import { asc, desc, eq, notInArray } from "drizzle-orm";
import { z } from "zod";
import { getDb } from "@/db";
import { admins, auditLogs, bookingActivity, bookingBlocks, bookingEvidence, bookingOccurrences, bookingRequests, collaborations, contentItems, corCalendarEvents, dataRequests, eventCollaborations, formSubmissions, integrations, liveCorItems, notificationOutbox, publicDocuments } from "@/db/schema";
import { requireAdmin, requireAdminRole } from "@/lib/admin";
import { writeAudit } from "@/lib/audit";
import { defaultCollaborations } from "@/lib/default-collaborations";
import { associationBrand, ASK_PURPLE, effectiveAssociationColor } from "@/lib/association-brand";
import { INITIAL_COR_CALENDAR, parseCorCalendar } from "@/lib/cor-calendar";
import { bookingRetentionDate, helsinkiLocalToIso } from "@/lib/booking";

export const dynamic = "force-dynamic";

const collaborationSchema=z.object({id:z.string().optional(),slug:z.string().min(1).regex(/^[a-z0-9-]+$/),name:z.string().min(1),type:z.enum(["association","sponsor","company","partner","alumni"]),shortDescriptionSv:z.string().default(""),shortDescriptionEn:z.string().default(""),descriptionSv:z.string().default(""),descriptionEn:z.string().default(""),websiteUrl:z.string().default(""),logoUrl:z.string().default(""),brandColor:z.string().regex(/^#[0-9a-f]{6}$/i).default(ASK_PURPLE),contactName:z.string().default(""),contactEmail:z.string().default(""),agreementStartsAt:z.string().nullable().optional(),agreementEndsAt:z.string().nullable().optional(),approvalStatus:z.enum(["draft","approved","expired"]).default("draft"),internalNotes:z.string().default(""),active:z.boolean().default(true),visible:z.boolean().default(true),featured:z.boolean().default(false)});
const calendarImportSchema=z.object({icalText:z.string().min(20).max(2_000_000)});
const liveSchema=z.object({id:z.string().optional(),type:z.enum(["status","office_hours","presence","public_event"]),titleSv:z.string().min(1),titleEn:z.string().default(""),descriptionSv:z.string().default(""),descriptionEn:z.string().default(""),collaborationId:z.string().nullable().optional(),startsAt:z.string().nullable().optional(),endsAt:z.string().nullable().optional(),space:z.string().default(""),active:z.boolean().default(true),visiblePublicly:z.boolean().default(false)});
const bookingUpdateSchema=z.object({id:z.string(),status:z.enum(["pending","quoted","approved","contract_sent","signed","cancelled"]),finalPriceCents:z.number().int().nullable().optional(),depositCents:z.number().int().min(0).default(0),amountPaidCents:z.number().int().min(0).default(0),invoiceStatus:z.enum(["not_required","draft","sent","paid","overdue","credited"]),contractLanguage:z.enum(["sv","en","fi"]),contractStatus:z.enum(["not_required","draft","sent","signed","declined"]),memberVerified:z.boolean().default(false),associationVerified:z.boolean().default(false),cleaningStatus:z.enum(["not_checked","approved","needs_cleaning","disputed"]),cleaningFeeCents:z.number().int().min(0).default(0),damageChargeCents:z.number().int().min(0).default(0),doorCode:z.string().max(80).default(""),internalNotes:z.string().max(4000).default("")});
const linkSchema=z.object({eventId:z.string(),collaborationId:z.string(),role:z.enum(["sponsor","partner","organizer","host"]),visiblePublicly:z.boolean().default(true)});
const blockSchema=z.object({id:z.string().optional(),startsAt:z.string().min(1),endsAt:z.string().min(1),resources:z.array(z.enum(["hall","kitchen","cabinet_sauna"])).min(1),reasonSv:z.string().default(""),reasonEn:z.string().default(""),active:z.boolean().default(true)});
const documentSchema=z.object({id:z.string().optional(),slug:z.string().min(1).regex(/^[a-z0-9-]+$/),category:z.enum(["council_agenda","council_minutes","bylaws","regulation","policy","form","annual_report","other"]),titleSv:z.string().min(1),titleEn:z.string().default(""),descriptionSv:z.string().default(""),descriptionEn:z.string().default(""),fileUrl:z.string().min(1),meetingDate:z.string().nullable().optional(),language:z.string().default("sv"),status:z.enum(["draft","published"]).default("draft")});
const adminSchema=z.object({email:z.string().email(),displayName:z.string().min(1),role:z.enum(["super_admin","admin","editor","association_rep"]),active:z.boolean().default(true)});
const integrationSchema=z.object({id:z.string().optional(),provider:z.string().min(1),category:z.enum(["email","membership","crm","analytics","calendar","accounting","payment","other"]),status:z.enum(["planned","configured","active","paused"]).default("planned"),purpose:z.string().default(""),personalData:z.string().default(""),dataRegion:z.string().default(""),dpaReviewedAt:z.string().nullable().optional(),enabled:z.boolean().default(false)});
const evidenceSchema=z.object({bookingId:z.string(),type:z.enum(["cleaning_before","cleaning_after","damage","access","other"]).default("other"),fileUrl:z.string().min(1),note:z.string().max(1000).default(""),shareWithBooker:z.boolean().default(false)});

function superAdmin(auth: NonNullable<Awaited<ReturnType<typeof requireAdmin>>>) { return auth.admin.role === "super_admin"; }

export async function GET(){
  const auth=await requireAdminRole(["super_admin","admin"]);if(!auth)return Response.json({error:"Forbidden"},{status:403});
  const db=getDb();
  const [partnerRows,liveRows,calendarRows,bookingRows,occurrenceRows,evidenceRows,eventRows,linkRows,blockRows,documentRows,requestRows,submissionRows,notificationRows,integrationRows,auditRows,adminRows]=await Promise.all([
    db.select().from(collaborations).orderBy(desc(collaborations.featured),asc(collaborations.name)),
    db.select().from(liveCorItems).orderBy(desc(liveCorItems.updatedAt)),
    db.select().from(corCalendarEvents).orderBy(desc(corCalendarEvents.startsAt)).limit(500),
    db.select().from(bookingRequests).orderBy(desc(bookingRequests.createdAt)).limit(200),
    db.select().from(bookingOccurrences).orderBy(asc(bookingOccurrences.startsAt)).limit(1000),
    db.select().from(bookingEvidence).orderBy(desc(bookingEvidence.createdAt)).limit(1000),
    db.select().from(contentItems).where(eq(contentItems.type,"event")).orderBy(desc(contentItems.updatedAt)),
    db.select().from(eventCollaborations).orderBy(asc(eventCollaborations.sortOrder)),
    db.select().from(bookingBlocks).orderBy(desc(bookingBlocks.startsAt)).limit(200),
    db.select().from(publicDocuments).orderBy(desc(publicDocuments.meetingDate),desc(publicDocuments.updatedAt)).limit(300),
    db.select().from(dataRequests).orderBy(desc(dataRequests.createdAt)).limit(200),
    db.select().from(formSubmissions).orderBy(desc(formSubmissions.createdAt)).limit(300),
    db.select().from(notificationOutbox).orderBy(desc(notificationOutbox.createdAt)).limit(300),
    db.select().from(integrations).orderBy(asc(integrations.category),asc(integrations.provider)),
    db.select().from(auditLogs).orderBy(desc(auditLogs.createdAt)).limit(200),
    superAdmin(auth)?db.select().from(admins).orderBy(asc(admins.email)):Promise.resolve([]),
  ]);
  return Response.json({collaborations:partnerRows.map(row=>({...row,brandColor:effectiveAssociationColor(row.slug,row.brandColor)})),liveCor:liveRows,corCalendar:calendarRows.length?calendarRows.map(row=>({...row,resources:JSON.parse(row.resources)})):INITIAL_COR_CALENDAR.map(row=>({...row,id:`seed:${row.sourceUid}`})),bookings:bookingRows.map(item=>({...item,occurrences:occurrenceRows.filter(row=>row.bookingId===item.id).map(row=>({...row,resources:JSON.parse(row.resources)})),evidence:evidenceRows.filter(row=>row.bookingId===item.id)})),events:eventRows,eventCollaborations:linkRows,bookingBlocks:blockRows.map(row=>({...row,resources:JSON.parse(row.resources)})),documents:documentRows,dataRequests:requestRows,formSubmissions:submissionRows,notifications:notificationRows,integrations:integrationRows,auditLogs:auditRows,admins:adminRows,currentAdmin:auth.admin});
}

export async function POST(request:Request){
  const auth=await requireAdminRole(["super_admin","admin"]);if(!auth)return Response.json({error:"Forbidden"},{status:403});
  const body=await request.json() as Record<string,unknown>;const entity=String(body.entity||"");const db=getDb();
  if(entity==="collaboration"){const p=collaborationSchema.parse(body.data);const id=crypto.randomUUID();const [row]=await db.insert(collaborations).values({...p,id,agreementStartsAt:p.agreementStartsAt||null,agreementEndsAt:p.agreementEndsAt||null}).returning();await writeAudit(auth.user.email,"create","collaboration",id);return Response.json({item:row},{status:201});}
  if(entity==="import_defaults"){let count=0;for(const item of defaultCollaborations){const found=await db.select({id:collaborations.id}).from(collaborations).where(eq(collaborations.slug,item.slug)).limit(1);if(!found.length){await db.insert(collaborations).values({...item,id:crypto.randomUUID(),brandColor:associationBrand(item.slug)?.color||ASK_PURPLE,internalNotes:"Public directory default imported 2026-09-05; ASK must verify details before launch."});count++;}}await writeAudit(auth.user.email,"import_defaults","collaboration","defaults",{count});return Response.json({count},{status:201});}
  if(entity==="calendar_import"){const p=calendarImportSchema.safeParse(body.data);if(!p.success)return Response.json({error:p.error.issues[0]?.message||"Invalid iCalendar file"},{status:400});const events=parseCorCalendar(p.data.icalText);if(!events.length)return Response.json({error:"No valid Cor bookings were found in this iCalendar file."},{status:400});const now=new Date().toISOString();for(const item of events){const values={...item,id:crypto.randomUUID(),resources:JSON.stringify(item.resources),importedAt:now,importedBy:auth.user.email};await db.insert(corCalendarEvents).values(values).onConflictDoUpdate({target:corCalendarEvents.sourceUid,set:{titleSv:item.titleSv,titleEn:item.titleEn,associationSlug:item.associationSlug,brandColor:item.brandColor,startsAt:item.startsAt,endsAt:item.endsAt,resources:JSON.stringify(item.resources),category:item.category,tentative:item.tentative,allDay:item.allDay,visiblePublicly:item.visiblePublicly,active:true,sourceUpdatedAt:item.sourceUpdatedAt,importedAt:now,importedBy:auth.user.email}});}const sourceUids=events.map(item=>item.sourceUid);await db.update(corCalendarEvents).set({active:false,importedAt:now,importedBy:auth.user.email}).where(notInArray(corCalendarEvents.sourceUid,sourceUids));await writeAudit(auth.user.email,"import","cor_calendar","google_ical",{count:events.length});return Response.json({count:events.length},{status:201});}
  if(entity==="live_cor"){const p=liveSchema.parse(body.data);const id=crypto.randomUUID();const startsAt=helsinkiLocalToIso(p.startsAt),endsAt=helsinkiLocalToIso(p.endsAt);if(startsAt&&endsAt&&endsAt<=startsAt)return Response.json({error:"End must be after start"},{status:400});const [row]=await db.insert(liveCorItems).values({...p,id,collaborationId:p.collaborationId||null,startsAt,endsAt,createdBy:auth.user.email}).returning();await writeAudit(auth.user.email,"create","live_cor",id);return Response.json({item:row},{status:201});}
  if(entity==="event_collaboration"){const p=linkSchema.parse(body.data);const [row]=await db.insert(eventCollaborations).values(p).onConflictDoUpdate({target:[eventCollaborations.eventId,eventCollaborations.collaborationId],set:{role:p.role,visiblePublicly:p.visiblePublicly}}).returning();await writeAudit(auth.user.email,"link","event_collaboration",String(row.id),p);return Response.json({item:row},{status:201});}
  if(entity==="booking_block"){const p=blockSchema.parse(body.data),startsAt=helsinkiLocalToIso(p.startsAt),endsAt=helsinkiLocalToIso(p.endsAt);if(!startsAt||!endsAt||endsAt<=startsAt)return Response.json({error:"Invalid time range"},{status:400});const id=crypto.randomUUID();const [row]=await db.insert(bookingBlocks).values({...p,id,startsAt,endsAt,resources:JSON.stringify(p.resources),createdBy:auth.user.email}).returning();await writeAudit(auth.user.email,"create","booking_block",id);return Response.json({item:row},{status:201});}
  if(entity==="document"){const p=documentSchema.parse(body.data);const id=crypto.randomUUID();const [row]=await db.insert(publicDocuments).values({...p,id,meetingDate:p.meetingDate||null,createdBy:auth.user.email}).returning();await writeAudit(auth.user.email,"create","document",id);return Response.json({item:row},{status:201});}
  if(entity==="admin"){if(!superAdmin(auth))return Response.json({error:"Super administrator required"},{status:403});const p=adminSchema.parse(body.data);const [row]=await db.insert(admins).values(p).onConflictDoUpdate({target:admins.email,set:p}).returning();await writeAudit(auth.user.email,"upsert","admin",row.email,{role:row.role});return Response.json({item:row},{status:201});}
  if(entity==="integration"){const p=integrationSchema.parse(body.data);const id=p.id||crypto.randomUUID();const values={...p,id,dpaReviewedAt:p.dpaReviewedAt||null,updatedBy:auth.user.email};const [row]=await db.insert(integrations).values(values).onConflictDoUpdate({target:integrations.provider,set:{...values,updatedAt:new Date().toISOString()}}).returning();await writeAudit(auth.user.email,"upsert","integration",id,{provider:p.provider,status:p.status,enabled:p.enabled});return Response.json({item:row},{status:201});}
  if(entity==="booking_evidence"){const p=evidenceSchema.parse(body.data),id=crypto.randomUUID();const [row]=await db.insert(bookingEvidence).values({...p,id,createdBy:auth.user.email}).returning();await db.insert(bookingActivity).values({bookingId:p.bookingId,action:"evidence_added",actor:auth.user.email,notes:p.note,metadata:JSON.stringify({type:p.type,shareWithBooker:p.shareWithBooker})});await writeAudit(auth.user.email,"create","booking_evidence",id,{bookingId:p.bookingId,type:p.type});return Response.json({item:row},{status:201});}
  return Response.json({error:"Unknown entity"},{status:400});
}

export async function PATCH(request:Request){
  const auth=await requireAdminRole(["super_admin","admin"]);if(!auth)return Response.json({error:"Forbidden"},{status:403});
  const body=await request.json() as Record<string,unknown>;const entity=String(body.entity||"");const db=getDb();const now=new Date().toISOString();
  if(entity==="collaboration"){const p=collaborationSchema.parse(body.data);if(!p.id)return Response.json({error:"Missing id"},{status:400});const [row]=await db.update(collaborations).set({...p,agreementStartsAt:p.agreementStartsAt||null,agreementEndsAt:p.agreementEndsAt||null,updatedAt:now}).where(eq(collaborations.id,p.id)).returning();await writeAudit(auth.user.email,"update","collaboration",p.id);return Response.json({item:row});}
  if(entity==="live_cor"){const p=liveSchema.parse(body.data);if(!p.id)return Response.json({error:"Missing id"},{status:400});const startsAt=helsinkiLocalToIso(p.startsAt),endsAt=helsinkiLocalToIso(p.endsAt);if(startsAt&&endsAt&&endsAt<=startsAt)return Response.json({error:"End must be after start"},{status:400});const [row]=await db.update(liveCorItems).set({...p,collaborationId:p.collaborationId||null,startsAt,endsAt,updatedAt:now}).where(eq(liveCorItems.id,p.id)).returning();await writeAudit(auth.user.email,"update","live_cor",p.id);return Response.json({item:row});}
  if(entity==="booking"){const p=bookingUpdateSchema.parse(body.data);const existing=(await db.select().from(bookingRequests).where(eq(bookingRequests.id,p.id)).limit(1))[0];if(!existing)return Response.json({error:"Not found"},{status:404});if(existing.status==="cancelled"&&p.status!=="cancelled")return Response.json({error:"Cancelled bookings cannot be reopened because their times have been released. Create a new booking instead."},{status:409});const retentionClass:"request"|"operational"|"accounting"=["sent","paid","overdue","credited"].includes(p.invoiceStatus)?"accounting":["approved","contract_sent","signed"].includes(p.status)?"operational":"request";const occurrenceEnds=await db.select({endsAt:bookingOccurrences.endsAt}).from(bookingOccurrences).where(eq(bookingOccurrences.bookingId,p.id));const lastBookingEnd=occurrenceEnds.reduce((latest,item)=>item.endsAt>latest?item.endsAt:latest,existing.endsAt);const retentionBase=retentionClass==="request"?new Date(existing.createdAt):new Date(lastBookingEnd);const values={...p,doorCode:p.contractStatus==="signed"?p.doorCode:existing.doorCode,cancelledAt:p.status==="cancelled"?(existing.cancelledAt||now):null,retentionUntil:bookingRetentionDate(retentionBase,retentionClass),updatedAt:now};const [row]=await db.update(bookingRequests).set(values).where(eq(bookingRequests.id,p.id)).returning();if(p.status==="cancelled")await db.update(bookingOccurrences).set({status:"cancelled"}).where(eq(bookingOccurrences.bookingId,p.id));await db.insert(bookingActivity).values({bookingId:p.id,action:"admin_update",actor:auth.user.email,metadata:JSON.stringify({from:existing.status,to:p.status,invoiceStatus:p.invoiceStatus,contractStatus:p.contractStatus})});if(existing.status!==p.status||existing.invoiceStatus!==p.invoiceStatus||existing.contractStatus!==p.contractStatus)await db.insert(notificationOutbox).values({id:crypto.randomUUID(),template:"booking_status_changed",recipient:existing.contactEmail,locale:p.contractLanguage,payload:JSON.stringify({reference:existing.reference,status:p.status,invoiceStatus:p.invoiceStatus,contractStatus:p.contractStatus})});await writeAudit(auth.user.email,"update","booking",p.id,{status:p.status});return Response.json({item:row});}
  if(entity==="booking_block"){const p=blockSchema.parse(body.data);if(!p.id)return Response.json({error:"Missing id"},{status:400});const startsAt=helsinkiLocalToIso(p.startsAt),endsAt=helsinkiLocalToIso(p.endsAt);if(!startsAt||!endsAt||endsAt<=startsAt)return Response.json({error:"Invalid time range"},{status:400});const [row]=await db.update(bookingBlocks).set({...p,startsAt,endsAt,resources:JSON.stringify(p.resources)}).where(eq(bookingBlocks.id,p.id)).returning();await writeAudit(auth.user.email,"update","booking_block",p.id);return Response.json({item:row});}
  if(entity==="document"){const p=documentSchema.parse(body.data);if(!p.id)return Response.json({error:"Missing id"},{status:400});const [row]=await db.update(publicDocuments).set({...p,meetingDate:p.meetingDate||null,updatedAt:now}).where(eq(publicDocuments.id,p.id)).returning();await writeAudit(auth.user.email,"update","document",p.id);return Response.json({item:row});}
  if(entity==="data_request"){const p=z.object({id:z.string(),status:z.enum(["received","verifying","processing","completed","rejected"])}).parse(body.data);const [row]=await db.update(dataRequests).set({status:p.status,updatedAt:now}).where(eq(dataRequests.id,p.id)).returning();await writeAudit(auth.user.email,"update","data_request",p.id,{status:p.status});return Response.json({item:row});}
  if(entity==="form_submission"){const p=z.object({id:z.string(),status:z.enum(["new","in_progress","answered","closed"])}).parse(body.data);const [row]=await db.update(formSubmissions).set({status:p.status,updatedAt:now}).where(eq(formSubmissions.id,p.id)).returning();await writeAudit(auth.user.email,"update","form_submission",p.id,{status:p.status});return Response.json({item:row});}
  if(entity==="notification"){const p=z.object({id:z.string(),status:z.enum(["pending","cancelled"])}).parse(body.data);const [row]=await db.update(notificationOutbox).set({status:p.status,lastError:""}).where(eq(notificationOutbox.id,p.id)).returning();await writeAudit(auth.user.email,"update","notification",p.id,{status:p.status});return Response.json({item:row});}
  return Response.json({error:"Unknown entity"},{status:400});
}

export async function DELETE(request:Request){
  const auth=await requireAdminRole(["super_admin","admin"]);if(!auth)return Response.json({error:"Forbidden"},{status:403});
  const body=await request.json() as{entity?:string;id?:string};if(!body.id)return Response.json({error:"Missing id"},{status:400});const db=getDb();
  if(body.entity==="collaboration")await db.delete(collaborations).where(eq(collaborations.id,body.id));
  else if(body.entity==="live_cor")await db.delete(liveCorItems).where(eq(liveCorItems.id,body.id));
  else if(body.entity==="event_collaboration")await db.delete(eventCollaborations).where(eq(eventCollaborations.id,Number(body.id)));
  else if(body.entity==="booking_block")await db.delete(bookingBlocks).where(eq(bookingBlocks.id,body.id));
  else if(body.entity==="calendar_event")await db.delete(corCalendarEvents).where(eq(corCalendarEvents.id,body.id));
  else if(body.entity==="document")await db.delete(publicDocuments).where(eq(publicDocuments.id,body.id));
  else if(body.entity==="booking"){const [existing]=await db.select({deletedAt:bookingRequests.deletedAt}).from(bookingRequests).where(eq(bookingRequests.id,body.id)).limit(1);if(!existing)return Response.json({error:"Not found"},{status:404});if(existing.deletedAt)return Response.json({ok:true,alreadyDeleted:true});await db.update(bookingRequests).set({deletedAt:new Date().toISOString(),deletedBy:auth.user.email}).where(eq(bookingRequests.id,body.id));await db.update(bookingOccurrences).set({status:"cancelled"}).where(eq(bookingOccurrences.bookingId,body.id));await db.insert(bookingActivity).values({bookingId:body.id,action:"soft_deleted",actor:auth.user.email});}
  else return Response.json({error:"Unknown entity"},{status:400});
  await writeAudit(auth.user.email,"delete",body.entity,body.id);return Response.json({ok:true});
}
