"use client";
import { useEffect, useState } from "react";
import { ArrowLeft, CalendarRange, Save, SlidersHorizontal, Trash2 } from "lucide-react";
import { toast } from "sonner";
import { Toaster } from "@/components/ui/sonner";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Switch } from "@/components/ui/switch";

type Policy={externalFirstHours:number;externalFirstHourlyCents:number;externalAfterHourlyCents:number;externalKitchenCents:number;saunaPerDateCents:number;associationWeekendCents:number;associationPackage3Cents:number;associationPackage5Cents:number;associationPackage10Cents:number;internalFreeBookings:number;maxBookingHours:number;maxAdvanceMonths:number;maxDatesPerRequest:number;hallCapacity:number;kitchenCapacity:number;saunaCapacity:number;cleaningFeeCents:number};
type Theme={id:string;name:string;theme:string;startsAt:string;endsAt:string;active:boolean};
const defaultPolicy:Policy={externalFirstHours:4,externalFirstHourlyCents:5000,externalAfterHourlyCents:3000,externalKitchenCents:5000,saunaPerDateCents:3000,associationWeekendCents:7500,associationPackage3Cents:21000,associationPackage5Cents:32500,associationPackage10Cents:60000,internalFreeBookings:1,maxBookingHours:18,maxAdvanceMonths:18,maxDatesPerRequest:10,hallCapacity:80,kitchenCapacity:8,saunaCapacity:20,cleaningFeeCents:15000};
const blankTheme={name:"",theme:"gulis",startsAt:"",endsAt:"",active:true};
const moneyFields:{key:keyof Policy;label:string}[]=[{key:"externalFirstHourlyCents",label:"External first hourly rate"},{key:"externalAfterHourlyCents",label:"External later hourly rate"},{key:"externalKitchenCents",label:"External kitchen add-on"},{key:"saunaPerDateCents",label:"Sauna per date"},{key:"associationWeekendCents",label:"Association Fri–Sun"},{key:"associationPackage3Cents",label:"Association package · 3"},{key:"associationPackage5Cents",label:"Association package · 5"},{key:"associationPackage10Cents",label:"Association package · 10"},{key:"cleaningFeeCents",label:"Cleaning fee"}];
const numberFields:{key:keyof Policy;label:string}[]=[{key:"externalFirstHours",label:"External base hours"},{key:"internalFreeBookings",label:"Internal free bookings / mandate year"},{key:"maxBookingHours",label:"Maximum hours / date"},{key:"maxAdvanceMonths",label:"Maximum advance months"},{key:"maxDatesPerRequest",label:"Maximum dates / request"},{key:"hallCapacity",label:"Hall capacity"},{key:"kitchenCapacity",label:"Kitchen capacity"},{key:"saunaCapacity",label:"Cabinet & sauna capacity"}];

export default function SettingsDashboard(){const[policy,setPolicy]=useState(defaultPolicy),[themes,setThemes]=useState<Theme[]>([]),[theme,setTheme]=useState(blankTheme),[loading,setLoading]=useState(true);async function load(){const r=await fetch("/api/admin/settings"),d=await r.json();if(r.ok){setPolicy({...defaultPolicy,...d.policy});setThemes(d.themes||[])}else toast.error(d.error||"Could not load settings");setLoading(false)}useEffect(()=>{load()},[]);async function savePolicy(){const r=await fetch("/api/admin/settings",{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify(policy)}),d=await r.json();if(r.ok)toast.success("Booking rules saved");else toast.error(d.error||"Could not save")}async function saveTheme(){const r=await fetch("/api/admin/settings",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(theme)}),d=await r.json();if(!r.ok)return toast.error(d.error||"Could not save");toast.success("Theme scheduled");setTheme(blankTheme);await load()}async function remove(id:string){const r=await fetch("/api/admin/settings",{method:"DELETE",headers:{"content-type":"application/json"},body:JSON.stringify({id})});if(r.ok){toast.success("Theme removed");await load()}}
return <main className="settings-admin"><header><a href="/admin/platform"><ArrowLeft/>Platform</a><div><span>ASK Backoffice</span><h1>Rules &amp; themes</h1></div></header>{loading?<p>Loading…</p>:<><section className="settings-card"><h2><SlidersHorizontal/>Cor booking configuration</h2><p>Changes apply to new estimates and booking requests. Prices are entered in euros.</p><div className="settings-grid">{moneyFields.map(({key,label})=><div key={key}><Label>{label} (€)</Label><Input type="number" min="0" step="0.01" value={(Number(policy[key])/100).toFixed(2)} onChange={e=>setPolicy({...policy,[key]:Math.round((Number(e.target.value)||0)*100)})}/></div>)}{numberFields.map(({key,label})=><div key={key}><Label>{label}</Label><Input type="number" min="0" step="1" value={policy[key]} onChange={e=>setPolicy({...policy,[key]:Math.round(Number(e.target.value)||0)})}/></div>)}</div><Button onClick={savePolicy}><Save/>Save booking rules</Button></section><section className="settings-card"><h2><CalendarRange/>Seasonal theme scheduler</h2><p>Scheduled themes override the automatic seasonal defaults. Overlapping active periods are blocked.</p><div className="theme-form"><div><Label>Name</Label><Input value={theme.name} onChange={e=>setTheme({...theme,name:e.target.value})}/></div><div><Label>Theme</Label><Select value={theme.theme} onValueChange={value=>setTheme({...theme,theme:value})}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{["default","gulis","christmas","new_year","vappu","midsummer","halloween","pride","independence","swedish_day"].map(item=><SelectItem value={item} key={item}>{item.replaceAll("_"," ")}</SelectItem>)}</SelectContent></Select></div><div><Label>Starts</Label><Input type="datetime-local" value={theme.startsAt} onChange={e=>setTheme({...theme,startsAt:e.target.value})}/></div><div><Label>Ends</Label><Input type="datetime-local" value={theme.endsAt} onChange={e=>setTheme({...theme,endsAt:e.target.value})}/></div><label><Switch checked={theme.active} onCheckedChange={active=>setTheme({...theme,active})}/>Active</label><Button disabled={!theme.name||!theme.startsAt||!theme.endsAt} onClick={saveTheme}><Save/>Schedule</Button></div><div className="theme-list">{themes.map(item=><article key={item.id}><div><b>{item.name}</b><span>{item.theme.replaceAll("_"," ")} · {new Date(item.startsAt).toLocaleString("fi-FI",{dateStyle:"short",timeStyle:"short",hour12:false})} – {new Date(item.endsAt).toLocaleString("fi-FI",{dateStyle:"short",timeStyle:"short",hour12:false})}</span></div><Button variant="ghost" size="icon" onClick={()=>remove(item.id)}><Trash2/></Button></article>)}</div></section></>}<Toaster richColors/></main>}
