import { env } from "cloudflare:workers";

export const dynamic = "force-dynamic";
const LAT=60.2036,LON=24.9804;

async function weather(){const url=new URL("https://api.open-meteo.com/v1/forecast");url.searchParams.set("latitude",String(LAT));url.searchParams.set("longitude",String(LON));url.searchParams.set("current","temperature_2m,apparent_temperature,precipitation,weather_code,wind_speed_10m");url.searchParams.set("timezone","Europe/Helsinki");const response=await fetch(url,{headers:{accept:"application/json"}});if(!response.ok)throw new Error("weather unavailable");const data=await response.json() as{current?:Record<string,number|string>};return data.current||null}

async function transit(){const key=String(env.DIGITRANSIT_SUBSCRIPTION_KEY||"");if(!key)return {configured:false,stops:[]};const query=`{stopsByRadius(lat:${LAT},lon:${LON},radius:700){edges{node{distance stop{gtfsId name stoptimesWithoutPatterns(numberOfDepartures:3){serviceDay realtimeDeparture scheduledDeparture realtime headsign trip{route{shortName}}}}}}}}`;const response=await fetch("https://api.digitransit.fi/routing/v2/hsl/gtfs/v1",{method:"POST",headers:{"content-type":"application/graphql","digitransit-subscription-key":key},body:query});if(!response.ok)throw new Error("transit unavailable");const data=await response.json() as{data?:{stopsByRadius?:{edges?:Array<{node:{distance:number;stop:{gtfsId:string;name:string;stoptimesWithoutPatterns:Array<{serviceDay:number;realtimeDeparture:number;scheduledDeparture:number;realtime:boolean;headsign:string;trip:{route:{shortName:string}}}>}}}>}}};const stops=(data.data?.stopsByRadius?.edges||[]).filter(item=>item.node.stop.stoptimesWithoutPatterns.length).sort((a,b)=>a.node.distance-b.node.distance).slice(0,3).map(({node})=>({id:node.stop.gtfsId,name:node.stop.name,distance:Math.round(node.distance),departures:node.stop.stoptimesWithoutPatterns.map(item=>({route:item.trip.route.shortName,headsign:item.headsign,realtime:item.realtime,at:new Date((item.serviceDay+(item.realtimeDeparture||item.scheduledDeparture))*1000).toISOString()}))}));return {configured:true,stops}}

export async function GET(){const [weatherResult,transitResult]=await Promise.allSettled([weather(),transit()]);return Response.json({weather:weatherResult.status==="fulfilled"?weatherResult.value:null,transit:transitResult.status==="fulfilled"?transitResult.value:{configured:Boolean(env.DIGITRANSIT_SUBSCRIPTION_KEY),stops:[]},reittiopasUrl:"https://www.hsl.fi/en/journey-planner?to=Majstadsgatan%2011%2C%20Helsinki"},{headers:{"Cache-Control":"public, max-age=120"}})}
