import { ContractLanguage } from './types';
export const CONTRACT_TEMPLATE_VERSION='2026.2-cor-house';
export const CONTRACT_TERMS_VERSION='2026.2-cor-house';
export const CONTRACT_PLACEHOLDERS=['{{bookingReference}}','{{contractDate}}','{{customerName}}','{{organization}}','{{billingAddress}}','{{resourceName}}','{{bookingDate}}','{{startTime}}','{{endTime}}','{{participants}}','{{purpose}}','{{rentalPrice}}','{{kitchenFee}}','{{saunaFee}}','{{totalPrice}}','{{doorCode}}','{{termsVersion}}'] as const;
export interface ContractTemplate{title:string;labels:Record<string,string>;terms:string[];liability:string[];accessInstructions:string;signatureLandlord:string;signatureTenant:string}
const svTerms=[
 'Hyresgästen har tillgång till och ansvarar för de utrymmen som avtalats om.',
 'Hyresgästen ansvarar för all verksamhet som sker i lokalen under avtalsperioden.',
 'Utrymmena ska återlämnas i samma skick som vid inledandet av hyresavtalet.',
 'Hyresvärden kan utföra inspektion efter hyresperioden.',
 'Bord och stolar ska vara rena och ordnade på samma sätt som vid inledandet.',
 'En städavgift om 150€ + moms kan faktureras om lokalerna inte är städade.',
 'Vid skador ersätter hyresgästen samtliga reparationskostnader.',
 'Hyresgästen ansvarar för kostnader för eventuella onödiga brandlarm.',
 'Hyran faktureras efter tillställningen om inget annat avtalats.',
 'Avtalet är uppgjort i två likalydande exemplar, ett för vardera parten.',
];
export const contractTemplates:Record<ContractLanguage,ContractTemplate>={
 en:{title:'Rental Contract - Cor House',labels:{reference:'Booking reference',contractDate:'Contract date',language:'Contract language',landlord:'Landlord',tenant:'Tenant',billing:'Billing address',object:'Rental object',period:'Rental period',type:'Booking type',participants:'Participants',purpose:'Purpose',organization:'Organization',email:'Email',phone:'Phone',vat:'VAT / Business ID',billingReference:'Reference',notApplicable:'Not applicable',priceBreakdown:'Rent',rental:'Rental price',kitchen:'Kitchen',sauna:'Sauna',discount:'Discount / free benefit',total:'Total',doorCode:'Access / door code',terms:'Rental terms',liability:'Cleaning and damage liability',signatures:'Signatures'},terms:['The tenant has access to and is responsible for the agreed premises.','The tenant is responsible for all activity in the premises during the rental period.','The premises must be returned in the same condition as at the start of the rental contract.','The landlord may inspect the premises after the rental period.','Tables and chairs must be clean and arranged as they were at the start.','A cleaning fee of 150€ + VAT may be invoiced if the premises are not cleaned.','The tenant compensates all repair costs for damage.','The tenant is responsible for costs caused by unnecessary fire alarms.','Rent is invoiced after the event unless otherwise agreed.','The contract is made in two identical copies, one for each party.'],liability:[],accessInstructions:'The door code is confidential and valid only for the agreed booking.',signatureLandlord:'Landlord representative',signatureTenant:'Tenant representative'},
 sv:{title:'Hyresavtal - Cor-huset',labels:{reference:'Bokningsreferens',contractDate:'Avtalsdatum',language:'Avtalsspråk',landlord:'Hyresvärd',tenant:'Hyresgäst',billing:'Faktureringsadress',object:'Hyresobjekt',period:'Avtalsperiod',type:'Bokningstyp',participants:'Deltagare',purpose:'Syfte',organization:'Organisation',email:'E-post',phone:'Telefon',vat:'FO-nummer / momsnummer',billingReference:'Referens',notApplicable:'Ej tillämpligt',priceBreakdown:'Hyra',rental:'Hyra',kitchen:'Kök',sauna:'Bastu',discount:'Rabatt / kostnadsfri förmån',total:'Totalt',doorCode:'Tillträde / dörrkod',terms:'Hyresvillkor',liability:'Städnings- och skadeansvar',signatures:'Underskrifter'},terms:svTerms,liability:[],accessInstructions:'Dörrkoden är konfidentiell och gäller endast för den avtalade bokningen.',signatureLandlord:'Hyresgivarens representant',signatureTenant:'Hyresgästens representant'},
 fi:{title:'Vuokrasopimus - Cor-talo',labels:{reference:'Varausviite',contractDate:'Sopimuspäivä',language:'Sopimuskieli',landlord:'Vuokranantaja',tenant:'Vuokralainen',billing:'Laskutusosoite',object:'Vuokrakohde',period:'Vuokra-aika',type:'Varaustyyppi',participants:'Osallistujat',purpose:'Käyttötarkoitus',organization:'Organisaatio',email:'Sähköposti',phone:'Puhelin',vat:'Y-tunnus / ALV-tunnus',billingReference:'Viite',notApplicable:'Ei sovelleta',priceBreakdown:'Vuokra',rental:'Vuokra',kitchen:'Keittiö',sauna:'Sauna',discount:'Alennus / maksuton etu',total:'Yhteensä',doorCode:'Pääsy / ovikoodi',terms:'Vuokraehdot',liability:'Siivous- ja vahinkovastuu',signatures:'Allekirjoitukset'},terms:['Vuokralaisella on pääsy sovittuihin tiloihin ja vastuu niistä.','Vuokralainen vastaa kaikesta toiminnasta tiloissa vuokra-aikana.','Tilat on palautettava samassa kunnossa kuin vuokrasopimuksen alkaessa.','Vuokranantaja voi tarkastaa tilat vuokra-ajan jälkeen.','Pöytien ja tuolien tulee olla puhtaita ja järjestettyinä kuten alussa.','Siivousmaksu 150€ + alv voidaan laskuttaa, jos tiloja ei ole siivottu.','Vahingoista vuokralainen korvaa kaikki korjauskustannukset.','Vuokralainen vastaa tarpeettomien palohälytysten kustannuksista.','Vuokra laskutetaan tilaisuuden jälkeen, ellei muuta ole sovittu.','Sopimus laaditaan kahtena samansisältöisenä kappaleena.'],liability:[],accessInstructions:'Ovikoodi on luottamuksellinen ja voimassa vain sovitulle varaukselle.',signatureLandlord:'Vuokranantajan edustaja',signatureTenant:'Vuokralaisen edustaja'}
};
