import { RepresentativeBody } from './types';

export const defaultRepresentativeBodies: Array<Omit<RepresentativeBody, 'id' | 'createdAt' | 'updatedAt'>> = [
  {
    name: { sv: 'Yrkeshögskolans styrelse', en: 'Board of the University of Applied Sciences' },
    slug: 'yrkeshogskolans-styrelse',
    description: {
      sv: 'ASK väljer studeranderepresentant till Arcadas styrelse enligt stadgar och reglemente.',
      en: 'ASK appoints a student representative to Arcada’s board according to the statutes and regulations.',
    },
    category: 'statutory_arcada_body',
    appointingBody: 'fullmaktige',
    defaultTermLengthMonths: 24,
    defaultSeatCount: 1,
    eligibilityDescription: {
      sv: 'Valbarhet fastställs enligt ASK:s stadgar, valstadga och den aktuella utlysningen.',
      en: 'Eligibility is determined by ASK’s statutes, election regulations and the current call.',
    },
    applicationInstructions: { sv: 'Ansökan lämnas enligt den aktuella utlysningen.', en: 'Apply according to the current call.' },
    active: true,
    visible: true,
    displayOrder: 10,
  },
  {
    name: { sv: 'Omprövningsnämnden', en: 'Board of Review' },
    slug: 'omprovningsnamnden',
    description: {
      sv: 'Studeranderepresentanter deltar i Arcadas omprövningsnämnd enligt ASK:s specialuppdrag.',
      en: 'Student representatives participate in Arcada’s Board of Review as part of ASK’s special duties.',
    },
    category: 'statutory_arcada_body',
    appointingBody: 'fullmaktige',
    defaultTermLengthMonths: 24,
    defaultSeatCount: 1,
    defaultDeputySeatCount: 1,
    eligibilityDescription: {
      sv: 'Valbarhet fastställs enligt ASK:s stadgar, valstadga och den aktuella utlysningen.',
      en: 'Eligibility is determined by ASK’s statutes, election regulations and the current call.',
    },
    applicationInstructions: { sv: 'Ansökan lämnas enligt den aktuella utlysningen.', en: 'Apply according to the current call.' },
    active: true,
    visible: true,
    displayOrder: 20,
  },
  {
    name: { sv: 'Branschråd', en: 'Sector Councils' },
    slug: 'branschrad',
    description: {
      sv: 'Branschråden omfattar flera utbildningsområden. Utlysningen anger vilket branschråd och hur många platser som är aktuella.',
      en: 'Sector councils cover several fields of education. The call specifies the council and available seats.',
    },
    category: 'arcada_body',
    appointingBody: 'fullmaktige',
    defaultTermLengthMonths: 24,
    eligibilityDescription: {
      sv: 'Valbarhet och eventuella programspecifika krav anges i den aktuella utlysningen.',
      en: 'Eligibility and programme-specific requirements are specified in the current call.',
    },
    applicationInstructions: { sv: 'Ansökan lämnas enligt den aktuella utlysningen.', en: 'Apply according to the current call.' },
    active: true,
    visible: true,
    displayOrder: 30,
  },
  {
    name: { sv: 'Kvalitetsråd', en: 'Quality Council' },
    slug: 'kvalitetsrad',
    description: {
      sv: 'Kvalitetsrådet behandlar kvalitetsfrågor inom Arcada. Antalet platser kan variera enligt utlysningen.',
      en: 'The Quality Council handles quality matters at Arcada. The number of seats may vary by call.',
    },
    category: 'arcada_body',
    appointingBody: 'fullmaktige',
    defaultTermLengthMonths: 24,
    defaultSeatCount: 2,
    eligibilityDescription: {
      sv: 'Vanligen 1–2 studeranderepresentanter. Närmare valbarhet anges i utlysningen.',
      en: 'Usually 1–2 student representatives. Detailed eligibility is specified in the call.',
    },
    applicationInstructions: { sv: 'Ansökan lämnas enligt den aktuella utlysningen.', en: 'Apply according to the current call.' },
    active: true,
    visible: true,
    displayOrder: 40,
  },
  {
    name: { sv: 'Forskningsråd', en: 'Research Council' },
    slug: 'forskningsrad',
    description: {
      sv: 'Forskningsrådet behandlar forskningsrelaterade frågor där studerandeperspektivet ingår.',
      en: 'The Research Council handles research-related matters where the student perspective is included.',
    },
    category: 'arcada_body',
    appointingBody: 'fullmaktige',
    defaultTermLengthMonths: 24,
    defaultSeatCount: 1,
    eligibilityDescription: {
      sv: 'Valbarhet fastställs enligt ASK:s stadgar, valstadga och den aktuella utlysningen.',
      en: 'Eligibility is determined by ASK’s statutes, election regulations and the current call.',
    },
    applicationInstructions: { sv: 'Ansökan lämnas enligt den aktuella utlysningen.', en: 'Apply according to the current call.' },
    active: true,
    visible: true,
    displayOrder: 50,
  },
  {
    name: { sv: 'Pedagogiska rådet', en: 'Pedagogical Council' },
    slug: 'pedagogiska-radet',
    description: {
      sv: 'Pedagogiska rådet behandlar undervisnings- och lärandefrågor vid Arcada.',
      en: 'The Pedagogical Council handles teaching and learning matters at Arcada.',
    },
    category: 'arcada_body',
    appointingBody: 'fullmaktige',
    defaultTermLengthMonths: 24,
    defaultSeatCount: 1,
    eligibilityDescription: {
      sv: 'Valbarhet fastställs enligt ASK:s stadgar, valstadga och den aktuella utlysningen.',
      en: 'Eligibility is determined by ASK’s statutes, election regulations and the current call.',
    },
    applicationInstructions: { sv: 'Ansökan lämnas enligt den aktuella utlysningen.', en: 'Apply according to the current call.' },
    active: true,
    visible: true,
    displayOrder: 60,
  },
  {
    name: { sv: 'Rådet för kvalitet och samhällsansvar', en: 'Council for Quality and Social Responsibility' },
    slug: 'radet-for-kvalitet-och-samhallsansvar',
    description: {
      sv: 'Rådet behandlar frågor om kvalitet och samhällsansvar där studerandeperspektivet ska vara synligt.',
      en: 'The council handles quality and social responsibility matters where the student perspective should be visible.',
    },
    category: 'arcada_body',
    appointingBody: 'fullmaktige',
    defaultTermLengthMonths: 24,
    defaultSeatCount: 1,
    eligibilityDescription: {
      sv: 'Valbarhet fastställs enligt ASK:s stadgar, valstadga och den aktuella utlysningen.',
      en: 'Eligibility is determined by ASK’s statutes, election regulations and the current call.',
    },
    applicationInstructions: { sv: 'Ansökan lämnas enligt den aktuella utlysningen.', en: 'Apply according to the current call.' },
    active: true,
    visible: true,
    displayOrder: 70,
  },
];
