import { PublicLanguage } from '../localization/languages';

export type RepresentativesLocale = PublicLanguage;
export type RepresentativeBodyCategory = 'statutory_arcada_body' | 'arcada_body' | 'external_body' | 'other';
export type AppointingBody = 'fullmaktige' | 'board' | 'other';
export type RepresentativeRole = 'representative' | 'deputy';
export type RepresentativeStatus = 'active' | 'ended' | 'resigned' | 'dismissed';
export type RepresentativeCallStatus = 'coming_soon' | 'open' | 'closed';
export interface LocalizedText { sv: string; en: string; }
export interface RepresentativeBody { id: string; name: LocalizedText; slug: string; description: LocalizedText; category: RepresentativeBodyCategory; appointingBody: AppointingBody; defaultTermLengthMonths: number; defaultSeatCount?: number; defaultDeputySeatCount?: number; eligibilityDescription: LocalizedText; applicationInstructions: LocalizedText; active: boolean; visible: boolean; displayOrder: number; createdAt: Date; updatedAt: Date; }
export interface StudentRepresentative { id: string; bodyId: string; fullName: string; email?: string; contactPublic: boolean; studyProgramme?: string; role: RepresentativeRole; termStart: Date; termEnd: Date; status: RepresentativeStatus; appointedBy: AppointingBody; appointmentDate?: Date; publicProfile: boolean; photoUrl?: string; description: LocalizedText; displayOrder: number; createdAt: Date; updatedAt: Date; }
export interface RepresentativeCall { id: string; title: LocalizedText; bodyId?: string; description: LocalizedText; openingDate: Date; closingDate: Date; numberOfSeats: number; eligibility: LocalizedText; applicationInstructions: LocalizedText; ctaLabel: LocalizedText; ctaUrl?: string; contactEmail?: string; status: RepresentativeCallStatus; published: boolean; featured: boolean; displayOrder: number; createdAt: Date; updatedAt: Date; }
export interface PublicRepresentativeBody { id: string; name: string; slug: string; description: string; category: RepresentativeBodyCategory; appointingBody: AppointingBody; defaultTermLengthMonths: number; defaultSeatCount?: number; defaultDeputySeatCount?: number; eligibilityDescription: string; applicationInstructions: string; }
export interface PublicStudentRepresentative { id: string; bodyId: string; fullName: string; email?: string; studyProgramme?: string; role: RepresentativeRole; termStart: Date; termEnd: Date; status: RepresentativeStatus; appointedBy: AppointingBody; appointmentDate?: Date; photoUrl?: string; description: string; displayOrder: number; }
export interface PublicRepresentativeCall { id: string; title: string; bodyId?: string; body?: PublicRepresentativeBody; description: string; openingDate: Date; closingDate: Date; numberOfSeats: number; eligibility: string; applicationInstructions: string; ctaLabel: string; ctaUrl?: string; contactEmail?: string; status: RepresentativeCallStatus; featured: boolean; displayOrder: number; }
export interface PublicRepresentativeBodyDetail { body: PublicRepresentativeBody; representatives: PublicStudentRepresentative[]; calls: PublicRepresentativeCall[]; }
export interface CurrentRepresentativesGroup { body: PublicRepresentativeBody; representatives: PublicStudentRepresentative[]; }
export interface RepresentativesService { listPublicBodies(locale: RepresentativesLocale): Promise<PublicRepresentativeBody[]>; getPublicBody(slug: string, locale: RepresentativesLocale): Promise<PublicRepresentativeBodyDetail>; listCurrentRepresentatives(locale: RepresentativesLocale): Promise<CurrentRepresentativesGroup[]>; listPublicCalls(locale: RepresentativesLocale): Promise<PublicRepresentativeCall[]>; listBodies(): Promise<RepresentativeBody[]>; createBody(input: Omit<RepresentativeBody, 'id' | 'createdAt' | 'updatedAt'>): Promise<RepresentativeBody>; updateBody(id: string, input: Omit<RepresentativeBody, 'id' | 'createdAt' | 'updatedAt'>): Promise<RepresentativeBody>; deactivateBody(id: string): Promise<void>; listRepresentatives(): Promise<StudentRepresentative[]>; createRepresentative(input: Omit<StudentRepresentative, 'id' | 'createdAt' | 'updatedAt'>): Promise<StudentRepresentative>; updateRepresentative(id: string, input: Omit<StudentRepresentative, 'id' | 'createdAt' | 'updatedAt'>): Promise<StudentRepresentative>; deactivateRepresentative(id: string): Promise<void>; listCalls(): Promise<RepresentativeCall[]>; createCall(input: Omit<RepresentativeCall, 'id' | 'createdAt' | 'updatedAt' | 'status'> & { status?: RepresentativeCallStatus }): Promise<RepresentativeCall>; updateCall(id: string, input: Omit<RepresentativeCall, 'id' | 'createdAt' | 'updatedAt' | 'status'> & { status?: RepresentativeCallStatus }): Promise<RepresentativeCall>; deactivateCall(id: string): Promise<void>; }
