import { isThemeActive, resolveActiveTheme } from './activeThemeResolver';
import { WebsiteTheme } from '../types';
const base: WebsiteTheme = { id: '1', key: 'base', name: { sv: 'Bas', en: 'Base' }, type: 'seasonal', status: 'active', enabled: true, automaticActivation: true, manualOverride: false, priority: 1, recurringYearly: false, startDate: new Date('2026-01-01T00:00:00Z'), endDate: new Date('2026-01-31T23:59:59Z'), timezone: 'Europe/Helsinki', decorationType: 'sparkles', animationEnabled: true, respectReducedMotion: true, announcementTitle: { sv: '', en: '' }, announcementText: { sv: '', en: '' }, heroTitle: { sv: '', en: '' }, heroText: { sv: '', en: '' }, showOnHomepage: true, showAnnouncementBar: true, showHeroDecoration: true, showNavigationBadge: false, highlightedNavItems: [], targetPages: ['home'], createdAt: new Date('2025-01-01T00:00:00Z'), updatedAt: new Date('2025-01-01T00:00:00Z') };
const theme = (patch: Partial<WebsiteTheme>) => ({ ...base, ...patch });
describe('active theme resolver', () => {
  it('ignores draft inactive archived and disabled themes', () => { expect(resolveActiveTheme([theme({ status: 'draft' }), theme({ status: 'inactive' }), theme({ status: 'archived' }), theme({ enabled: false })], new Date('2026-01-10T12:00:00Z')).theme).toBeNull(); });
  it('manual override wins over schedule and priority candidates', () => { const manual = theme({ id: 'manual', key: 'manual', manualOverride: true, automaticActivation: false, priority: 1 }); const scheduled = theme({ id: 'scheduled', key: 'scheduled', priority: 99 }); expect(resolveActiveTheme([scheduled, manual], new Date('2026-01-10T12:00:00Z')).theme?.key).toBe('scheduled'); const manualHigh = theme({ id: 'manual-high', key: 'manual-high', manualOverride: true, automaticActivation: false, priority: 100 }); expect(resolveActiveTheme([scheduled, manualHigh], new Date('2026-01-10T12:00:00Z')).reason).toBe('manual_override'); });
  it('uses highest priority and newest update as tie breaker', () => { const older = theme({ key: 'older', priority: 10, updatedAt: new Date('2026-01-01T00:00:00Z') }); const newer = theme({ key: 'newer', priority: 10, updatedAt: new Date('2026-01-02T00:00:00Z') }); expect(resolveActiveTheme([older, newer], new Date('2026-01-10T12:00:00Z')).theme?.key).toBe('newer'); });
  it('activates recurring yearly Gulis theme date range', () => { const gulis = theme({ key: 'gulis-theme', recurringYearly: true, startMonthDay: '08-20', endMonthDay: '09-30' }); expect(isThemeActive(gulis, new Date('2026-08-20T09:00:00Z'))).toBe(true); expect(isThemeActive(gulis, new Date('2026-10-01T09:00:00Z'))).toBe(false); });
});
