import { Types } from 'mongoose';
import { AppError } from '../../http/errors';
import { localizedValue } from '../../localization/languages';
import { WebsiteThemeModel } from '../models/WebsiteTheme';
import { ActiveThemeResolution, PublicWebsiteTheme, ThemeLocale, ThemeService, WebsiteTheme } from '../types';
import { resolveActiveTheme } from './activeThemeResolver';

type ThemeDoc = WebsiteTheme & { _id: Types.ObjectId; toObject: () => Record<string, unknown> };
function clean(value?: string) { return value && value.trim() ? value.trim() : undefined; }
export class MongooseThemeService implements ThemeService {
  private id(value: string) { if (!Types.ObjectId.isValid(value)) throw new AppError(400, 'INVALID_ID', 'Identifier is invalid'); return value; }
  private duplicate(error: unknown) { if ((error as { code?: number }).code === 11000) throw new AppError(409, 'THEME_KEY_IN_USE', 'Theme key is already in use'); }
  private toAdmin(doc: ThemeDoc): WebsiteTheme { return { ...doc.toObject(), id: doc._id.toString() } as unknown as WebsiteTheme; }
  private toPublic(theme: WebsiteTheme, locale: ThemeLocale, reason = 'preview'): PublicWebsiteTheme {
    return { id: theme.id, key: theme.key, name: localizedValue(theme.name, locale), type: theme.type, decorationType: theme.decorationType, accentColor: theme.accentColor, secondaryAccentColor: theme.secondaryAccentColor, bannerImageUrl: theme.bannerImageUrl, mascotImageUrl: theme.mascotImageUrl, decorativeAssetUrl: theme.decorativeAssetUrl, backgroundPatternUrl: theme.backgroundPatternUrl, logoVariantUrl: theme.logoVariantUrl, chatbotMascotAssetUrl: theme.chatbotMascotAssetUrl, animationEnabled: theme.animationEnabled, respectReducedMotion: theme.respectReducedMotion, announcementTitle: localizedValue(theme.announcementTitle, locale), announcementText: localizedValue(theme.announcementText, locale), heroTitle: localizedValue(theme.heroTitle, locale), heroText: localizedValue(theme.heroText, locale), ctaPrimaryLabel: theme.ctaPrimaryLabel ? localizedValue(theme.ctaPrimaryLabel, locale) : undefined, ctaPrimaryUrl: theme.ctaPrimaryUrl || theme.externalCtaUrl, ctaSecondaryLabel: theme.ctaSecondaryLabel ? localizedValue(theme.ctaSecondaryLabel, locale) : undefined, ctaSecondaryUrl: theme.ctaSecondaryUrl, homepageCardTitle: theme.homepageCardTitle ? localizedValue(theme.homepageCardTitle, locale) : undefined, homepageCardText: theme.homepageCardText ? localizedValue(theme.homepageCardText, locale) : undefined, homepageCardUrl: theme.homepageCardUrl, showOnHomepage: theme.showOnHomepage, showAnnouncementBar: theme.showAnnouncementBar, showHeroDecoration: theme.showHeroDecoration, showNavigationBadge: theme.showNavigationBadge, highlightedNavItems: theme.highlightedNavItems || [], targetPages: theme.targetPages || ['home'], campaignType: theme.campaignType, activeReason: reason };
  }
  private normalize<T extends Omit<WebsiteTheme, 'id' | 'createdAt' | 'updatedAt'>>(input: T): T { return { ...input, accentColor: clean(input.accentColor), secondaryAccentColor: clean(input.secondaryAccentColor), bannerImageUrl: clean(input.bannerImageUrl), mascotImageUrl: clean(input.mascotImageUrl), decorativeAssetUrl: clean(input.decorativeAssetUrl), backgroundPatternUrl: clean(input.backgroundPatternUrl), logoVariantUrl: clean(input.logoVariantUrl), chatbotMascotAssetUrl: clean(input.chatbotMascotAssetUrl), ctaPrimaryUrl: clean(input.ctaPrimaryUrl), ctaSecondaryUrl: clean(input.ctaSecondaryUrl), homepageCardUrl: clean(input.homepageCardUrl), externalCtaUrl: clean(input.externalCtaUrl), relatedRecruitmentCampaignId: clean(input.relatedRecruitmentCampaignId) } as T; }
  async listAdmin(): Promise<WebsiteTheme[]> { const docs = await WebsiteThemeModel.find({}).sort({ status: 1, priority: -1, updatedAt: -1 }); return docs.map((doc: ThemeDoc) => this.toAdmin(doc)); }
  async create(input: Omit<WebsiteTheme, 'id' | 'createdAt' | 'updatedAt'>): Promise<WebsiteTheme> { try { const doc = await WebsiteThemeModel.create(this.normalize(input)); return this.toAdmin(doc as ThemeDoc); } catch (error) { this.duplicate(error); throw error; } }
  async update(id: string, input: Omit<WebsiteTheme, 'id' | 'createdAt' | 'updatedAt'>): Promise<WebsiteTheme> { try { const doc = await WebsiteThemeModel.findByIdAndUpdate(this.id(id), this.normalize(input), { new: true, runValidators: true }); if (!doc) throw new AppError(404, 'THEME_NOT_FOUND', 'Theme was not found'); return this.toAdmin(doc as ThemeDoc); } catch (error) { this.duplicate(error); throw error; } }
  async archive(id: string): Promise<void> { await WebsiteThemeModel.findByIdAndUpdate(this.id(id), { status: 'archived', enabled: false, manualOverride: false }); }
  async activeResolution(now = new Date()): Promise<ActiveThemeResolution> { return resolveActiveTheme(await this.listAdmin(), now); }
  async getPublicActive(locale: ThemeLocale, now = new Date()): Promise<PublicWebsiteTheme | null> { const resolution = await this.activeResolution(now); return resolution.theme ? this.toPublic(resolution.theme, locale, resolution.reason) : null; }
  async preview(id: string, locale: ThemeLocale): Promise<PublicWebsiteTheme> { const doc = await WebsiteThemeModel.findById(this.id(id)); if (!doc) throw new AppError(404, 'THEME_NOT_FOUND', 'Theme was not found'); return this.toPublic(this.toAdmin(doc as ThemeDoc), locale); }
}
