import { Router } from 'express';
import { z } from 'zod';
import { Env } from '../../env';
import { AppError } from '../../http/errors';
import { createAuthMiddleware, AuthenticatedRequest } from '../../identity/middleware/auth';
import { IdentityService } from '../../identity/types';
import { GovernanceService } from '../types';
import { governanceDocumentInputSchema, governanceDocumentQuerySchema, governanceSettingsInputSchema, idParamsSchema } from '../validation/governanceSchemas';
function parse<T extends z.ZodTypeAny>(schema: T, value: unknown): z.infer<T> { const result = schema.safeParse(value); if (!result.success) throw new AppError(400, 'VALIDATION_ERROR', 'Request validation failed', result.error.flatten()); return result.data; }
const actor = (request: AuthenticatedRequest) => request.principal?.userId;
export function createAdminGovernanceRouter(service: GovernanceService, identityService: IdentityService, env: Env) { const router = Router(); const { requireAuth, requirePermission } = createAuthMiddleware(identityService, env); router.use(requireAuth); router.get('/documents', requirePermission('governance.read'), async (request, response) => response.json({ data: { documents: await service.listDocuments(parse(governanceDocumentQuerySchema, request.query)) } })); router.post('/documents', requirePermission('governance.write'), async (request: AuthenticatedRequest, response) => response.status(201).json({ data: { document: await service.createDocument({ ...parse(governanceDocumentInputSchema, request.body), createdBy: actor(request), updatedBy: actor(request) } as never) } })); router.put('/documents/:id', requirePermission('governance.write'), async (request: AuthenticatedRequest, response) => response.json({ data: { document: await service.updateDocument(parse(idParamsSchema, request.params).id, { ...parse(governanceDocumentInputSchema, request.body), updatedBy: actor(request) } as never) } })); router.post('/documents/:id/publish', requirePermission('governance.write'), async (request: AuthenticatedRequest, response) => response.json({ data: { document: await service.publishDocument(parse(idParamsSchema, request.params).id, actor(request)) } })); router.post('/documents/:id/unpublish', requirePermission('governance.write'), async (request: AuthenticatedRequest, response) => response.json({ data: { document: await service.unpublishDocument(parse(idParamsSchema, request.params).id, actor(request)) } })); router.delete('/documents/:id', requirePermission('governance.write'), async (request: AuthenticatedRequest, response) => { await service.archiveDocument(parse(idParamsSchema, request.params).id, actor(request)); response.status(204).send(); }); router.get('/settings', requirePermission('governance.read'), async (_request, response) => response.json({ data: { settings: await service.getSettings() } })); router.put('/settings', requirePermission('governance.write'), async (request, response) => response.json({ data: { settings: await service.updateSettings(parse(governanceSettingsInputSchema, request.body) as never) } })); return router; }
