import request from 'supertest';
import { createApp } from '../../app';
import { Env } from '../../env';
import { issueTokens } from '../../identity/security/tokens';
import { AuthPrincipal, IdentityService } from '../../identity/types';
import { GovernanceDocument, GovernanceService } from '../types';
const env = { NODE_ENV: 'test', PORT: 3000, MONGO_URI: 'mongodb://localhost:27017/asken-test', JWT_ACCESS_SECRET: 'access-secret-with-at-least-32-characters', JWT_REFRESH_SECRET: 'refresh-secret-with-at-least-32-characters', ACCESS_TOKEN_TTL_SECONDS: 900, REFRESH_TOKEN_TTL_DAYS: 7, BCRYPT_ROUNDS: 10, COOKIE_SECURE: false, FRONTEND_URL: 'http://localhost:5173', ADMIN_URL: 'http://localhost:5174', SMTP_HOST: 'localhost', SMTP_AUTH: false, SMTP_SECURE: false, SMTP_PORT: 1025, SMTP_USER: 'test@example.com', SMTP_PASS: 'password', SUPER_ADMIN_NAME: 'Super Admin' } satisfies Env;
const principal: AuthPrincipal = { userId: '507f1f77bcf86cd799439011', email: 'admin@example.com', name: 'Admin', roles: ['super_admin'], permissions: ['governance.read', 'governance.write'] };
const doc: GovernanceDocument = { id: '507f1f77bcf86cd799439071', title: { sv: 'Fullmäktige protokoll', en: 'Student Council minutes' }, slug: 'fullmaktige-protokoll', description: { sv: 'Offentligt protokoll', en: 'Public minutes' }, documentType: 'minutes', governanceBody: 'fullmaktige', meetingDate: new Date('2026-05-01T15:00:00Z'), documentDate: new Date('2026-05-02T00:00:00Z'), year: 2026, language: 'sv', fileUrl: 'https://example.com/minutes.pdf', isPublic: true, isPublished: true, displayOrder: 1, tags: { sv: 'fullmäktige', en: 'student council' }, createdAt: new Date(), updatedAt: new Date() };
function identity(current: AuthPrincipal = principal): IdentityService { return { login: jest.fn(async () => ({ principal: current, ...issueTokens(current.userId, '507f191e810c19729de860ea', env) })), refresh: jest.fn(), logout: jest.fn(), changePassword: jest.fn(), getPrincipal: jest.fn(async () => current), listUsers: jest.fn(), createUser: jest.fn(), updateUser: jest.fn(), listRoles: jest.fn(), createRole: jest.fn(), updateRolePermissions: jest.fn(), listPermissions: jest.fn() } as unknown as IdentityService; }
function service(): GovernanceService { return { overview: jest.fn(async () => ({ settings: { intro: 'Intro', documentPolicyText: 'Policy', visible: true }, latestDocuments: [], sections: [] })), listPublicDocuments: jest.fn(async (filters) => filters.documentType === 'agenda' ? [] : [{ ...doc, title: doc.title.sv, description: doc.description.sv, tags: doc.tags.sv } as never]), getPublicDocument: jest.fn(async () => ({ ...doc, title: doc.title.sv, description: doc.description.sv, tags: doc.tags.sv } as never)), fullmaktige: jest.fn(async () => ({ meetingNotices: [], agendas: [], minutes: [{ ...doc, title: doc.title.sv, description: doc.description.sv, tags: doc.tags.sv } as never] })), listDocuments: jest.fn(async () => [doc]), createDocument: jest.fn(async (input) => ({ ...doc, ...input })), updateDocument: jest.fn(async (_id, input) => ({ ...doc, ...input })), publishDocument: jest.fn(async () => ({ ...doc, isPublished: true, isPublic: true })), unpublishDocument: jest.fn(async () => ({ ...doc, isPublished: false })), archiveDocument: jest.fn(async () => undefined), getSettings: jest.fn(async () => ({ id: 'settings', intro: { sv: 'Intro', en: 'Intro' }, documentPolicyText: { sv: 'Policy', en: 'Policy' }, visible: true })), updateSettings: jest.fn(async (input) => ({ id: 'settings', ...input })) } as unknown as GovernanceService; }
function app(current: AuthPrincipal = principal, governanceService = service()) { return createApp({ env, identityService: identity(current), cmsService: {} as never, newsService: {} as never, eventService: {} as never, governanceService }); }
async function login(application: ReturnType<typeof app>) { return request(application).post('/api/v1/auth/login').send({ email: 'admin@example.com', password: 'Password1!' }); }
describe('governance routes', () => {
  it('serves public endpoints and forwards filters', async () => { const governanceService = service(); const application = app(principal, governanceService); expect((await request(application).get('/api/v1/governance')).status).toBe(200); expect((await request(application).get('/api/v1/governance/documents?documentType=agenda&year=2026')).body.data.documents).toEqual([]); expect(governanceService.listPublicDocuments).toHaveBeenCalledWith(expect.objectContaining({ documentType: 'agenda', year: 2026 }), 'sv'); expect((await request(application).get('/api/v1/governance/documents/fullmaktige-protokoll')).body.data.document.title).toBe('Fullmäktige protokoll'); expect((await request(application).get('/api/v1/governance/fullmaktige?year=2026')).body.data.minutes).toHaveLength(1); });
  it('protects admin endpoints and requires governance.write for publishing', async () => { const application = app(); expect((await request(application).get('/api/v1/admin/governance/documents')).status).toBe(401); const session = await login(application); expect((await request(application).get('/api/v1/admin/governance/documents').set('Cookie', session.headers['set-cookie'])).status).toBe(200); const readOnly = app({ ...principal, permissions: ['governance.read'] }); const readOnlySession = await login(readOnly); expect((await request(readOnly).post(`/api/v1/admin/governance/documents/${doc.id}/publish`).set('Cookie', readOnlySession.headers['set-cookie'])).status).toBe(403); });
});
