import { SupportedLanguage } from './languages'

type AdminLanguageCode = Extract<SupportedLanguage, 'sv' | 'en'>

export const adminLanguages: AdminLanguageCode[] = ['sv', 'en']
export const adminTranslations = {
  sv: {
    language: { label: 'Adminspråk', sv: 'Svenska', en: 'English' },
    nav: { overview: 'Översikt', users: 'Användare', roles: 'Roller', content: 'Innehåll', news: 'Nyheter', events: 'Evenemang', corActivities: 'Cor-aktiviteter', collaborations: 'Samarbeten', booking: 'Bokning', organization: 'Organisation', representatives: 'Studeranderepresentanter', governance: 'Styrning', settings: 'Inställningar' },
    common: { loadingSession: 'Laddar session...', workspace: 'Arbetsyta', accountSecurity: 'Kontosäkerhet', signOut: 'Logga ut', secureAdministration: 'Säker administration', askAdministration: 'ASK-administration', save: 'Spara', cancel: 'Avbryt', create: 'Skapa', archive: 'Arkivera', edit: 'Redigera', delete: 'Radera', publish: 'Publicera', unpublish: 'Avpublicera', restore: 'Återställ', search: 'Sök', filter: 'Filtrera', open: 'Öppna', all: 'Alla', active: 'Aktiv', closed: 'Stängd', comingSoon: 'Kommer snart', inactive: 'Inaktiv', archived: 'Arkiverad', published: 'Publicerad', unpublished: 'Opublicerad', draft: 'Utkast', approved: 'Godkänd', rejected: 'Avvisad', waiting: 'Väntar', loading: 'Laddar', noResults: 'Inga resultat', private: 'Privat', public: 'Publik', visible: 'Synlig', hidden: 'Dold', title: 'Titel', description: 'Beskrivning', status: 'Status', action: 'Åtgärd', actions: 'Åtgärder', name: 'Namn', type: 'Typ', date: 'Datum', year: 'År', settings: 'Inställningar', documents: 'Dokument', people: 'Personer', bodies: 'Organ', calls: 'Utlysningar', overview: 'Översikt', svenska: 'Svenska', english: 'English', suomi: 'Suomi' },
    login: { eyebrow: 'Välkommen tillbaka', title: 'Logga in till ASK', intro: 'Använd ditt administrationskonto för att fortsätta.', email: 'E-post', password: 'Lösenord', submit: 'Logga in', submitting: 'Loggar in...', error: 'Det gick inte att logga in', heroEyebrow: 'Säker administration', heroTitle: 'En arbetsyta för ASK:s verksamhet.', heroBody: 'Hantera personer, innehåll, evenemang, bokningar och styrning i en behörighetsstyrd plattform.', protected: 'Skyddas av säkra sessioner och rollbaserad åtkomst.' },
    dashboard: { title: 'Välkommen tillbaka', modules: 'Dina moduler', moduleHelp: 'Synliga moduler baseras på dina behörigheter.', available: 'tillgängliga', intro: 'Hantera ASK:s tjänster från en säker, behörighetsstyrd arbetsyta.' },
    organization: { eyebrow: 'Organisation', title: 'Organisation', intro: 'Endast offentlig organisationsinformation. Styrelsemöten, röster, agendor, uppgifter och interna protokoll ingår inte.', tabs: { overview: 'Översikt', people: 'Personer', badges: 'Rollmärken', committees: 'Kommittéer', council: 'Fullmäktige', elders: 'Äldres Råd', recruitment: 'Rekrytering', alumni: 'Alumner' }, boardShortcut: 'Redigera styrelsemedlemmar', allTypes: 'Alla typer', createPerson: 'Skapa person', newPerson: 'Ny person' },
    booking: { eyebrow: 'Bokning av Cor-huset', title: 'Bokningsdashboard', intro: 'Offerter, godkännanden, avtal, underskrifter, resurser och aktivitet.', tabs: { list: 'Lista', calendar: 'Kalender', resources: 'Resurser', settings: 'Inställningar' }, resource: 'Resurs', reference: 'Referens', booking: 'Bokning', time: 'Tid', price: 'Pris', noBookings: 'Inga bokningar matchar filtren.', pendingApprovals: 'Väntar på godkännande', waitingForSignature: 'Väntar på underskrift', quoteRequests: 'Offertförfrågningar', upcomingThisWeek: 'Kommande denna vecka', completedThisMonth: 'Slutförda denna månad' },
    governance: { eyebrow: 'Offentlig styrning', title: 'Styrning', intro: 'Endast offentliga Fullmäktige- och styrdokument. Styrelseagendor, styrelseprotokoll, interna anteckningar, privata dokument och konfidentiellt material ingår inte.', tabs: { documents: 'Dokument', fullmaktige: 'Fullmäktige', settings: 'Inställningar' }, allTypes: 'Alla typer', allBodies: 'Alla organ', newDocument: 'Nytt dokument', editDocument: 'Redigera dokument', saveDocument: 'Spara dokument', saveSettings: 'Spara inställningar' },
    collaborations: { eyebrow: 'Samarbeten', title: 'Samarbeten', intro: 'Hantera ASK:s specialföreningar, studentnationer, partner, sponsorer och andra samarbeten.', tabs: { overview: 'Översikt', collaborations: 'Samarbeten', settings: 'Inställningar' }, allTypes: 'Alla typer', allStatuses: 'Alla statusar', newCollaboration: 'Nytt samarbete', editCollaboration: 'Redigera samarbete', saveCollaboration: 'Spara samarbete', saveSettings: 'Spara inställningar', featured: 'Utvald', officeAtCor: 'Kontor i Cor-huset', officeHours: 'Öppettider', internalNotes: 'Interna anteckningar', relationshipOwner: 'Ansvarig relation', contactPerson: 'Kontaktperson', websiteUrl: 'Webbplats', logoUrl: 'Logo-URL', logoAltText: 'Alt-text för logo', shortDescription: 'Kort beskrivning', tags: 'Taggar', displayOrder: 'Visningsordning', validFrom: 'Giltig från', validUntil: 'Giltig till', contactEmail: 'Kontakt e-post', location: 'Plats', socialLinks: 'Sociala länkar', visibleOnly: 'Endast synliga', featuredOnly: 'Endast utvalda', settingsIntro: 'Intro', types: { arcada_association: 'Specialförening', student_nation: 'Studentnation', sponsor: 'Sponsor', company: 'Företag', university: 'Universitet', strategic_partner: 'Partner', student_organization: 'Organisation', other: 'Annat' } },
    representatives: { eyebrow: 'Organisation', title: 'Studeranderepresentanter', intro: 'Information om förtroendeuppdrag i Arcadas organ. Modulen publicerar och administrerar information; val och beslut sker enligt ASK:s stadgar och reglemente.', tabs: { bodies: 'Organ', people: 'Representanter', calls: 'Utlysningar' }, appointedBy: 'Utses av', mandate: 'Mandat', visibility: 'Synlighet', term: 'Mandatperiod', newBody: 'Nytt organ', editBody: 'Redigera organ', newRepresentative: 'Ny representant', editRepresentative: 'Redigera representant', newCall: 'Ny utlysning', editCall: 'Redigera utlysning' },
    contentFields: { svTitle: 'Titel på svenska', enTitle: 'Title in English', svLabel: 'svenska', enLabel: 'English' }
  },
  en: {
    language: { label: 'Admin language', sv: 'Svenska', en: 'English' },
    nav: { overview: 'Overview', users: 'Users', roles: 'Roles', content: 'Content', news: 'News', events: 'Events', corActivities: 'Cor Activities', collaborations: 'Collaborations', booking: 'Booking', organization: 'Organization', representatives: 'Student Representatives', governance: 'Governance', settings: 'Settings' },
    common: { loadingSession: 'Loading session...', workspace: 'Workspace', accountSecurity: 'Account security', signOut: 'Sign out', secureAdministration: 'Secure administration', askAdministration: 'ASK Administration', save: 'Save', cancel: 'Cancel', create: 'Create', archive: 'Archive', edit: 'Edit', delete: 'Delete', publish: 'Publish', unpublish: 'Unpublish', restore: 'Restore', search: 'Search', filter: 'Filter', open: 'Open', all: 'All', active: 'Active', closed: 'Closed', comingSoon: 'Coming soon', inactive: 'Inactive', archived: 'Archived', published: 'Published', unpublished: 'Unpublished', draft: 'Draft', approved: 'Approved', rejected: 'Rejected', waiting: 'Waiting', loading: 'Loading', noResults: 'No results', private: 'Private', public: 'Public', visible: 'Visible', hidden: 'Hidden', title: 'Title', description: 'Description', status: 'Status', action: 'Action', actions: 'Actions', name: 'Name', type: 'Type', date: 'Date', year: 'Year', settings: 'Settings', documents: 'Documents', people: 'People', bodies: 'Bodies', calls: 'Calls', overview: 'Overview', svenska: 'Svenska', english: 'English', suomi: 'Suomi' },
    login: { eyebrow: 'Welcome back', title: 'Sign in to ASK', intro: 'Use your administration account to continue.', email: 'Email', password: 'Password', submit: 'Sign in', submitting: 'Signing in...', error: 'Unable to sign in', heroEyebrow: 'Secure administration', heroTitle: 'One workspace for ASK operations.', heroBody: 'Manage people, content, events, bookings, and governance through a permission-aware platform.', protected: 'Protected by secure sessions and role-based access.' },
    dashboard: { title: 'Welcome back', modules: 'Your modules', moduleHelp: 'Visible modules are based on your assigned permissions.', available: 'available', intro: 'Manage ASK services from one secure, permission-aware workspace.' },
    organization: { eyebrow: 'Organization', title: 'Organization', intro: 'Public organization information only. Board meetings, votes, agendas, tasks and internal protocols are excluded.', tabs: { overview: 'Overview', people: 'People', badges: 'Role badges', committees: 'Committees', council: 'Student Council', elders: 'Elders’ Council', recruitment: 'Recruitment', alumni: 'Alumni' }, boardShortcut: 'Edit board members', allTypes: 'All types', createPerson: 'Create person', newPerson: 'New person' },
    booking: { eyebrow: 'Cor House Booking', title: 'Booking dashboard', intro: 'Quotes, approvals, contracts, signatures, resources and activity.', tabs: { list: 'List', calendar: 'Calendar', resources: 'Resources', settings: 'Settings' }, resource: 'Resource', reference: 'Reference', booking: 'Booking', time: 'Time', price: 'Price', noBookings: 'No bookings match the filters.', pendingApprovals: 'Pending approvals', waitingForSignature: 'Waiting for signature', quoteRequests: 'Quote requests', upcomingThisWeek: 'Upcoming this week', completedThisMonth: 'Completed this month' },
    governance: { eyebrow: 'Public Governance', title: 'Governance', intro: 'Public Student Council and governance documents only. Board agendas, board protocols, internal notes, private documents, and confidential material are excluded.', tabs: { documents: 'Documents', fullmaktige: 'Student Council', settings: 'Settings' }, allTypes: 'All types', allBodies: 'All bodies', newDocument: 'New document', editDocument: 'Edit document', saveDocument: 'Save document', saveSettings: 'Save settings' },
    collaborations: { eyebrow: 'Collaborations', title: 'Collaborations', intro: 'Manage ASK associations, student nations, partners, sponsors, and other collaborations.', tabs: { overview: 'Overview', collaborations: 'Collaborations', settings: 'Settings' }, allTypes: 'All types', allStatuses: 'All statuses', newCollaboration: 'New collaboration', editCollaboration: 'Edit collaboration', saveCollaboration: 'Save collaboration', saveSettings: 'Save settings', featured: 'Featured', officeAtCor: 'Office at Cor', officeHours: 'Office hours', internalNotes: 'Internal notes', relationshipOwner: 'Relationship owner', contactPerson: 'Contact person', websiteUrl: 'Website', logoUrl: 'Logo URL', logoAltText: 'Logo alt text', shortDescription: 'Short description', tags: 'Tags', displayOrder: 'Display order', validFrom: 'Valid from', validUntil: 'Valid until', contactEmail: 'Contact email', location: 'Location', socialLinks: 'Social links', visibleOnly: 'Visible only', featuredOnly: 'Featured only', settingsIntro: 'Intro', types: { arcada_association: 'Arcada Association', student_nation: 'Student Nation', sponsor: 'Sponsor', company: 'Company', university: 'University', strategic_partner: 'Partner', student_organization: 'Organization', other: 'Other' } },
    representatives: { eyebrow: 'Organization', title: 'Student Representatives', intro: 'Information about representative roles in Arcada bodies. This module publishes and manages information; elections and decisions follow ASK’s statutes and regulations.', tabs: { bodies: 'Bodies', people: 'Representatives', calls: 'Calls' }, appointedBy: 'Appointed by', mandate: 'Term', visibility: 'Visibility', term: 'Term period', newBody: 'New body', editBody: 'Edit body', newRepresentative: 'New representative', editRepresentative: 'Edit representative', newCall: 'New call', editCall: 'Edit call' },
    contentFields: { svTitle: 'Swedish title', enTitle: 'English title', svLabel: 'Swedish', enLabel: 'English' }
  }
} as const

export type AdminLanguage = keyof typeof adminTranslations
export type AdminTranslationKey = keyof typeof adminTranslations.sv
export type AdminTranslations = (typeof adminTranslations)[AdminLanguage]
