import { Types } from 'mongoose'; import { CmsService } from '../../cms/types'; import { ContentModel } from '../../cms/models/Content'; import { slugify } from '../../cms/utils/slug'; import { AppError } from '../../http/errors'; import { recordAudit } from '../../identity/services/audit'; import { AuthPrincipal,RequestContext } from '../../identity/types'; import { EventModel } from '../models/Event'; import { EventCategoryModel } from '../models/EventCategory'; import { EventVersionModel } from '../models/EventVersion'; import { localizedObject, localizedValue, TranslationMetadata } from '../../localization/languages'; import { EventCategory,EventInput,EventLocale,EventQuery,EventService,ManagedEvent,PublicEvent } from '../types';
interface ED{_id:Types.ObjectId;contentId:Types.ObjectId;translations:EventInput['translations'];translationMeta?:Partial<Record<EventLocale,TranslationMetadata>>;imageUrl?:string;startAt:Date;endAt:Date;categoryId:Types.ObjectId;eventStatus:EventInput['eventStatus'];featured:boolean;kideAppUrl?:string;createdAt:Date;updatedAt:Date} interface CD{_id:Types.ObjectId;slug:string;status:'draft'|'published';version:number;publishedAt?:Date} interface CAT{_id:Types.ObjectId;slug:string;labels:{en:string;sv:string};createdAt:Date;updatedAt:Date}
export class MongooseEventService implements EventService{constructor(private cms:CmsService){}
 async listAdminEvents(){const events=await EventModel.find().sort({startAt:1}).lean() as unknown as ED[];const contents=await ContentModel.find({_id:{$in:events.map(e=>e.contentId)},contentType:'event'}).lean() as unknown as CD[];return this.managed(events,contents)}
 async getAdminEvent(id:string){this.id(id);const e=await EventModel.findById(id).lean() as unknown as ED|null;if(!e)throw new AppError(404,'EVENT_NOT_FOUND','Event was not found');const c=await ContentModel.findOne({_id:e.contentId,contentType:'event'}).lean() as unknown as CD|null;if(!c)throw new AppError(404,'EVENT_NOT_FOUND','Event was not found');return (await this.managed([e],[c]))[0]}
 async createEvent(input:EventInput,actor:AuthPrincipal,ctx:RequestContext){await this.category(input.categoryId);const c=await this.cms.createContent({contentType:'event',title:input.translations.sv.title,slug:input.slug,sections:[]},actor,ctx);try{const e=await EventModel.create({...input,contentId:c.id});await this.version(e.toObject() as unknown as ED,c.version,actor.userId);return this.getAdminEvent(e.id)}catch(error){await this.cms.deleteContent(c.id,actor,ctx);throw error}}
 async updateEvent(id:string,input:EventInput&{expectedVersion:number},actor:AuthPrincipal,ctx:RequestContext){this.id(id);await this.category(input.categoryId);const old=await EventModel.findById(id).lean() as unknown as ED|null;if(!old)throw new AppError(404,'EVENT_NOT_FOUND','Event was not found');const c=await this.cms.updateContent({contentId:old.contentId.toString(),contentType:'event',title:input.translations.sv.title,slug:input.slug,sections:[],expectedVersion:input.expectedVersion},actor,ctx);const e=await EventModel.findByIdAndUpdate(id,{$set:input},{new:true}).lean() as unknown as ED;await this.version(e,c.version,actor.userId);return this.getAdminEvent(id)}
 async deleteEvent(id:string,actor:AuthPrincipal,ctx:RequestContext){this.id(id);const e=await EventModel.findById(id).lean() as unknown as ED|null;if(!e)throw new AppError(404,'EVENT_NOT_FOUND','Event was not found');await this.cms.deleteContent(e.contentId.toString(),actor,ctx);await Promise.all([EventModel.deleteOne({_id:id}),EventVersionModel.deleteMany({eventId:id})])}
 async publishEvent(id:string,expectedVersion:number,actor:AuthPrincipal,ctx:RequestContext){const e=await EventModel.findById(id).lean() as unknown as ED|null;if(!e)throw new AppError(404,'EVENT_NOT_FOUND','Event was not found');const c=await this.cms.publishContent(e.contentId.toString(),expectedVersion,actor,ctx);await this.version(e,c.version,actor.userId);return this.getAdminEvent(id)}
 async setFeatured(id:string,featured:boolean,actor:AuthPrincipal,ctx:RequestContext){const e=await EventModel.findByIdAndUpdate(id,{$set:{featured}},{new:true});if(!e)throw new AppError(404,'EVENT_NOT_FOUND','Event was not found');await recordAudit({actorId:actor.userId,action:'events.featured_changed',targetType:'event',targetId:id,context:ctx,metadata:{featured}});return this.getAdminEvent(id)}
 async listPublicEvents(q:EventQuery){const f:Record<string,unknown>={};if(q.featured!==undefined)f.featured=q.featured;if(q.category){const cat=await EventCategoryModel.findOne({slug:q.category}).lean() as unknown as CAT|null;if(!cat)return{events:[],total:0,page:q.page,limit:q.limit};f.categoryId=cat._id}if(q.period==='upcoming')f.endAt={$gte:new Date()};if(q.period==='past')f.endAt={$lt:new Date()};if(q.from||q.to)f.startAt={...(q.from?{$gte:q.from}:{}),...(q.to?{$lte:q.to}:{})};if(q.search){const x=new RegExp(this.escape(q.search),'i');f.$or=[{[`translations.${q.locale}.title`]:x},{[`translations.${q.locale}.description`]:x},{[`translations.${q.locale}.location`]:x},{[`translations.${q.locale}.organizer`]:x}]}const es=await EventModel.find(f).sort({startAt:q.period==='past'?-1:1}).lean() as unknown as ED[];const cs=await ContentModel.find({_id:{$in:es.map(e=>e.contentId)},contentType:'event',status:'published',publishedAt:{$lte:new Date()}}).lean() as unknown as CD[];const allowed=new Set(cs.map(c=>c._id.toString()));const filtered=es.filter(e=>allowed.has(e.contentId.toString()));const total=filtered.length;const page=filtered.slice((q.page-1)*q.limit,q.page*q.limit);return{events:await this.public(page,cs,q.locale),total,page:q.page,limit:q.limit}}
 async getPublicEvent(slug:string,locale:EventLocale){const c=await ContentModel.findOne({contentType:'event',slug,status:'published',publishedAt:{$lte:new Date()}}).lean() as unknown as CD|null;if(!c)throw new AppError(404,'EVENT_NOT_FOUND','Event was not found');const e=await EventModel.findOne({contentId:c._id}).lean() as unknown as ED|null;if(!e)throw new AppError(404,'EVENT_NOT_FOUND','Event was not found');return(await this.public([e],[c],locale))[0]}
 async calendar(q:EventQuery){return(await this.listPublicEvents({...q,page:1,limit:100})).events}
 async listCategories(){return(await EventCategoryModel.find().sort({'labels.sv':1}).lean() as unknown as CAT[]).map(this.cat)}
 async createCategory(input:{slug?:string;labels:{en:string;sv:string}}){try{const c=await EventCategoryModel.create({slug:this.slug(input.slug||input.labels.sv),labels:input.labels});return this.cat(c.toObject() as unknown as CAT)}catch(e){this.dup(e);throw e}}
 async updateCategory(id:string,input:{slug?:string;labels:{en:string;sv:string}}){this.id(id);try{const c=await EventCategoryModel.findByIdAndUpdate(id,{$set:{slug:this.slug(input.slug||input.labels.sv),labels:input.labels}},{new:true}).lean() as unknown as CAT|null;if(!c)throw new AppError(404,'EVENT_CATEGORY_NOT_FOUND','Event category was not found');return this.cat(c)}catch(e){this.dup(e);throw e}}
 async deleteCategory(id:string){this.id(id);if(await EventModel.exists({categoryId:id}))throw new AppError(409,'EVENT_CATEGORY_IN_USE','Event category is assigned to events');const r=await EventCategoryModel.deleteOne({_id:id});if(!r.deletedCount)throw new AppError(404,'EVENT_CATEGORY_NOT_FOUND','Event category was not found')}
 private async managed(es:ED[],cs:CD[]):Promise<ManagedEvent[]>{const cm=new Map(cs.map(c=>[c._id.toString(),c]));const cats=new Map((await EventCategoryModel.find({_id:{$in:es.map(e=>e.categoryId)}}).lean() as unknown as CAT[]).map(c=>[c._id.toString(),this.cat(c)]));return es.flatMap(e=>{const c=cm.get(e.contentId.toString()),cat=cats.get(e.categoryId.toString());return c&&cat?[{...e,id:e._id.toString(),contentId:e.contentId.toString(),slug:c.slug,publicationStatus:c.status,temporalStatus:this.temporal(e),version:c.version,category:cat,publishedAt:c.publishedAt,translationMeta:e.translationMeta}]:[]})}
 private async public(es:ED[],cs:CD[],locale:EventLocale):Promise<PublicEvent[]>{const cm=new Map(cs.map(c=>[c._id.toString(),c]));const cats=new Map((await EventCategoryModel.find({_id:{$in:es.map(e=>e.categoryId)}}).lean() as unknown as CAT[]).map(c=>[c._id.toString(),c]));return es.map(e=>{const t=localizedObject(e.translations,locale)||e.translations.sv,cat=cats.get(e.categoryId.toString())!,c=cm.get(e.contentId.toString())!;return{id:e._id.toString(),slug:c.slug,...t,imageUrl:e.imageUrl,startAt:e.startAt,endAt:e.endAt,eventStatus:e.eventStatus,temporalStatus:this.temporal(e),category:{slug:cat.slug,label:localizedValue(cat.labels,locale)},featured:e.featured,kideAppUrl:e.kideAppUrl,locale}})}
 private temporal(e:ED):'upcoming'|'past'{return e.endAt.getTime()<Date.now()?'past':'upcoming'} private async category(id:string){this.id(id);if(!await EventCategoryModel.exists({_id:id}))throw new AppError(400,'INVALID_EVENT_CATEGORY','Event category does not exist')} private async version(e:ED,v:number,a:string){await EventVersionModel.create({eventId:e._id,contentId:e.contentId,version:v,snapshot:e,actorId:a})} private cat(c:CAT):EventCategory{return{id:c._id.toString(),slug:c.slug,labels:c.labels,createdAt:c.createdAt,updatedAt:c.updatedAt}} private slug(v:string){const s=slugify(v);if(!s)throw new AppError(400,'INVALID_SLUG','Slug is invalid');return s} private id(v:string){if(!Types.ObjectId.isValid(v))throw new AppError(400,'INVALID_ID','Identifier is invalid')} private dup(e:unknown){if((e as{code?:number}).code===11000)throw new AppError(409,'EVENT_CATEGORY_SLUG_IN_USE','Category slug is in use')} private escape(v:string){return v.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')}
}
