"use client";

import {useEffect,useState,type CSSProperties} from "react";
import {ArrowUpRight,Building2,Handshake,School,ShieldCheck} from "lucide-react";
import PublicShell from "@/components/public-shell";

type Partner={id:string;slug:string;name:string;type:"association"|"sponsor"|"company"|"partner"|"alumni";shortDescriptionSv:string;shortDescriptionEn:string;descriptionSv:string;descriptionEn:string;websiteUrl:string;logoUrl:string;brandColor:string;featured:boolean};
const copy={
 sv:{back:"Till ASK",switchLabel:"English",switchHref:"/collaborations",eyebrow:"ASK:s gemenskap",title:"Föreningar och samarbeten",lead:"Möt studentföreningarna vid Arcada och de organisationer som ASK samarbetar med. En organisation visas här endast när samarbetet är aktivt och godkänt för offentlig publicering.",associations:"Studentföreningar vid Arcada",associationsText:"Självständiga registrerade föreningar som samarbetar med ASK och skapar verksamhet för studerande inom sina utbildningsområden.",partners:"Samarbetspartner",partnersText:"Organisationer som ASK samarbetar med inom studentinflytande, högskolegemenskap, medlemskap eller evenemang.",sponsors:"Sponsorer",sponsorsText:"Formella sponsorer publiceras här efter att samarbetet har bekräftats av ASK.",emptySponsors:"ASK har ännu inte publicerat någon aktiv sponsor.",visit:"Läs mer"},
 en:{back:"Back to ASK",switchLabel:"Svenska",switchHref:"/samarbeten",eyebrow:"The ASK community",title:"Associations and collaborations",lead:"Meet Arcada’s student associations and the organisations ASK works with. An organisation appears here only when the relationship is active and approved for public display.",associations:"Student associations at Arcada",associationsText:"Independent registered associations that work with ASK and create activities for students in their fields of study.",partners:"Collaboration partners",partnersText:"Organisations ASK works with in student advocacy, the higher-education community, membership or events.",sponsors:"Sponsors",sponsorsText:"Formal sponsors are published here after ASK has confirmed the relationship.",emptySponsors:"ASK has not yet published an active sponsor.",visit:"Read more"}
};
export default function PartnerDirectory({lang}:{lang:"sv"|"en"}){
 const t=copy[lang],[items,setItems]=useState<Partner[]>([]),[loading,setLoading]=useState(true);
 useEffect(()=>{fetch("/api/public/collaborations").then(r=>r.json()).then(d=>setItems(d.items||[])).finally(()=>setLoading(false))},[]);
 const groups=[{types:["association"],title:t.associations,text:t.associationsText,icon:<School/>},{types:["partner","company","alumni"],title:t.partners,text:t.partnersText,icon:<Handshake/>},{types:["sponsor"],title:t.sponsors,text:t.sponsorsText,icon:<ShieldCheck/>}];
 return <PublicShell lang={lang} alternate={t.switchHref}><main className="partners-page"><section className="partners-hero"><span>{t.eyebrow}</span><h1>{t.title}</h1><p>{t.lead}</p></section><div className="partner-sections">{groups.map(group=>{const list=items.filter(item=>group.types.includes(item.type));return <section key={group.title}><div className="partner-section-title"><i>{group.icon}</i><div><h2>{group.title}</h2><p>{group.text}</p></div></div><div className="partner-grid">{loading?<div className="partner-empty">…</div>:list.length?list.map(item=><article className="partner-card-branded" style={{"--association-color":item.brandColor||"#A32F8E"} as CSSProperties} key={item.id}><div className="partner-mark">{item.logoUrl?<img src={item.logoUrl} alt={`${item.name} logo`}/>:<span>{item.name.split(/\s+/).map(x=>x[0]).join("").slice(0,3)}</span>}</div><div><small>{item.type}</small><h3>{item.name}</h3><p>{lang==="sv"?item.shortDescriptionSv:item.shortDescriptionEn}</p><a href={`/${lang==="sv"?"samarbeten":"collaborations"}/${item.slug}`}>{t.visit}<ArrowUpRight/></a></div></article>):<div className="partner-empty"><Building2/><span>{group.types.includes("sponsor")?t.emptySponsors:"—"}</span></div>}</div></section>})}</div></main></PublicShell>
}
