import { ArrowLeft, ExternalLink, LockKeyhole, Mail, MapPin, Phone } from "lucide-react";

const notices = {
  sv: {
    back:"Till Cor-huset", switchLabel:"English", switchHref:"/privacy", eyebrow:"Integritetsmeddelande · Cor-bokningar", title:"Så behandlar ASK dina bokningsuppgifter", lead:"Detta meddelande gäller personuppgifter som behandlas när du frågar om, bokar eller använder Cor-huset. Version 06.09.2026.",
    sections:[
      ["1. Personuppgiftsansvarig",<>Arcada studerandekår – ASK<br/>Majstadsgatan 11, 00560 Helsingfors<br/>E-post: <a href="mailto:info@asken.fi">info@asken.fi</a><br/>Telefon: <a href="tel:+358404890367">+358 40 489 0367</a></>],
      ["2. Uppgifter vi behandlar",<ul key="data"><li>Namn, organisation, e-postadress och telefonnummer.</li><li>Fakturamottagare och faktureringsadress.</li><li>Bokad tid, valda utrymmen, bokningens ändamål och avtalsspråk.</li><li>Bokningsstatus, pris, avtal, betalnings- och faktureringsuppgifter.</li><li>Vid behov uppgifter om tillträde, städning, skador, incidenter och reklamationer.</li><li>Tekniska säkerhetsuppgifter som bokningsreferens, privat statuskod och tidsstämplar.</li></ul>],
      ["3. Ändamål och rättslig grund",<ul key="basis"><li>Hantera en bokningsförfrågan och fullgöra bokningsavtalet: åtgärder före avtal och avtal enligt GDPR artikel 6.1 b.</li><li>Hantera en organisations kontaktperson, skydda Cor-huset och utreda skador, städning eller tvister: ASK:s berättigade intresse enligt artikel 6.1 f.</li><li>Fakturering, bokföring och myndighetskrav: rättslig förpliktelse enligt artikel 6.1 c.</li></ul>],
      ["4. Samtycke",<p key="consent">Bokningsuppgifter som är nödvändiga för förfrågan eller avtalet behandlas inte med samtycke som rättslig grund. Kryssrutan i formuläret bekräftar att du har fått detta meddelande. Separat, frivilligt samtycke ska begäras om ASK senare använder uppgifter för exempelvis marknadsföring eller icke-nödvändig analys.</p>],
      ["5. Mottagare och offentlig kalender",<p key="recipients">Behöriga ASK-administratörer behandlar uppgifterna. Nödvändiga uppgifter kan lämnas till ASK:s leverantörer av webbhotell och IT, e-post, bokföring och fakturering samt den externa signeringstjänst som används. Uppgifter kan lämnas till myndigheter eller försäkringsbolag när lag eller ett rättsligt anspråk kräver det. Den offentliga Cor-kalendern visar bokad tid och utrymme. En verifierad föreningsbokning kan visa föreningens namn och färg; övriga bokningar visas som ”Privat bokning”. Namn, kontaktuppgifter, faktureringsuppgifter, ändamål och privata statuslänkar publiceras inte.</p>],
      ["6. Överföringar utanför EES",<p key="transfer">Om en tjänsteleverantör behandlar uppgifter utanför Europeiska ekonomiska samarbetsområdet använder ASK en laglig överföringsmekanism, såsom ett adekvansbeslut eller EU:s standardavtalsklausuler, och kompletterande skydd där det behövs.</p>],
      ["7. Lagring",<ul key="retention"><li>Förfrågningar som inte leder till bokning: normalt högst 12 månader efter avslutad behandling.</li><li>Operativa boknings-, tillträdes-, städnings- och skadeuppgifter: normalt högst 24 månader efter bokningen, eller längre om ett krav eller en tvist pågår.</li><li>Avtal, fakturor och bokföringsunderlag: så länge finländsk bokförings- och skattelagstiftning kräver, normalt minst sex år efter räkenskapsperiodens slut.</li></ul>],
      ["8. Dina rättigheter",<p key="rights">Du kan beroende på situationen begära tillgång, rättelse, radering, begränsning eller dataportabilitet samt invända mot behandling som grundar sig på berättigat intresse. Kontakta <a href="mailto:info@asken.fi">info@asken.fi</a>. Du har också rätt att lämna in ett klagomål till <a href="https://tietosuoja.fi/sv/framsida" target="_blank" rel="noreferrer">Dataombudsmannens byrå <ExternalLink/></a>.</p>],
      ["9. Säkerhet och automatiska beslut",<p key="security">Åtkomsten begränsas till behöriga användare. Privata statuslänkar och dörrkoder får inte delas offentligt. ASK fattar inga beslut med rättslig eller motsvarande betydande verkan enbart genom automatiserad behandling. Skriv inte känsliga personuppgifter i fritextfältet.</p>],
      ["10. Ändringar",<p key="changes">Den version som gällde när förfrågan skickades registreras med bokningen. Väsentliga ändringar publiceras på denna sida.</p>],
    ]
  },
  en: {
    back:"Back to Cor House", switchLabel:"Svenska", switchHref:"/integritet", eyebrow:"Privacy notice · Cor bookings", title:"How ASK processes your booking data", lead:"This notice covers personal data processed when you enquire about, book or use Cor House. Version 6 September 2026.",
    sections:[
      ["1. Data controller",<>Arcada Student Union – ASK<br/>Majstadsgatan 11, 00560 Helsinki, Finland<br/>Email: <a href="mailto:info@asken.fi">info@asken.fi</a><br/>Telephone: <a href="tel:+358404890367">+358 40 489 0367</a></>],
      ["2. Data we process",<ul key="data"><li>Name, organisation, email address and telephone number.</li><li>Invoice recipient and billing address.</li><li>Booking time, selected spaces, purpose and contract language.</li><li>Booking status, price, contract, payment and invoicing details.</li><li>Where needed, access, cleaning, damage, incident and complaint records.</li><li>Technical security data such as the booking reference, private status token and timestamps.</li></ul>],
      ["3. Purposes and legal bases",<ul key="basis"><li>Handling a request and performing the booking agreement: steps before a contract and contract under GDPR Article 6(1)(b).</li><li>Managing an organisation’s contact person, protecting Cor House and handling damage, cleaning or disputes: ASK’s legitimate interests under Article 6(1)(f).</li><li>Invoicing, accounting and authority requirements: legal obligation under Article 6(1)(c).</li></ul>],
      ["4. Consent",<p key="consent">Booking data needed for the request or agreement is not processed on the legal basis of consent. The form checkbox confirms that you received this notice. ASK must request separate, voluntary consent before using the data for purposes such as marketing or non-essential analytics.</p>],
      ["5. Recipients and public calendar",<p key="recipients">Authorised ASK administrators process the data. Necessary data may be provided to ASK’s website hosting and IT, email, accounting and invoicing providers and the external signing service used for the contract. Data may be provided to authorities or insurers when required by law or a legal claim. The public Cor calendar shows the booked time and space. A verified association booking may show the association name and colour; other bookings appear as “Private booking”. Names, contact details, billing details, purpose and private status links are not published.</p>],
      ["6. Transfers outside the EEA",<p key="transfer">If a service provider processes data outside the European Economic Area, ASK uses a lawful transfer mechanism such as an adequacy decision or the European Commission’s standard contractual clauses, with supplementary safeguards where necessary.</p>],
      ["7. Retention",<ul key="retention"><li>Requests that do not become bookings: normally no longer than 12 months after final handling.</li><li>Operational booking, access, cleaning and damage records: normally no longer than 24 months after the booking, or longer while a claim or dispute is active.</li><li>Contracts, invoices and accounting material: for the period required under Finnish accounting and tax law, normally at least six years after the relevant financial period ends.</li></ul>],
      ["8. Your rights",<p key="rights">Depending on the circumstances, you may request access, rectification, erasure, restriction or portability and object to processing based on legitimate interests. Contact <a href="mailto:info@asken.fi">info@asken.fi</a>. You may also complain to the <a href="https://tietosuoja.fi/en/home" target="_blank" rel="noreferrer">Office of the Data Protection Ombudsman <ExternalLink/></a>.</p>],
      ["9. Security and automated decisions",<p key="security">Access is limited to authorised users. Private status links and door codes must not be shared publicly. ASK does not make decisions producing legal or similarly significant effects solely through automated processing. Do not enter sensitive personal data in free-text fields.</p>],
      ["10. Changes",<p key="changes">The notice version in force when the request is submitted is recorded with the booking. Material changes will be published on this page.</p>],
    ]
  }
};

export default function PrivacyNotice({lang}:{lang:"sv"|"en"}){
  const t=notices[lang];
  return <main className="legal-page"><header><a href={lang==="sv"?"/cor-huset":"/cor"}><ArrowLeft/>{t.back}</a><img src="/ask-logo-white.png" alt="ASK"/><a href={t.switchHref}>{t.switchLabel}</a></header><article><span className="legal-eyebrow"><LockKeyhole/>{t.eyebrow}</span><h1>{t.title}</h1><p className="legal-lead">{t.lead}</p><aside><span><MapPin/>Majstadsgatan 11, 00560 Helsinki</span><span><Mail/>info@asken.fi</span><span><Phone/>+358 40 489 0367</span></aside>{t.sections.map(([heading,body])=><section key={heading as string}><h2>{heading}</h2>{body}</section>)}</article></main>
}
