"use client";

import { useEffect, useMemo, useState } from "react";
import { ArrowUpRight, CalendarDays, Download, FileText, Search, Send, UserRound } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select,SelectContent,SelectItem,SelectTrigger,SelectValue } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import type { PublicLanguage, PublicPageKind } from "@/lib/public-pages";

type Content={id:string;type:string;slug:string;titleSv:string;titleEn:string;summarySv:string;summaryEn:string;bodySv:string;bodyEn:string;startsAt:string|null;location:string;ctaUrl:string;imageUrl:string};
type Document={id:string;slug:string;category:string;titleSv:string;titleEn:string;descriptionSv:string;descriptionEn:string;fileUrl:string;meetingDate:string|null;language:string};

export function ContentCollection({lang,kind}:{lang:PublicLanguage;kind:"news"|"events"|"people"}){
  const[items,setItems]=useState<Content[]>([]),[query,setQuery]=useState("");
  useEffect(()=>{fetch("/api/content").then(r=>r.json()).then(d=>setItems((d.items||[]).filter((item:Content)=>item.type===(kind==="events"?"event":kind==="people"?"person":"news")))).catch(()=>setItems([]))},[kind]);
  const shown=useMemo(()=>items.filter(item=>`${item.titleSv} ${item.titleEn} ${item.summarySv} ${item.summaryEn}`.toLowerCase().includes(query.toLowerCase())),[items,query]);
  const title=(item:Content)=>lang==="sv"?item.titleSv:(item.titleEn||item.titleSv),summary=(item:Content)=>lang==="sv"?item.summarySv:(item.summaryEn||item.summarySv);
  return <section className="public-collection"><div className="collection-header-row"><div className="collection-tools"><Search/><Input value={query} onChange={e=>setQuery(e.target.value)} placeholder={lang==="sv"?"Sök…":"Search…"}/></div>{kind==="events"&&<a className="calendar-subscribe" href="/api/calendar.ics"><CalendarDays/>{lang==="sv"?"Prenumerera på kalender":"Subscribe to calendar"}</a>}</div><div className="archive-grid">{shown.length?shown.map(item=><article key={item.id}>{item.imageUrl&&<img src={item.imageUrl} alt=""/>}<span className="archive-icon">{kind==="events"?<CalendarDays/>:kind==="people"?<UserRound/>:<FileText/>}</span>{item.startsAt&&<time>{new Date(item.startsAt).toLocaleString("fi-FI",{dateStyle:"short",timeStyle:"short",hour12:false})}</time>}<h2>{title(item)}</h2><p>{summary(item)}</p>{item.location&&<small>{item.location}</small>}<a href={kind==="events"?`/${lang==="sv"?"evenemang":"events"}/${item.slug}`:kind==="news"?`/${lang==="sv"?"nyheter":"news"}/${item.slug}`:(item.ctaUrl||`mailto:info@asken.fi`)}>{kind==="people"?(lang==="sv"?"Kontakta":"Contact"):(lang==="sv"?"Läs mer":"Read more")}<ArrowUpRight/></a></article>):<div className="collection-empty">{lang==="sv"?"Inga publicerade poster ännu.":"No published items yet."}</div>}</div></section>;
}

export function DocumentCollection({lang,councilOnly=false}:{lang:PublicLanguage;councilOnly?:boolean}){
 const[items,setItems]=useState<Document[]>([]),[category,setCategory]=useState(councilOnly?"council":"all");
 useEffect(()=>{fetch("/api/public/documents").then(r=>r.json()).then(d=>setItems(d.items||[])).catch(()=>setItems([]))},[]);
 const shown=items.filter(item=>category==="all"||(category==="council"?["council_agenda","council_minutes"].includes(item.category):item.category===category));
 const labels:Record<string,string>={council_agenda:lang==="sv"?"Föredragningslista":"Agenda",council_minutes:lang==="sv"?"Protokoll":"Minutes",bylaws:lang==="sv"?"Stadgar":"Bylaws",regulation:lang==="sv"?"Reglemente":"Regulation",policy:"Policy",form:lang==="sv"?"Blankett":"Form",annual_report:lang==="sv"?"Årsberättelse":"Annual report",other:lang==="sv"?"Övrigt":"Other"};
 return <section className="public-collection"><div className="document-filters"><Select value={category} onValueChange={setCategory}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{!councilOnly&&<SelectItem value="all">{lang==="sv"?"Alla dokument":"All documents"}</SelectItem>}<SelectItem value="council">{lang==="sv"?"Fullmäktigematerial":"Council material"}</SelectItem>{!councilOnly&&Object.entries(labels).filter(([key])=>!["council_agenda","council_minutes"].includes(key)).map(([key,value])=><SelectItem key={key} value={key}>{value}</SelectItem>)}</SelectContent></Select></div><div className="document-list">{shown.length?shown.map(item=><article key={item.id}><FileText/><div><small>{labels[item.category]||item.category}{item.meetingDate?` · ${new Date(item.meetingDate).toLocaleDateString("fi-FI")}`:""}</small><h2>{lang==="sv"?item.titleSv:(item.titleEn||item.titleSv)}</h2><p>{lang==="sv"?item.descriptionSv:(item.descriptionEn||item.descriptionSv)}</p></div><a href={item.fileUrl} target="_blank" rel="noreferrer"><Download/>{lang==="sv"?"Öppna":"Open"}</a></article>):<div className="collection-empty">{lang==="sv"?"Inga publicerade dokument i denna kategori.":"No published documents in this category."}</div>}</div></section>;
}

export function ContactForm({lang,type}:{lang:PublicLanguage;type:"contact"|"support"|"harassment"|"tutoring"|"recruitment"|"partnership"|"event"}){
 const[form,setForm]=useState({name:"",email:"",organization:"",message:"",consentToContact:false,website:""}),[busy,setBusy]=useState(false),[result,setResult]=useState(""),[error,setError]=useState("");
 const set=(key:string,value:unknown)=>setForm(current=>({...current,[key]:value}));async function submit(event:React.FormEvent){event.preventDefault();setBusy(true);setError("");const r=await fetch("/api/forms",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({...form,type})});const d=await r.json();setBusy(false);if(!r.ok)return setError(d.error||"Error");setResult(d.reference)}
 if(result)return <section className="public-form success"><Send/><h2>{lang==="sv"?"Tack – meddelandet är mottaget":"Thank you—your message was received"}</h2><p>{lang==="sv"?"Referens":"Reference"}: <b>{result}</b></p></section>;
 return <form className="public-form" onSubmit={submit}><h2>{lang==="sv"?"Skicka ett meddelande":"Send a message"}</h2><div className="form-two"><div><Label>{lang==="sv"?"Namn":"Name"}</Label><Input required value={form.name} onChange={e=>set("name",e.target.value)}/></div><div><Label>{lang==="sv"?"E-post":"Email"}</Label><Input required type="email" value={form.email} onChange={e=>set("email",e.target.value)}/></div></div><div><Label>{lang==="sv"?"Organisation (valfritt)":"Organisation (optional)"}</Label><Input value={form.organization} onChange={e=>set("organization",e.target.value)}/></div><div className="form-honeypot" aria-hidden="true"><Label>Website</Label><Input tabIndex={-1} autoComplete="off" value={form.website} onChange={e=>set("website",e.target.value)}/></div><div><Label>{lang==="sv"?"Meddelande":"Message"}</Label><Textarea required minLength={10} value={form.message} onChange={e=>set("message",e.target.value)}/>{type==="harassment"&&<small>{lang==="sv"?"Skriv bara det som behövs för första kontakten.":"Share only what is needed for first contact."}</small>}</div><label className="consent-row"><Checkbox required checked={form.consentToContact} onCheckedChange={v=>set("consentToContact",v===true)}/><span>{lang==="sv"?"ASK får använda uppgifterna för att hantera och svara på detta ärende. Jag har läst dataskyddsinformationen.":"ASK may use this information to handle and answer this matter. I have read the data protection information."}</span></label><a className="privacy-inline" href={lang==="sv"?"/dataskydd":"/data-protection"}>{lang==="sv"?"Läs om dataskydd":"Read about data protection"}</a>{error&&<p className="form-error" role="alert">{error}</p>}<Button size="lg" disabled={busy}>{busy?"…":lang==="sv"?"Skicka":"Send"}</Button></form>;
}

export function PrivacyRequestForm({lang}:{lang:PublicLanguage}){
 const[form,setForm]=useState({type:"access",name:"",email:"",details:"",website:""}),[result,setResult]=useState(""),[error,setError]=useState("");const set=(k:string,v:string)=>setForm(x=>({...x,[k]:v}));async function submit(e:React.FormEvent){e.preventDefault();const r=await fetch("/api/privacy-requests",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(form)}),d=await r.json();if(!r.ok)return setError(d.error||"Error");setResult(d.reference)}
 if(result)return <section id="privacy-request" className="public-form success"><h2>{lang==="sv"?"Begäran mottagen":"Request received"}</h2><p>{lang==="sv"?"Referens":"Reference"}: <b>{result}</b></p></section>;
 return <form id="privacy-request" className="public-form" onSubmit={submit}><h2>{lang==="sv"?"Utöva dina rättigheter":"Exercise your rights"}</h2><Select value={form.type} onValueChange={v=>set("type",v)}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{[["access",lang==="sv"?"Tillgång":"Access"],["correction",lang==="sv"?"Rättelse":"Correction"],["deletion",lang==="sv"?"Radering":"Deletion"],["restriction",lang==="sv"?"Begränsning":"Restriction"],["objection",lang==="sv"?"Invändning":"Objection"],["portability",lang==="sv"?"Dataportabilitet":"Portability"],["photo_consent",lang==="sv"?"Fotografering och samtycke":"Photography and consent"]].map(([v,l])=><SelectItem key={v} value={v}>{l}</SelectItem>)}</SelectContent></Select><div className="form-two"><div><Label>{lang==="sv"?"Namn":"Name"}</Label><Input required value={form.name} onChange={e=>set("name",e.target.value)}/></div><div><Label>{lang==="sv"?"E-post":"Email"}</Label><Input required type="email" value={form.email} onChange={e=>set("email",e.target.value)}/></div></div><div className="form-honeypot" aria-hidden="true"><Input tabIndex={-1} value={form.website} onChange={e=>set("website",e.target.value)}/></div><div><Label>{lang==="sv"?"Beskriv begäran":"Describe the request"}</Label><Textarea required minLength={5} value={form.details} onChange={e=>set("details",e.target.value)}/></div><p>{lang==="sv"?"ASK kan be om ytterligare uppgifter för att säkert verifiera din identitet.":"ASK may request more information to verify your identity securely."}</p>{error&&<p className="form-error">{error}</p>}<Button>{lang==="sv"?"Skicka begäran":"Submit request"}</Button></form>;
}

export function PublicExtras({lang,kind,formType,councilOnly}:{lang:PublicLanguage;kind?:PublicPageKind;formType?:Parameters<typeof ContactForm>[0]["type"];councilOnly?:boolean}){
 if(kind==="news"||kind==="events"||kind==="people")return <ContentCollection lang={lang} kind={kind}/>;
 if(kind==="documents")return <DocumentCollection lang={lang} councilOnly={councilOnly}/>;
 if(kind==="contact"&&formType)return <ContactForm lang={lang} type={formType}/>;
 if(kind==="privacy_request")return <PrivacyRequestForm lang={lang}/>;
 return null;
}
