import { Db, ObjectId } from 'mongodb';
import { Migration } from './types';
const now = () => new Date();
const text = (sv: string, en: string) => ({ sv, en });
function theme(key: string, name: { sv: string; en: string }, type: string, campaignType: string | undefined, decorationType: string, hero: { sv: string; en: string }, body: { sv: string; en: string }, extra: Record<string, unknown> = {}) { return { key, name, description: text('', ''), type, status: 'active', enabled: key === 'gulis-theme', automaticActivation: key === 'gulis-theme', manualOverride: false, priority: key === 'gulis-theme' ? 100 : 20, recurringYearly: key === 'gulis-theme', startMonthDay: key === 'gulis-theme' ? '08-20' : undefined, endMonthDay: key === 'gulis-theme' ? '09-30' : undefined, timezone: 'Europe/Helsinki', decorationType, accentColor: decorationType === 'ducks' ? '#E0C13D' : undefined, secondaryAccentColor: decorationType === 'ducks' ? '#2E7D68' : undefined, animationEnabled: decorationType !== 'none', respectReducedMotion: true, announcementTitle: hero, announcementText: body, heroTitle: hero, heroText: body, ctaPrimaryLabel: key === 'gulis-theme' ? text('Bli medlem', 'Join ASK') : text('', ''), showOnHomepage: true, showAnnouncementBar: key === 'gulis-theme', showHeroDecoration: true, showNavigationBadge: false, highlightedNavItems: [], targetPages: ['home'], campaignType, createdAt: now(), updatedAt: now(), ...extra }; }
const themes = [
  theme('gulis-theme', text('Gulistema', 'Freshers Theme'), 'seasonal', 'gulis', 'ducks', text('Välkommen gulisar!', 'Welcome freshers!'), text('Börja ditt studieliv med ASK och upptäck gemenskapen på Arcada.', 'Start your student life with ASK and discover the Arcada community.')),
  theme('tutor-recruitment', text('Tutorrekrytering', 'Tutor Recruitment'), 'recruitment', 'tutor_recruitment', 'sparkles', text('Ansök som tutor', 'Apply as a tutor'), text('Hjälp nya studerande hitta hem på Arcada.', 'Help new students feel at home at Arcada.'), { enabled: false, automaticActivation: false }),
  theme('board-recruitment', text('Styrelserekrytering', 'Board Recruitment'), 'recruitment', 'board_recruitment', 'ribbons', text('Kandidera till styrelsen', 'Run for the board'), text('Var med och påverka ASK:s framtid.', 'Help shape ASK’s future.'), { enabled: false, automaticActivation: false }),
  theme('student-council-election', text('Fullmäktigeval', 'Student Council Election'), 'campaign', 'student_council_election', 'ribbons', text('Kandidera till fullmäktige', 'Run for Student Council'), text('Var med och fatta beslut om ASK:s riktning.', 'Take part in deciding ASK’s direction.'), { enabled: false, automaticActivation: false }),
  theme('christmas', text('Jul', 'Christmas'), 'seasonal', undefined, 'snow', text('God jul från ASK', 'Merry Christmas from ASK'), text('En varm hälsning till hela Arcada-gemenskapen.', 'Warm wishes to the whole Arcada community.'), { enabled: false, startMonthDay: '12-01', endMonthDay: '12-26', recurringYearly: true }),
  theme('new-year', text('Nyår', 'New Year'), 'seasonal', undefined, 'sparkles', text('Gott nytt år', 'Happy New Year'), text('Vi ses under ett nytt ASK-år.', 'See you in a new ASK year.'), { enabled: false, startMonthDay: '12-31', endMonthDay: '01-02', recurringYearly: true }),
  theme('vappen', text('Vappen', 'Vappen'), 'seasonal', undefined, 'confetti', text('Glad vappen', 'Happy Vappen'), text('Fira våren tillsammans med studerandegemenskapen.', 'Celebrate spring with the student community.'), { enabled: false, startMonthDay: '04-25', endMonthDay: '05-01', recurringYearly: true }),
  theme('pride-week', text('Prideveckan', 'Pride Week'), 'campaign', undefined, 'pride', text('Prideveckan', 'Pride Week'), text('ASK står för en trygg och inkluderande studerandegemenskap.', 'ASK stands for a safe and inclusive student community.'), { enabled: false }),
  theme('halloween', text('Halloween', 'Halloween'), 'seasonal', undefined, 'pumpkins', text('Halloween', 'Halloween'), text('Säsongsdekorationer för hösten.', 'Seasonal autumn decorations.'), { enabled: false, startMonthDay: '10-25', endMonthDay: '10-31', recurringYearly: true }),
  theme('swedish-day', text('Svenska dagen', 'Swedish Day in Finland'), 'seasonal', undefined, 'ribbons', text('Svenska dagen', 'Swedish Day in Finland'), text('En liten hälsning på Svenska dagen.', 'A small greeting for Swedish Day in Finland.'), { enabled: false, startMonthDay: '11-06', endMonthDay: '11-06', recurringYearly: true }),
  theme('independence-day', text('Självständighetsdagen', 'Independence Day'), 'seasonal', undefined, 'candles', text('Självständighetsdagen', 'Independence Day'), text('En högtidlig hälsning från ASK.', 'A solemn greeting from ASK.'), { enabled: false, startMonthDay: '12-06', endMonthDay: '12-06', recurringYearly: true }),
  theme('midsummer', text('Midsommar', 'Midsummer'), 'seasonal', undefined, 'flowers', text('Glad midsommar', 'Happy Midsummer'), text('Sommarhälsningar från ASK.', 'Summer greetings from ASK.'), { enabled: false, startMonthDay: '06-20', endMonthDay: '06-26', recurringYearly: true }),
  theme('custom-theme', text('Anpassat tema', 'Custom Theme'), 'custom', 'custom', 'custom', text('Anpassat tema', 'Custom Theme'), text('Ett redigerbart kampanjtema.', 'An editable campaign theme.'), { enabled: false, status: 'draft' }),
];
export const websiteThemesMigration: Migration = { id: '018-website-themes', description: 'Create website themes and seed editable seasonal/campaign defaults', up: async (database: Db) => { await database.collection('websitethemes').createIndex({ key: 1 }, { unique: true }); await database.collection('websitethemes').createIndex({ status: 1, enabled: 1, priority: -1, updatedAt: -1 }); for (const item of themes) await database.collection('websitethemes').updateOne({ key: item.key }, { $setOnInsert: { _id: new ObjectId(), ...item } }, { upsert: true }); const permissionSpecs = [['themes.read', 'View website theme management'], ['themes.write', 'Manage website themes']] as const; const permissionIds: ObjectId[] = []; for (const [key, description] of permissionSpecs) { await database.collection('permissions').updateOne({ key }, { $set: { description }, $setOnInsert: { _id: new ObjectId(), schemaVersion: 1 } }, { upsert: true }); const permission = await database.collection('permissions').findOne<{ _id: ObjectId }>({ key }); if (permission) permissionIds.push(permission._id); } if (permissionIds.length) await database.collection('roles').updateOne({ key: 'super_admin' }, { $addToSet: { permissionIds: { $each: permissionIds } } }); }, down: async () => {} };
