export const defaultCollaborations = [
  { id:"default-commedia", slug:"commedia-rf", name:"Commedia rf", type:"association", shortDescriptionSv:"Ämnesföreningen för film- och mediastuderande vid Arcada.", shortDescriptionEn:"The student association for film and media students at Arcada.", descriptionSv:"Commedia rf skapar gemenskap och verksamhet för Arcadas film- och mediastuderande.", descriptionEn:"Commedia rf creates community and activities for Arcada’s film and media students.", websiteUrl:"https://www.instagram.com/commediarf/", logoUrl:"", featured:false, active:true, visible:true, approvalStatus:"approved" },
  { id:"default-hanse", slug:"hanse-sf", name:"HanSe SF", type:"association", shortDescriptionSv:"Ämnesföreningen för företagsekonomi- och International Business-studerande vid Arcada.", shortDescriptionEn:"The association for Business Administration and International Business students at Arcada.", descriptionSv:"HanSe SF skapar gemenskap, traditioner och evenemang för Arcadas ekonomistuderande.", descriptionEn:"HanSe SF creates community, traditions and events for Arcada’s business students.", websiteUrl:"https://hansesf.net/", logoUrl:"", featured:false, active:true, visible:true, approvalStatus:"approved" },
  { id:"default-hosk", slug:"hosk-rf", name:"HoSK r.f.", type:"association", shortDescriptionSv:"Studerandeföreningen för vård, hälsa och välfärd vid Arcada.", shortDescriptionEn:"The association for healthcare, health and welfare students at Arcada.", descriptionSv:"HoSK r.f. ordnar verksamhet och stöder gemenskapen inom vård, hälsa och välfärd.", descriptionEn:"HoSK r.f. organises activities and supports the healthcare, health and welfare community.", websiteUrl:"https://hosk.fi/", logoUrl:"", featured:false, active:true, visible:true, approvalStatus:"approved" },
  { id:"default-tlk", slug:"tlk-rf", name:"TLK r.f.", type:"association", shortDescriptionSv:"Tekniska Läroverkets Kamratförbund för ingenjörsstuderande vid Arcada.", shortDescriptionEn:"The engineering student association at Arcada.", descriptionSv:"TLK r.f. främjar kamratskap och ordnar verksamhet för ingenjörsstuderande.", descriptionEn:"TLK r.f. promotes community and organises activities for engineering students.", websiteUrl:"https://www.tlk.fi/", logoUrl:"", featured:false, active:true, visible:true, approvalStatus:"approved" },
  { id:"default-kult", slug:"kult-rf", name:"Kult rf", type:"association", shortDescriptionSv:"Ämnesföreningen för kulturproducentstuderande vid Arcada.", shortDescriptionEn:"The association for cultural management students at Arcada.", descriptionSv:"Kult rf skapar gemenskap och verksamhet för kulturproducentstuderande vid Arcada.", descriptionEn:"Kult rf creates community and activities for cultural management students at Arcada.", websiteUrl:"https://www.instagram.com/kultrf/", logoUrl:"", featured:false, active:true, visible:true, approvalStatus:"approved" },
  { id:"default-arcada", slug:"arcada-uas", name:"Yrkeshögskolan Arcada", type:"partner", shortDescriptionSv:"ASK:s högskolegemenskap i Helsingfors.", shortDescriptionEn:"ASK’s university of applied sciences community in Helsinki.", descriptionSv:"ASK representerar studerande vid Arcada och samarbetar med högskolan i frågor som berör studentvardagen.", descriptionEn:"ASK represents students at Arcada and works with the university on student-life matters.", websiteUrl:"https://www.arcada.fi/", logoUrl:"", featured:true, active:true, visible:true, approvalStatus:"approved" },
  { id:"default-samok", slug:"samok", name:"SAMOK", type:"partner", shortDescriptionSv:"Finlands studerandekårers förbund för yrkeshögskolestuderande.", shortDescriptionEn:"The national union of students at universities of applied sciences in Finland.", descriptionSv:"ASK deltar i det nationella studentinflytandet genom SAMOK:s nätverk och verksamhet.", descriptionEn:"ASK participates in national student advocacy through SAMOK’s networks and activities.", websiteUrl:"https://samok.fi/", logoUrl:"", featured:false, active:true, visible:true, approvalStatus:"approved" },
  { id:"default-kide", slug:"kide-app", name:"Kide.app", type:"partner", shortDescriptionSv:"Plattform som ASK använder för medlemskap och evenemangsbiljetter.", shortDescriptionEn:"The platform ASK uses for memberships and event tickets.", descriptionSv:"Kide.app stöder ASK:s digitala försäljning av medlemskap och evenemangsbiljetter.", descriptionEn:"Kide.app supports ASK’s digital sale of memberships and event tickets.", websiteUrl:"https://kide.app/community/b112ffe9-2deb-4894-a4b8-ed1b70ef1a00", logoUrl:"", featured:false, active:true, visible:true, approvalStatus:"approved" },
] as const;
