import request from 'supertest';
import { createApp } from '../../app';
import { Env } from '../../env';
import { issueTokens } from '../../identity/security/tokens';
import { AuthPrincipal, IdentityService } from '../../identity/types';
import { ThemeService, WebsiteTheme } from '../types';
const env = { NODE_ENV: 'test', PORT: 3000, MONGO_URI: 'mongodb://localhost:27017/asken-test', JWT_ACCESS_SECRET: 'access-secret-with-at-least-32-characters', JWT_REFRESH_SECRET: 'refresh-secret-with-at-least-32-characters', ACCESS_TOKEN_TTL_SECONDS: 900, REFRESH_TOKEN_TTL_DAYS: 7, BCRYPT_ROUNDS: 10, COOKIE_SECURE: false, FRONTEND_URL: 'http://localhost:5173', ADMIN_URL: 'http://localhost:5174', SMTP_HOST: 'localhost', SMTP_AUTH: false, SMTP_SECURE: false, SMTP_PORT: 1025, SMTP_USER: 'test@example.com', SMTP_PASS: 'password', SUPER_ADMIN_NAME: 'Super Admin' } satisfies Env;
const principal: AuthPrincipal = { userId: '507f1f77bcf86cd799439011', email: 'admin@example.com', name: 'Admin', roles: ['super_admin'], permissions: ['themes.read', 'themes.write'] };
const theme: WebsiteTheme = { id: '507f1f77bcf86cd799439099', key: 'gulis-theme', name: { sv: 'Gulistema', en: 'Freshers Theme' }, type: 'seasonal', status: 'active', enabled: true, automaticActivation: true, manualOverride: false, priority: 100, recurringYearly: true, startMonthDay: '08-20', endMonthDay: '09-30', timezone: 'Europe/Helsinki', decorationType: 'ducks', accentColor: '#E0C13D', animationEnabled: true, respectReducedMotion: true, announcementTitle: { sv: 'Välkommen gulisar!', en: 'Welcome freshers!' }, announcementText: { sv: 'Din start på studielivet börjar här.', en: 'Your student life starts here.' }, heroTitle: { sv: 'Välkommen gulisar!', en: 'Welcome freshers!' }, heroText: { sv: 'Börja ditt studieliv med ASK.', en: 'Start your student life with ASK.' }, ctaPrimaryLabel: { sv: 'Bli medlem', en: 'Join ASK' }, ctaPrimaryUrl: 'https://kide.app/', showOnHomepage: true, showAnnouncementBar: true, showHeroDecoration: true, showNavigationBadge: false, highlightedNavItems: [], targetPages: ['home'], campaignType: 'gulis', createdAt: new Date(), updatedAt: new Date() };
function identity(current: AuthPrincipal = principal): IdentityService { return { login: jest.fn(async () => ({ principal: current, ...issueTokens(current.userId, '507f191e810c19729de860ea', env) })), refresh: jest.fn(), logout: jest.fn(), changePassword: jest.fn(), getPrincipal: jest.fn(async () => current), listUsers: jest.fn(), createUser: jest.fn(), updateUser: jest.fn(), listRoles: jest.fn(), createRole: jest.fn(), updateRolePermissions: jest.fn(), listPermissions: jest.fn() } as unknown as IdentityService; }
function service(): ThemeService { return { listAdmin: jest.fn(async () => [theme]), create: jest.fn(async (input) => ({ ...theme, ...input })), update: jest.fn(async (_id, input) => ({ ...theme, ...input })), archive: jest.fn(async () => undefined), activeResolution: jest.fn(async () => ({ theme, reason: 'recurring_schedule', overlappingThemes: [], nextThemes: [] })), getPublicActive: jest.fn(async () => ({ id: theme.id, key: theme.key, name: theme.name.sv, type: theme.type, decorationType: theme.decorationType, accentColor: theme.accentColor, animationEnabled: theme.animationEnabled, respectReducedMotion: theme.respectReducedMotion, announcementTitle: theme.announcementTitle.sv, announcementText: theme.announcementText.sv, heroTitle: theme.heroTitle.sv, heroText: theme.heroText.sv, ctaPrimaryLabel: theme.ctaPrimaryLabel?.sv, ctaPrimaryUrl: theme.ctaPrimaryUrl, showOnHomepage: true, showAnnouncementBar: true, showHeroDecoration: true, showNavigationBadge: false, highlightedNavItems: [], targetPages: ['home'], campaignType: 'gulis', activeReason: 'recurring_schedule' })), preview: jest.fn(async () => ({ id: theme.id, key: theme.key, name: theme.name.sv, type: theme.type, decorationType: theme.decorationType, animationEnabled: true, respectReducedMotion: true, announcementTitle: theme.announcementTitle.sv, announcementText: theme.announcementText.sv, heroTitle: theme.heroTitle.sv, heroText: theme.heroText.sv, showOnHomepage: true, showAnnouncementBar: true, showHeroDecoration: true, showNavigationBadge: false, highlightedNavItems: [], targetPages: ['home'], activeReason: 'preview' })) } as unknown as ThemeService; }
function app(current: AuthPrincipal = principal, themeService = service()) { return createApp({ env, identityService: identity(current), cmsService: {} as never, newsService: {} as never, eventService: {} as never, themeService }); }
async function login(application: ReturnType<typeof app>) { return request(application).post('/api/v1/auth/login').send({ email: 'admin@example.com', password: 'Password1!' }); }
describe('theme routes', () => { it('serves public active theme without admin fields', async () => { const response = await request(app()).get('/api/v1/themes/active?lang=sv'); expect(response.body.data.theme.key).toBe('gulis-theme'); expect(response.body.data.theme.createdBy).toBeUndefined(); }); it('protects admin endpoints and enforces write permissions', async () => { const application = app(); expect((await request(application).get('/api/v1/admin/themes')).status).toBe(401); const session = await login(application); expect((await request(application).get('/api/v1/admin/themes').set('Cookie', session.headers['set-cookie'])).status).toBe(200); const readOnly = app({ ...principal, permissions: ['themes.read'] }); const readOnlySession = await login(readOnly); expect((await request(readOnly).post('/api/v1/admin/themes').set('Cookie', readOnlySession.headers['set-cookie']).send({ ...theme, id: undefined })).status).toBe(403); }); });
