import type { Metadata } from "next";
import type { CSSProperties } from "react";
import { notFound } from "next/navigation";
import { and, asc, eq, lte, or } from "drizzle-orm";
import { ArrowUpRight, CalendarDays, MapPin } from "lucide-react";
import { getDb } from "@/db";
import { collaborations, contentItems, eventCollaborations } from "@/db/schema";
import { defaultCollaborations } from "@/lib/default-collaborations";
import { effectiveAssociationColor } from "@/lib/association-brand";
import PublicShell from "@/components/public-shell";

export const dynamic="force-dynamic";
const parents:Record<string,{lang:"sv"|"en";type:"news"|"event"|"collaboration";alternate:string;back:string}>={nyheter:{lang:"sv",type:"news",alternate:"news",back:"Alla nyheter"},news:{lang:"en",type:"news",alternate:"nyheter",back:"All news"},evenemang:{lang:"sv",type:"event",alternate:"events",back:"Alla evenemang"},events:{lang:"en",type:"event",alternate:"evenemang",back:"All events"},samarbeten:{lang:"sv",type:"collaboration",alternate:"collaborations",back:"Alla samarbeten"},collaborations:{lang:"en",type:"collaboration",alternate:"samarbeten",back:"All collaborations"}};

async function load(parent:string,slug:string){const config=parents[parent];if(!config)return null;if(config.type==="collaboration"){try{const[row]=await getDb().select().from(collaborations).where(and(eq(collaborations.slug,slug),eq(collaborations.active,true),eq(collaborations.visible,true))).limit(1);return row||defaultCollaborations.find(item=>item.slug===slug)||null}catch{return defaultCollaborations.find(item=>item.slug===slug)||null}}try{const now=new Date().toISOString();const[row]=await getDb().select().from(contentItems).where(and(eq(contentItems.type,config.type),eq(contentItems.slug,slug),eq(contentItems.reviewStatus,"approved"),or(eq(contentItems.status,"published"),and(eq(contentItems.status,"scheduled"),lte(contentItems.publishAt,now))))).limit(1);return row||null}catch{return null}}
async function loadEventAssociations(eventId:string){try{const rows=await getDb().select({slug:collaborations.slug,name:collaborations.name,type:collaborations.type,role:eventCollaborations.role,brandColor:collaborations.brandColor,logoUrl:collaborations.logoUrl,approvalStatus:collaborations.approvalStatus}).from(eventCollaborations).innerJoin(collaborations,eq(eventCollaborations.collaborationId,collaborations.id)).where(and(eq(eventCollaborations.eventId,eventId),eq(eventCollaborations.visiblePublicly,true),eq(collaborations.active,true),eq(collaborations.visible,true))).orderBy(asc(eventCollaborations.sortOrder));return rows.filter((row)=>row.type!=="sponsor"||row.approvalStatus==="approved").map((row)=>({...row,brandColor:effectiveAssociationColor(row.slug,row.brandColor)}))}catch{return[]}}
export async function generateMetadata({params}:{params:Promise<{slug:string;item:string}>}):Promise<Metadata>{const{slug,item}=await params,config=parents[slug],data=await load(slug,item);if(!config||!data)return{};const title=config.type==="collaboration"?(data as typeof collaborations.$inferSelect).name:config.lang==="sv"?(data as typeof contentItems.$inferSelect).titleSv:((data as typeof contentItems.$inferSelect).titleEn||(data as typeof contentItems.$inferSelect).titleSv);return{title:`${title} | ASK`,alternates:{canonical:`/${slug}/${item}`,languages:{[config.lang]:`/${slug}/${item}`,[config.lang==="sv"?"en":"sv"]:`/${config.alternate}/${item}`}}}}
export default async function Detail({params}:{params:Promise<{slug:string;item:string}>}){const{slug,item}=await params,config=parents[slug];if(!config)notFound();const data=await load(slug,item);if(!data)notFound();const alt=`/${config.alternate}/${item}`;
 if(config.type==="collaboration"){const c=data as typeof collaborations.$inferSelect;const description=config.lang==="sv"?c.descriptionSv:(c.descriptionEn||c.descriptionSv);return <PublicShell lang={config.lang} alternate={alt}><article className="detail-page"><a className="detail-back" href={`/${slug}`}>← {config.back}</a><header><span>{c.type}</span><h1>{c.name}</h1><p>{config.lang==="sv"?c.shortDescriptionSv:(c.shortDescriptionEn||c.shortDescriptionSv)}</p></header><section><h2>{config.lang==="sv"?"Om organisationen":"About the organisation"}</h2>{description.split(/\n+/).map((p,i)=><p key={i}>{p}</p>)}{c.websiteUrl&&<a className="pill" href={c.websiteUrl} target="_blank" rel="noreferrer">{config.lang==="sv"?"Besök webbplats":"Visit website"}<ArrowUpRight/></a>}</section></article></PublicShell>}
 const c=data as typeof contentItems.$inferSelect,title=config.lang==="sv"?c.titleSv:(c.titleEn||c.titleSv),summary=config.lang==="sv"?c.summarySv:(c.summaryEn||c.summarySv),body=config.lang==="sv"?c.bodySv:(c.bodyEn||c.bodySv),associations=config.type==="event"?await loadEventAssociations(c.id):[],primary=associations[0];return <PublicShell lang={config.lang} alternate={alt}><article className={`detail-page ${primary?"event-detail-branded":""}`} style={primary?({"--association-color":primary.brandColor} as CSSProperties):undefined}><a className="detail-back" href={`/${slug}`}>← {config.back}</a><header>{c.imageUrl&&<img src={c.imageUrl} alt={title}/>}<span>{config.type==="event"?(config.lang==="sv"?"Evenemang":"Event"):(config.lang==="sv"?"Nyhet":"News")}</span><h1>{title}</h1><p>{summary}</p>{associations.length?<div className="event-brand-list">{associations.map(association=><a style={{"--association-color":association.brandColor} as CSSProperties} href={`/${config.lang==="sv"?"samarbeten":"collaborations"}/${association.slug}`} key={`${association.slug}-${association.role}`}><i/>{association.name}{association.type==="sponsor"?` · ${config.lang==="sv"?"sponsor":"sponsor"}`:""}</a>)}</div>:null}{config.type==="event"&&<div className="detail-meta">{c.startsAt&&<span><CalendarDays/>{new Date(c.startsAt).toLocaleString("fi-FI",{dateStyle:"short",timeStyle:"short",hour12:false,timeZone:"Europe/Helsinki"})}</span>}{c.location&&<span><MapPin/>{c.location}</span>}</div>}</header><section>{body.split(/\n+/).filter(Boolean).map((p,i)=><p key={i}>{p}</p>)}{c.ctaUrl&&<a className="pill" href={c.ctaUrl} target="_blank" rel="noreferrer">{config.lang==="sv"?"Öppna länk / biljett":"Open link / ticket"}<ArrowUpRight/></a>}</section></article></PublicShell>}
