import { and, eq, like, or } from "drizzle-orm";
import { getDb } from "@/db";
import { collaborations, contentItems, publicDocuments } from "@/db/schema";
import { publicPages } from "@/lib/public-pages";
import { defaultCollaborations } from "@/lib/default-collaborations";
export const dynamic="force-dynamic";
export async function GET(request:Request){const url=new URL(request.url),query=(url.searchParams.get("q")||"").trim().slice(0,80),lang=url.searchParams.get("lang")==="en"?"en":"sv";if(query.length<2)return Response.json({items:[]});const q=`%${query.replace(/[%_]/g,"")}%`;let content:typeof contentItems.$inferSelect[]=[],partners:typeof collaborations.$inferSelect[]=[],documents:typeof publicDocuments.$inferSelect[]=[];try{[content,partners,documents]=await Promise.all([getDb().select().from(contentItems).where(and(eq(contentItems.status,"published"),or(like(contentItems.titleSv,q),like(contentItems.titleEn,q),like(contentItems.summarySv,q),like(contentItems.summaryEn,q)))).limit(20),getDb().select().from(collaborations).where(and(eq(collaborations.active,true),eq(collaborations.visible,true),or(like(collaborations.name,q),like(collaborations.descriptionSv,q),like(collaborations.descriptionEn,q)))).limit(20),getDb().select().from(publicDocuments).where(and(eq(publicDocuments.status,"published"),or(like(publicDocuments.titleSv,q),like(publicDocuments.titleEn,q),like(publicDocuments.descriptionSv,q),like(publicDocuments.descriptionEn,q)))).limit(20)])}catch{}
 const normalized=query.toLowerCase(),staticItems=Object.entries(publicPages).filter(([,page])=>page.lang===lang&&`${page.title} ${page.lead} ${page.sections.map(x=>`${x.title} ${x.body?.join(" ")||""} ${x.bullets?.join(" ")||""}`).join(" ")}`.toLowerCase().includes(normalized)).slice(0,20).map(([slug,page])=>({type:"page",title:page.title,summary:page.lead,href:`/${slug}`}));
 const defaultPartners=defaultCollaborations.filter(item=>`${item.name} ${lang==="sv"?item.descriptionSv:item.descriptionEn}`.toLowerCase().includes(normalized)&&!partners.some(row=>row.slug===item.slug));
 const items=[...staticItems,...content.map(item=>({type:item.type,title:lang==="sv"?item.titleSv:(item.titleEn||item.titleSv),summary:lang==="sv"?item.summarySv:(item.summaryEn||item.summarySv),href:`/${item.type==="event"?(lang==="sv"?"evenemang":"events"):(lang==="sv"?"nyheter":"news")}/${item.slug}`})),...[...partners,...defaultPartners].map(item=>({type:"collaboration",title:item.name,summary:lang==="sv"?item.shortDescriptionSv:(item.shortDescriptionEn||item.shortDescriptionSv),href:`/${lang==="sv"?"samarbeten":"collaborations"}/${item.slug}`})),...documents.map(item=>({type:"document",title:lang==="sv"?item.titleSv:(item.titleEn||item.titleSv),summary:lang==="sv"?item.descriptionSv:(item.descriptionEn||item.descriptionSv),href:item.fileUrl}))].slice(0,50);return Response.json({items},{headers:{"cache-control":"public, max-age=30"}})}
