import { Types } from 'mongoose';
import { slugify } from '../../cms/utils/slug';
import { AppError } from '../../http/errors';
import { localizedValue } from '../../localization/languages';
import { RepresentativeBodyModel } from '../models/RepresentativeBody';
import { RepresentativeCallModel } from '../models/RepresentativeCall';
import { StudentRepresentativeModel } from '../models/StudentRepresentative';
import { CurrentRepresentativesGroup, PublicRepresentativeBody, PublicRepresentativeCall, PublicStudentRepresentative, RepresentativeBody, RepresentativeCall, RepresentativeCallStatus, RepresentativesLocale, RepresentativesService, StudentRepresentative } from '../types';

type Doc = Record<string, any>;
export function calculateRepresentativeCallStatus(openingDate: Date, closingDate: Date, now = new Date()): RepresentativeCallStatus { if (now < openingDate) return 'coming_soon'; if (now > closingDate) return 'closed'; return 'open'; }
export class MongooseRepresentativesService implements RepresentativesService {
  async listPublicBodies(locale: RepresentativesLocale) { return (await RepresentativeBodyModel.find({ active: true, visible: true }).sort({ displayOrder: 1, 'name.sv': 1 }).lean()).map((doc) => this.publicBody(doc, locale)); }
  async getPublicBody(slug: string, locale: RepresentativesLocale) { const body = await RepresentativeBodyModel.findOne({ slug, active: true, visible: true }).lean(); if (!body) throw new AppError(404, 'REPRESENTATIVE_BODY_NOT_FOUND', 'Representative body was not found'); const reps = await StudentRepresentativeModel.find({ bodyId: body._id, status: 'active', publicProfile: true }).sort({ displayOrder: 1, fullName: 1 }).lean(); const calls = await RepresentativeCallModel.find({ bodyId: body._id, published: true }).sort({ featured: -1, displayOrder: 1, closingDate: 1 }).lean(); return { body: this.publicBody(body, locale), representatives: reps.map((doc) => this.publicRepresentative(doc, locale)), calls: calls.map((doc) => this.publicCall(doc, locale, body)) }; }
  async listCurrentRepresentatives(locale: RepresentativesLocale): Promise<CurrentRepresentativesGroup[]> { const bodies = await RepresentativeBodyModel.find({ active: true, visible: true }).sort({ displayOrder: 1, 'name.sv': 1 }).lean(); const reps = await StudentRepresentativeModel.find({ status: 'active', publicProfile: true, bodyId: { $in: bodies.map((b) => b._id) } }).sort({ displayOrder: 1, fullName: 1 }).lean(); return bodies.map((body) => ({ body: this.publicBody(body, locale), representatives: reps.filter((rep) => rep.bodyId.toString() === body._id.toString()).map((rep) => this.publicRepresentative(rep, locale)) })).filter((group) => group.representatives.length > 0); }
  async listPublicCalls(locale: RepresentativesLocale) { const calls = await RepresentativeCallModel.find({ published: true }).sort({ featured: -1, displayOrder: 1, closingDate: 1 }).lean(); const bodies = await RepresentativeBodyModel.find({ _id: { $in: calls.map((call) => call.bodyId).filter(Boolean) }, active: true, visible: true }).lean(); const byId = new Map(bodies.map((body) => [body._id.toString(), body])); return calls.map((call) => this.publicCall(call, locale, call.bodyId ? byId.get(call.bodyId.toString()) : undefined)); }
  async listBodies() { return (await RepresentativeBodyModel.find().sort({ displayOrder: 1, 'name.sv': 1 }).lean()).map(this.body); }
  async createBody(input: Omit<RepresentativeBody, 'id' | 'createdAt' | 'updatedAt'>) { try { return this.body((await RepresentativeBodyModel.create({ ...input, slug: this.slug(input.slug || input.name.sv) })).toObject()); } catch (e) { this.dup(e, 'REPRESENTATIVE_BODY_SLUG_IN_USE'); throw e; } }
  async updateBody(id: string, input: Omit<RepresentativeBody, 'id' | 'createdAt' | 'updatedAt'>) { this.id(id); try { const doc = await RepresentativeBodyModel.findByIdAndUpdate(id, { $set: { ...input, slug: this.slug(input.slug || input.name.sv) } }, { new: true }).lean(); if (!doc) throw new AppError(404, 'REPRESENTATIVE_BODY_NOT_FOUND', 'Representative body was not found'); return this.body(doc); } catch (e) { this.dup(e, 'REPRESENTATIVE_BODY_SLUG_IN_USE'); throw e; } }
  async deactivateBody(id: string) { this.id(id); const r = await RepresentativeBodyModel.updateOne({ _id: id }, { $set: { active: false, visible: false } }); if (!r.matchedCount) throw new AppError(404, 'REPRESENTATIVE_BODY_NOT_FOUND', 'Representative body was not found'); }
  async listRepresentatives() { return (await StudentRepresentativeModel.find().sort({ status: 1, displayOrder: 1, fullName: 1 }).lean()).map(this.representative); }
  async createRepresentative(input: Omit<StudentRepresentative, 'id' | 'createdAt' | 'updatedAt'>) { return this.representative((await StudentRepresentativeModel.create(input)).toObject()); }
  async updateRepresentative(id: string, input: Omit<StudentRepresentative, 'id' | 'createdAt' | 'updatedAt'>) { this.id(id); const doc = await StudentRepresentativeModel.findByIdAndUpdate(id, { $set: input }, { new: true }).lean(); if (!doc) throw new AppError(404, 'STUDENT_REPRESENTATIVE_NOT_FOUND', 'Student representative was not found'); return this.representative(doc); }
  async deactivateRepresentative(id: string) { this.id(id); const r = await StudentRepresentativeModel.updateOne({ _id: id }, { $set: { status: 'ended', publicProfile: false } }); if (!r.matchedCount) throw new AppError(404, 'STUDENT_REPRESENTATIVE_NOT_FOUND', 'Student representative was not found'); }
  async listCalls() { return (await RepresentativeCallModel.find().sort({ featured: -1, displayOrder: 1, closingDate: 1 }).lean()).map(this.call); }
  async createCall(input: Omit<RepresentativeCall, 'id' | 'createdAt' | 'updatedAt' | 'status'> & { status?: RepresentativeCallStatus }) { return this.call((await RepresentativeCallModel.create({ ...input, status: input.status || calculateRepresentativeCallStatus(input.openingDate, input.closingDate) })).toObject()); }
  async updateCall(id: string, input: Omit<RepresentativeCall, 'id' | 'createdAt' | 'updatedAt' | 'status'> & { status?: RepresentativeCallStatus }) { this.id(id); const doc = await RepresentativeCallModel.findByIdAndUpdate(id, { $set: { ...input, status: input.status || calculateRepresentativeCallStatus(input.openingDate, input.closingDate) } }, { new: true }).lean(); if (!doc) throw new AppError(404, 'REPRESENTATIVE_CALL_NOT_FOUND', 'Representative call was not found'); return this.call(doc); }
  async deactivateCall(id: string) { this.id(id); const r = await RepresentativeCallModel.updateOne({ _id: id }, { $set: { published: false, featured: false, status: 'closed' } }); if (!r.matchedCount) throw new AppError(404, 'REPRESENTATIVE_CALL_NOT_FOUND', 'Representative call was not found'); }
  private body = (doc: Doc): RepresentativeBody => ({ id: doc._id.toString(), name: doc.name, slug: doc.slug, description: doc.description, category: doc.category, appointingBody: doc.appointingBody, defaultTermLengthMonths: doc.defaultTermLengthMonths, defaultSeatCount: doc.defaultSeatCount, defaultDeputySeatCount: doc.defaultDeputySeatCount, eligibilityDescription: doc.eligibilityDescription, applicationInstructions: doc.applicationInstructions, active: doc.active, visible: doc.visible, displayOrder: doc.displayOrder, createdAt: doc.createdAt, updatedAt: doc.updatedAt });
  private representative = (doc: Doc): StudentRepresentative => ({ id: doc._id.toString(), bodyId: doc.bodyId.toString(), fullName: doc.fullName, email: doc.email, contactPublic: Boolean(doc.contactPublic), studyProgramme: doc.studyProgramme, role: doc.role, termStart: doc.termStart, termEnd: doc.termEnd, status: doc.status, appointedBy: doc.appointedBy, appointmentDate: doc.appointmentDate, publicProfile: doc.publicProfile, photoUrl: doc.photoUrl, description: doc.description || { sv: '', en: '' }, displayOrder: doc.displayOrder, createdAt: doc.createdAt, updatedAt: doc.updatedAt });
  private call = (doc: Doc): RepresentativeCall => ({ id: doc._id.toString(), title: doc.title, bodyId: doc.bodyId?.toString(), description: doc.description, openingDate: doc.openingDate, closingDate: doc.closingDate, numberOfSeats: doc.numberOfSeats, eligibility: doc.eligibility, applicationInstructions: doc.applicationInstructions, ctaLabel: doc.ctaLabel, ctaUrl: doc.ctaUrl, contactEmail: doc.contactEmail, status: calculateRepresentativeCallStatus(doc.openingDate, doc.closingDate), published: doc.published, featured: doc.featured, displayOrder: doc.displayOrder, createdAt: doc.createdAt, updatedAt: doc.updatedAt });
  private publicBody(doc: Doc, locale: RepresentativesLocale): PublicRepresentativeBody { return { id: doc._id.toString(), name: localizedValue(doc.name, locale), slug: doc.slug, description: localizedValue(doc.description, locale), category: doc.category, appointingBody: doc.appointingBody, defaultTermLengthMonths: doc.defaultTermLengthMonths, defaultSeatCount: doc.defaultSeatCount, defaultDeputySeatCount: doc.defaultDeputySeatCount, eligibilityDescription: localizedValue(doc.eligibilityDescription, locale), applicationInstructions: localizedValue(doc.applicationInstructions, locale) }; }
  private publicRepresentative(doc: Doc, locale: RepresentativesLocale): PublicStudentRepresentative { return { id: doc._id.toString(), bodyId: doc.bodyId.toString(), fullName: doc.fullName, email: doc.contactPublic ? doc.email : undefined, studyProgramme: doc.studyProgramme, role: doc.role, termStart: doc.termStart, termEnd: doc.termEnd, status: doc.status, appointedBy: doc.appointedBy, appointmentDate: doc.appointmentDate, photoUrl: doc.photoUrl, description: localizedValue(doc.description || { sv: '', en: '' }, locale), displayOrder: doc.displayOrder }; }
  private publicCall(doc: Doc, locale: RepresentativesLocale, body?: Doc): PublicRepresentativeCall { return { id: doc._id.toString(), title: localizedValue(doc.title, locale), bodyId: doc.bodyId?.toString(), body: body ? this.publicBody(body, locale) : undefined, description: localizedValue(doc.description, locale), openingDate: doc.openingDate, closingDate: doc.closingDate, numberOfSeats: doc.numberOfSeats, eligibility: localizedValue(doc.eligibility, locale), applicationInstructions: localizedValue(doc.applicationInstructions, locale), ctaLabel: localizedValue(doc.ctaLabel, locale), ctaUrl: doc.ctaUrl, contactEmail: doc.contactEmail, status: calculateRepresentativeCallStatus(doc.openingDate, doc.closingDate), featured: doc.featured, displayOrder: doc.displayOrder }; }
  private id(v: string) { if (!Types.ObjectId.isValid(v)) throw new AppError(400, 'INVALID_ID', 'Identifier is invalid'); }
  private slug(v: string) { const slug = slugify(v); if (!slug) throw new AppError(400, 'INVALID_SLUG', 'Slug is invalid'); return slug; }
  private dup(e: unknown, code: string) { if ((e as { code?: number }).code === 11000) throw new AppError(409, code, 'Slug is already in use'); }
}
