import { FormEvent,useEffect,useMemo,useState } from 'react';
import { Link } from 'react-router-dom';
import { calculatePrice,createBooking,getAvailability,listBookingCategories,listBookingResources } from '../booking/api';
import { bookingContent } from '../booking/content';
import { BookingCategory,BookingLocale,BookingRequest,BookingResource,BookingStatusRecord,BookingType,PriceBreakdown } from '../booking/types';
import PageHero from '../components/PageHero';
import PublicLayout from '../components/PublicLayout';
import { usePageMetadata } from '../hooks/usePageMetadata';
import { useSiteLocale } from '../hooks/useSiteLocale';
import { formatTimeRange } from '../utils/dateTime';
const localInput=(date:Date)=>new Date(date.getTime()-date.getTimezoneOffset()*60000).toISOString().slice(0,16);
const euros=(value:number)=>`${value.toFixed(2)} €`;
export default function Booking(){
 const{locale}=useSiteLocale(),[bookingLocale,setBookingLocale]=useState<BookingLocale>(locale),copy=bookingContent[bookingLocale];const[resources,setResources]=useState<BookingResource[]>([]),[categories,setCategories]=useState<BookingCategory[]>([]),[resourceId,setResourceId]=useState(''),[date,setDate]=useState(new Date().toISOString().slice(0,10)),[intervals,setIntervals]=useState<Array<{startAt:string;endAt:string;kind:'booking'|'blackout'}>>([]),[error,setError]=useState(''),[sending,setSending]=useState(false),[confirmation,setConfirmation]=useState<BookingStatusRecord|null>(null),[estimate,setEstimate]=useState<PriceBreakdown|null>(null);
 const tomorrow=new Date(Date.now()+86_400_000),initialStart=localInput(new Date(tomorrow.setHours(10,0,0,0))),initialEnd=localInput(new Date(tomorrow.setHours(14,0,0,0)));
 const[form,setForm]=useState({startAt:initialStart,endAt:initialEnd,requesterName:'',requesterEmail:'',requesterPhone:'',organization:'',bookingType:'ask_member' as BookingType,internalAskPurpose:'official_activity' as 'official_activity'|'private_booking',mandateYear:new Date().getFullYear(),kitchenExtra:false,saunaExtra:false,purpose:'',attendees:1,accessibilityNeeds:'',privacyAccepted:false,billing:{name:'',address:'',postalCode:'',city:'',country:'Finland',vatOrBusinessId:'',referenceNumber:''}});
 const selected=resources.find(resource=>resource.id===resourceId),selectedCategory=categories.find(category=>category.key===form.bookingType),ordered=useMemo(()=>[...intervals].sort((a,b)=>a.startAt.localeCompare(b.startAt)),[intervals]),paid=Boolean(estimate&&estimate.totalPrice>0),billingComplete=!paid||Boolean(form.billing.name.trim()&&form.billing.address.trim()&&form.billing.postalCode.trim()&&form.billing.city.trim()&&form.billing.country.trim());usePageMetadata(copy.title,copy.intro,'/booking');
 useEffect(()=>{Promise.all([listBookingResources(bookingLocale),listBookingCategories(bookingLocale)]).then(([resourceResult,categoryResult])=>{setResources(resourceResult.data.resources);setCategories(categoryResult.data.categories);setResourceId(current=>current||resourceResult.data.resources[0]?.id||'')}).catch(()=>setError(copy.error))},[bookingLocale,copy.error]);
 useEffect(()=>{if(!resourceId)return;const from=new Date(`${date}T00:00:00`),to=new Date(`${date}T23:59:59`);getAvailability(resourceId,from.toISOString(),to.toISOString()).then(result=>setIntervals(result.data.intervals)).catch(()=>setIntervals([]))},[date,resourceId]);
 useEffect(()=>{if(!selected||!form.startAt||!form.endAt)return;const timer=setTimeout(()=>{calculatePrice({bookingType:form.bookingType,internalAskPurpose:form.bookingType==='internal_ask'?form.internalAskPurpose:undefined,requesterEmail:form.requesterEmail||undefined,mandateYear:form.bookingType==='internal_ask'&&form.internalAskPurpose==='private_booking'?form.mandateYear:undefined,resourceSlug:selected.slug,startAt:new Date(form.startAt).toISOString(),endAt:new Date(form.endAt).toISOString(),kitchenExtra:form.kitchenExtra,saunaExtra:form.saunaExtra}).then(result=>{setEstimate(result.data.price);setError('')}).catch(()=>{setEstimate(null)})},250);return()=>clearTimeout(timer)},[selected,form.bookingType,form.internalAskPurpose,form.requesterEmail,form.mandateYear,form.startAt,form.endAt,form.kitchenExtra,form.saunaExtra]);
 const submit=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();if(!selected||!estimate)return;if(paid&&!billingComplete){setError(copy.billingIncomplete);return;}const submissionType=((event.nativeEvent as SubmitEvent).submitter as HTMLButtonElement)?.value==='quote_request'?'quote_request':'booking_request';setSending(true);setError('');try{const billing=estimate.totalPrice>0?{name:form.billing.name,address:form.billing.address,postalCode:form.billing.postalCode,city:form.billing.city,country:form.billing.country,vatOrBusinessId:form.billing.vatOrBusinessId||undefined,referenceNumber:form.billing.referenceNumber||undefined}:undefined;const input:BookingRequest={resourceId,resourceSlug:selected.slug,startAt:new Date(form.startAt).toISOString(),endAt:new Date(form.endAt).toISOString(),requesterName:form.requesterName,requesterEmail:form.requesterEmail,requesterPhone:form.requesterPhone||undefined,organization:form.organization||undefined,bookingType:form.bookingType,internalAskPurpose:form.bookingType==='internal_ask'?form.internalAskPurpose:undefined,mandateYear:form.bookingType==='internal_ask'&&form.internalAskPurpose==='private_booking'?form.mandateYear:undefined,kitchenExtra:form.kitchenExtra,saunaExtra:form.saunaExtra,billingAddress:billing,purpose:form.purpose,attendees:Number(form.attendees),accessibilityNeeds:form.accessibilityNeeds||undefined,locale:bookingLocale,submissionType,privacyAccepted:true};setConfirmation((await createBooking(input)).data.booking)}catch{setError(copy.error)}finally{setSending(false)}};
 const field=(label:string,key:keyof typeof form.billing,required=false)=><label className="font-semibold">{label}<input required={required} value={form.billing[key]} onChange={event=>setForm({...form,billing:{...form.billing,[key]:event.target.value}})} className="mt-2 w-full rounded-xl border p-3"/></label>;
 return <PublicLayout><PageHero compact eyebrow={copy.eyebrow} title={copy.title} description={copy.intro} secondaryAction={{label:copy.statusLink,href:'/booking/status'}}/><div className="ask-container space-y-10 py-14 sm:py-20"><section className="flex flex-wrap items-center justify-end gap-3"><label className="font-semibold">{copy.language}<select value={bookingLocale} onChange={event=>setBookingLocale(event.target.value as BookingLocale)} className="ml-3 rounded-xl border p-2"><option value="sv">Svenska</option><option value="en">English</option><option value="fi">Suomi</option></select></label></section>
 <section><div className="flex justify-between gap-4"><h2 className="text-3xl font-black">{copy.resources}</h2><Link className="font-bold text-ask-600" to="/booking/status">{copy.statusLink}</Link></div><div className="mt-6 grid gap-5 md:grid-cols-3">{resources.map(resource=><button type="button" key={resource.id} onClick={()=>setResourceId(resource.id)} aria-pressed={resource.id===resourceId} className={`ask-card p-6 text-left ${resource.id===resourceId?'border-ask-600 ring-2 ring-ask-600/20':''}`}><h3 className="text-xl font-black">{resource.name}</h3><p className="mt-1 text-sm font-semibold text-ask-600">{resource.floor}</p><p className="mt-3 text-sm leading-6 text-black/60 dark:text-white/60">{resource.description}</p><p className="mt-4">{copy.capacity}: {resource.capacity} {copy.people}</p></button>)}</div></section>
 {selected&&<section className="grid gap-6 lg:grid-cols-2"><div className="ask-card p-6"><h2 className="text-2xl font-black">{selected.name}</h2><p className="mt-4"><b>{copy.accessibility}:</b> {selected.accessibility}</p><p className="mt-4 whitespace-pre-line"><b>{copy.rules}:</b> {selected.rules}</p></div><div className="ask-card p-6"><div className="flex flex-wrap justify-between gap-3"><h2 className="text-2xl font-black">{copy.availability}</h2><label>{copy.date}<input type="date" value={date} onChange={event=>setDate(event.target.value)} className="ml-3 rounded-xl border p-2"/></label></div><div className="mt-5 space-y-3">{ordered.length===0?<p className="rounded-xl bg-green-50 p-4 text-green-900">{copy.available}</p>:ordered.map((item,index)=><div key={`${item.startAt}-${index}`} className="flex justify-between rounded-xl bg-red-50 p-4 text-red-900"><strong>{item.kind==='booking'?copy.busy:copy.blackout}</strong><span>{formatTimeRange(item.startAt,item.endAt)}</span></div>)}</div></div></section>}
 <section className="ask-card p-6 sm:p-9"><h2 className="text-3xl font-black">{copy.request}</h2>{confirmation?<div className="mt-6 rounded-2xl bg-green-50 p-6 text-green-950"><h3 className="text-2xl font-black">{copy.success}</h3><p className="mt-4"><strong>{copy.reference}:</strong> {confirmation.reference}</p><p className="mt-3">{copy.save}</p><Link className="ask-button-primary mt-5" to="/booking/status">{copy.check}</Link></div>:<form onSubmit={submit} className="mt-6 grid gap-5 md:grid-cols-2">
 <label className="font-semibold">{copy.bookingType}<select value={form.bookingType} onChange={event=>setForm({...form,bookingType:event.target.value as BookingType})} className="mt-2 w-full rounded-xl border p-3"><option value="" disabled>Select</option>{categories.map(category=><option key={category.key} value={category.key}>{category.name}</option>)}</select></label><label className="font-semibold">{copy.attendees}<input required min="1" max={selected?.capacity||80} type="number" value={form.attendees} onChange={event=>setForm({...form,attendees:Number(event.target.value)})} className="mt-2 w-full rounded-xl border p-3"/></label>
 {form.bookingType==='internal_ask'&&<><label className="font-semibold">{copy.internalPurpose}<select value={form.internalAskPurpose} onChange={event=>setForm({...form,internalAskPurpose:event.target.value as typeof form.internalAskPurpose})} className="mt-2 w-full rounded-xl border p-3"><option value="official_activity">{copy.official}</option><option value="private_booking">{copy.privateBooking}</option></select></label>{form.internalAskPurpose==='private_booking'&&<label className="font-semibold">{copy.mandateYear}<input required type="number" value={form.mandateYear} onChange={event=>setForm({...form,mandateYear:Number(event.target.value)})} className="mt-2 w-full rounded-xl border p-3"/></label>}</>}
 <label className="font-semibold">{copy.start}<input required type="datetime-local" value={form.startAt} onChange={event=>setForm({...form,startAt:event.target.value})} className="mt-2 w-full rounded-xl border p-3"/></label><label className="font-semibold">{copy.end}<input required type="datetime-local" value={form.endAt} onChange={event=>setForm({...form,endAt:event.target.value})} className="mt-2 w-full rounded-xl border p-3"/></label><label className="font-semibold">{copy.name}<input required value={form.requesterName} onChange={event=>setForm({...form,requesterName:event.target.value})} className="mt-2 w-full rounded-xl border p-3"/></label><label className="font-semibold">{copy.email}<input required type="email" value={form.requesterEmail} onChange={event=>setForm({...form,requesterEmail:event.target.value})} className="mt-2 w-full rounded-xl border p-3"/></label><label className="font-semibold">{copy.phone}<input value={form.requesterPhone} onChange={event=>setForm({...form,requesterPhone:event.target.value})} className="mt-2 w-full rounded-xl border p-3"/></label><label className="font-semibold">{copy.organization}<input value={form.organization} onChange={event=>setForm({...form,organization:event.target.value})} className="mt-2 w-full rounded-xl border p-3"/></label>
 <label className="flex gap-3"><input type="checkbox" checked={form.kitchenExtra} onChange={event=>setForm({...form,kitchenExtra:event.target.checked})}/>{copy.kitchen}</label><label className="flex gap-3"><input type="checkbox" checked={form.saunaExtra} onChange={event=>setForm({...form,saunaExtra:event.target.checked})}/>{copy.sauna}</label><label className="font-semibold md:col-span-2">{copy.purpose}<textarea required rows={4} value={form.purpose} onChange={event=>setForm({...form,purpose:event.target.value})} className="mt-2 w-full rounded-xl border p-3"/></label><label className="font-semibold md:col-span-2">{copy.needs}<textarea rows={3} value={form.accessibilityNeeds} onChange={event=>setForm({...form,accessibilityNeeds:event.target.value})} className="mt-2 w-full rounded-xl border p-3"/></label>
 {estimate&&<section className="rounded-2xl bg-ask-50 p-5 md:col-span-2 dark:bg-white/10"><h3 className="text-xl font-black">{copy.price}</h3><dl className="mt-4 grid gap-2 sm:grid-cols-2"><div><dt>{copy.rentalPrice}</dt><dd className="font-bold">{euros(estimate.rentalPrice)}</dd></div><div><dt>{copy.kitchen}</dt><dd className="font-bold">{euros(estimate.kitchenFee)}</dd></div><div><dt>{copy.sauna}</dt><dd className="font-bold">{euros(estimate.saunaFee)}</dd></div><div><dt>{copy.discount}</dt><dd className="font-bold">{estimate.benefitApplied?estimate.benefitApplied:euros(estimate.discount)}</dd></div><div className="sm:col-span-2"><dt>{copy.total}</dt><dd className="text-2xl font-black">{euros(estimate.totalPrice)}</dd></div></dl></section>}
 {estimate&&estimate.totalPrice>0&&<fieldset className="grid gap-4 rounded-2xl border p-5 md:col-span-2"><legend className="px-2 text-xl font-black">{copy.billing}</legend>{field(copy.billingName,'name',true)}{field(copy.address,'address',true)}{field(copy.postalCode,'postalCode',true)}{field(copy.city,'city',true)}{field(copy.country,'country',true)}{field(copy.vat,'vatOrBusinessId')}{field(copy.billingReference,'referenceNumber')}</fieldset>}
 <label className="flex gap-3 md:col-span-2"><input required type="checkbox" checked={form.privacyAccepted} onChange={event=>setForm({...form,privacyAccepted:event.target.checked})}/><span>{copy.privacy} <Link className="text-ask-600 underline" to="/privacy">Privacy</Link></span></label>{error&&<p role="alert" className="rounded-xl bg-red-50 p-4 text-red-800 md:col-span-2">{error}</p>}<div className="flex flex-wrap gap-3 md:col-span-2"><button disabled={sending||!estimate} value="booking_request" className="ask-button-primary">{sending?copy.sending:copy.submit}</button> {selectedCategory?.quoteRequestAllowed&&<button disabled={sending||!estimate} value="quote_request" className="ask-button-secondary">{copy.quote}</button>}</div>
 </form>}</section></div></PublicLayout>;
}
