import { useEffect, useMemo, useState } from 'react'
import { Link } from 'react-router-dom'
import PublicLayout from '../components/PublicLayout'
import { usePageMetadata } from '../hooks/usePageMetadata'
import { collaborationsApi } from '../collaborations/api'
import { CollaborationType, CollaborationTypeOption, PublicCollaboration, PublicCollaborationSettings } from '../collaborations/types'
import { publicText } from '../content/publicLabels'
import { useSiteLocale } from '../hooks/useSiteLocale'

export default function Collaborations() {
  const { locale, content } = useSiteLocale(); const labels = publicText(locale)
  const [items, setItems] = useState<PublicCollaboration[]>([]), [types, setTypes] = useState<CollaborationTypeOption[]>([]), [settings, setSettings] = useState<PublicCollaborationSettings | null>(null), [type, setType] = useState<CollaborationType | ''>(''), [search, setSearch] = useState(''), [error, setError] = useState('')
  usePageMetadata(labels.collaborations, settings?.intro || labels.collaborations, '/samarbeten')
  const query = useMemo(() => { const params = new URLSearchParams(); if (type) params.set('type', type); if (search) params.set('search', search); return params.size ? `?${params}` : '' }, [type, search])
  useEffect(() => { let mounted = true; Promise.all([collaborationsApi.list(query), collaborationsApi.types(), collaborationsApi.settings()]).then(([list, typeList, cfg]) => { if (!mounted) return; setItems(list.data.collaborations); setTypes(typeList.data.types); setSettings(cfg.data.settings) }).catch(() => setError(locale === 'sv' ? 'Samarbeten är tillfälligt otillgängliga.' : 'Collaborations are temporarily unavailable.')); return () => { mounted = false } }, [query, locale])
  const featured = items.filter((item) => item.featured)
  return <PublicLayout><section className="ask-container py-12"><p className="font-semibold text-ask-600">{labels.collaborations}</p><h1 className="mt-2 text-4xl font-black tracking-tight md:text-5xl">{labels.collaborations}</h1><p className="mt-4 max-w-3xl text-lg text-black/65 dark:text-white/65">{settings?.intro || (locale === 'sv' ? 'ASK:s samarbeten, specialföreningar, studentnationer och partner.' : 'ASK collaborations, associations, student nations and partners.')}</p><div className="mt-8 grid gap-3 md:grid-cols-[1fr_260px]"><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder={locale === 'sv' ? 'Sök samarbeten' : 'Search collaborations'} className="rounded-2xl border border-black/10 bg-white px-4 py-3 dark:border-white/10 dark:bg-white/5" /><select value={type} onChange={(event) => setType(event.target.value as CollaborationType | '')} className="rounded-2xl border border-black/10 bg-white px-4 py-3 dark:border-white/10 dark:bg-white/5"><option value="">{labels.allTypes}</option>{types.map((option) => <option key={option.type} value={option.type}>{option.label}</option>)}</select></div>{error && <p className="mt-6 rounded-2xl bg-red-50 p-4 text-red-800">{error}</p>}{featured.length > 0 && <section className="mt-10"><h2 className="text-2xl font-black">{locale === 'sv' ? 'Utvalda samarbeten' : 'Featured collaborations'}</h2><div className="mt-4 grid gap-4 md:grid-cols-3">{featured.map((item) => <CollaborationCard key={item.id} item={item} />)}</div></section>}<section className="mt-10"><h2 className="text-2xl font-black">{content.nav.collaborations}</h2><div className="mt-4 grid gap-4 md:grid-cols-3">{items.map((item) => <CollaborationCard key={item.id} item={item} />)}</div>{!items.length && !error && <p className="rounded-2xl bg-white p-5 text-black/60 dark:bg-white/5 dark:text-white/60">{locale === 'sv' ? 'Inga samarbeten matchar filtret.' : 'No collaborations match the filter.'}</p>}</section></section></PublicLayout>
}
function CollaborationCard({ item }: { item: PublicCollaboration }) { return <article className="rounded-2xl border border-black/10 bg-white p-5 dark:border-white/10 dark:bg-white/5"><div className="flex items-start gap-4">{item.logoUrl && <img src={item.logoUrl} alt={item.logoAltText || ''} className="h-14 w-14 rounded-xl object-contain" />}<div><p className="text-sm font-semibold text-ask-600">{item.typeLabel}</p><h3 className="text-xl font-black"><Link to={`/samarbeten/${item.slug}`}>{item.name}</Link></h3></div></div><p className="mt-3 text-sm text-black/65 dark:text-white/65">{item.shortDescription || item.description}</p>{item.officeAtCor && <p className="mt-3 text-sm font-semibold">Cor House</p>}</article> }
