import { useQuery } from '@tanstack/react-query'
import PublicLayout from '../components/PublicLayout'
import PageHero from '../components/PageHero'
import { publicText } from '../content/publicLabels'
import { useSiteLocale } from '../hooks/useSiteLocale'
import { organizationApi } from '../organization/api'
import { formatDate } from '../utils/dateTime'

export default function EldersCouncil() {
  const { locale } = useSiteLocale()
  const labels = publicText(locale)
  const { data } = useQuery({ queryKey: ['elders-council', locale], queryFn: organizationApi.eldersCouncil })
  const council = data?.data.eldersCouncil
  return <PublicLayout><PageHero eyebrow={labels.organization} title={labels.elders} description={locale === 'sv' ? 'ASK:s rådgivande organ enligt stadgar och reglemente.' : 'ASK’s advisory body according to the statutes and regulations.'} /><section className="ask-container grid gap-8 py-12 lg:grid-cols-[1.25fr_.75fr]">{council && <><article className="rounded-2xl bg-white p-6 dark:bg-white/5"><h2 className="text-2xl font-black">{council.title}</h2><p className="mt-4 leading-7 text-black/65 dark:text-white/65">{council.description}</p><dl className="mt-6 grid gap-4 sm:grid-cols-2"><div><dt className="font-bold">{labels.role}</dt><dd>{labels.advisoryBody}</dd></div><div><dt className="font-bold">{labels.appointedBy}</dt><dd>{labels.council}</dd></div><div><dt className="font-bold">{labels.mandate}</dt><dd>{locale === 'sv' ? 'Nio medlemmar, tre år' : 'Nine members, three years'}</dd></div><div><dt className="font-bold">{labels.contact}</dt><dd><a className="text-ask-600" href={`mailto:${council.contactEmail}`}>{council.contactEmail}</a></dd></div></dl><p className="mt-6 text-sm leading-6 text-black/60 dark:text-white/60">{locale === 'sv' ? 'Fullmäktige kompletterar avgående medlemmar årligen vid höstmötet. Medlemmar kan vara utexaminerade från Arcada eller andra personer med god insyn i ASK:s verksamhet.' : 'The Student Council supplements outgoing members annually at the autumn meeting. Members may be Arcada graduates or other people with good insight into ASK’s activities.'}</p></article><aside className="rounded-2xl bg-white p-6 dark:bg-white/5"><h2 className="font-black">{labels.members}</h2>{council.members.length === 0 ? <p className="mt-3 text-sm text-black/60 dark:text-white/60">{locale === 'sv' ? 'Medlemmar publiceras senare.' : 'Members will be published later.'}</p> : <ul className="mt-3 space-y-3">{council.members.map((member) => <li key={member.name} className="border-t pt-3 first:border-t-0 first:pt-0"><b>{member.name}</b>{member.title && <span>, {member.title}</span>}{member.chairperson && <span> · {locale === 'sv' ? 'Ordförande' : 'Chairperson'}</span>}{member.secretary && <span> · {locale === 'sv' ? 'Sekreterare' : 'Secretary'}</span>}{(member.mandateStart || member.mandateEnd) && <p className="text-sm text-black/55 dark:text-white/55">{member.mandateStart ? formatDate(member.mandateStart) : ''} - {member.mandateEnd ? formatDate(member.mandateEnd) : ''}</p>}</li>)}</ul>}</aside></>}</section></PublicLayout>
}
