import { useQuery } from '@tanstack/react-query'
import { Link, useSearchParams } from 'react-router-dom'
import PublicLayout from '../components/PublicLayout'
import PageHero from '../components/PageHero'
import SectionHeading from '../components/SectionHeading'
import { governanceApi } from '../governance/api'
import { PublicGovernanceDocument } from '../governance/types'
import { useSiteLocale } from '../hooks/useSiteLocale'
import { formatDate } from '../utils/dateTime'
function List({ title, documents }: { title: string; documents: PublicGovernanceDocument[] }) { return <section className="rounded-2xl bg-white p-6 dark:bg-white/5"><h2 className="text-xl font-black">{title}</h2><div className="mt-4 space-y-3">{documents.length ? documents.map((doc) => <Link key={doc.id} to={`/styrning/dokument/${doc.slug}`} className="block rounded-xl border border-black/10 p-4 dark:border-white/10"><b>{doc.title}</b><p className="text-sm text-black/60 dark:text-white/60">{doc.meetingDate ? formatDate(doc.meetingDate) : doc.documentDate ? formatDate(doc.documentDate) : doc.year}</p></Link>) : <p className="text-sm text-black/60 dark:text-white/60">Inga publicerade dokument.</p>}</div></section> }
export default function FullmaktigeDocuments() { const { locale } = useSiteLocale(); const [params, setParams] = useSearchParams(); const year = params.get('year') || ''; const { data } = useQuery({ queryKey: ['fullmaktige-documents', locale, year], queryFn: () => governanceApi.fullmaktige(locale, year) }); return <PublicLayout><PageHero eyebrow="Fullmäktige / Student Council" title="Fullmäktige dokument" description="Kallelser, föredragningslistor och protokoll från ASK:s högsta beslutande organ." /><section className="ask-container py-12"><SectionHeading eyebrow="Offentlig styrning" title="Fullmäktige" description="Fullmäktige är ASK:s högsta beslutande organ. Protokoll är offentliga, men delar kan undanhållas om de innehåller uppgifter om privatpersoner eller annat material som inte ska publiceras." /><div className="mt-6 max-w-xs rounded-2xl bg-white p-4 dark:bg-white/5"><input placeholder="År" value={year} onChange={(event) => setParams(event.target.value ? { year: event.target.value } : {})} className="w-full rounded border p-2" /></div><div className="mt-8 grid gap-5 lg:grid-cols-3"><List title="Kallelser / Meeting notices" documents={data?.data.meetingNotices || []} /><List title="Föredragningslistor / Agendas" documents={data?.data.agendas || []} /><List title="Protokoll / Minutes" documents={data?.data.minutes || []} /></div></section></PublicLayout> }
