import { useQuery } from '@tanstack/react-query'
import { Link, useSearchParams } from 'react-router-dom'
import PublicLayout from '../components/PublicLayout'
import PageHero from '../components/PageHero'
import SectionHeading from '../components/SectionHeading'
import { publicText } from '../content/publicLabels'
import { governanceApi } from '../governance/api'
import { PublicGovernanceDocument } from '../governance/types'
import { useSiteLocale } from '../hooks/useSiteLocale'
import { formatDate } from '../utils/dateTime'
function List({ title, documents, empty }: { title: string; documents: PublicGovernanceDocument[]; empty: string }) { return <section className="rounded-2xl bg-white p-6 dark:bg-white/5"><h2 className="text-xl font-black">{title}</h2><div className="mt-4 space-y-3">{documents.length ? documents.map((doc) => <Link key={doc.id} to={`/styrning/dokument/${doc.slug}`} className="block rounded-xl border border-black/10 p-4 dark:border-white/10"><b>{doc.title}</b><p className="text-sm text-black/60 dark:text-white/60">{doc.meetingDate ? formatDate(doc.meetingDate) : doc.documentDate ? formatDate(doc.documentDate) : doc.year}</p></Link>) : <p className="text-sm text-black/60 dark:text-white/60">{empty}</p>}</div></section> }
export default function FullmaktigeDocuments() { const { locale } = useSiteLocale(); const labels = publicText(locale); const [params, setParams] = useSearchParams(); const year = params.get('year') || ''; const { data } = useQuery({ queryKey: ['fullmaktige-documents', locale, year], queryFn: () => governanceApi.fullmaktige(locale, year) }); const empty = locale === 'sv' ? 'Inga publicerade dokument.' : 'No published documents.'; return <PublicLayout><PageHero eyebrow={labels.council} title={labels.fullmaktigeDocuments} description={locale === 'sv' ? 'Kallelser, föredragningslistor och protokoll från ASK:s högsta beslutande organ.' : 'Meeting notices, agendas, and minutes from ASK’s highest decision-making body.'} /><section className="ask-container py-12"><SectionHeading eyebrow={labels.publicGovernance} title={labels.council} description={locale === 'sv' ? 'Fullmäktige är ASK:s högsta beslutande organ. Protokoll är offentliga, men delar kan undanhållas om de innehåller uppgifter om privatpersoner eller annat material som inte ska publiceras.' : 'The Student Council is ASK’s highest decision-making body. Minutes are public, but parts may be withheld if they contain private-person information or other material that should not be published.'} /><div className="mt-6 max-w-xs rounded-2xl bg-white p-4 dark:bg-white/5"><input placeholder={labels.year} value={year} onChange={(event) => setParams(event.target.value ? { year: event.target.value } : {})} className="w-full rounded border p-2" /></div><div className="mt-8 grid gap-5 lg:grid-cols-3"><List title={labels.meetingNotices} documents={data?.data.meetingNotices || []} empty={empty} /><List title={labels.agendas} documents={data?.data.agendas || []} empty={empty} /><List title={labels.minutes} documents={data?.data.minutes || []} empty={empty} /></div></section></PublicLayout> }
