import { useQuery } from '@tanstack/react-query'
import { Link, useParams } from 'react-router-dom'
import PublicLayout from '../components/PublicLayout'
import PageHero from '../components/PageHero'
import { publicText } from '../content/publicLabels'
import { governanceApi } from '../governance/api'
import { GovernanceDocumentType } from '../governance/types'
import { useSiteLocale } from '../hooks/useSiteLocale'
import { formatDate } from '../utils/dateTime'
const typeLabels = {
  sv: { meeting_notice: 'Kallelse', agenda: 'Föredragningslista', minutes: 'Protokoll', statutes: 'Stadgar', regulations: 'Reglemente', annual_report: 'Verksamhetsberättelse', financial_statement: 'Bokslut', policy: 'Policy', other: 'Annat' },
  en: { meeting_notice: 'Meeting notice', agenda: 'Agenda', minutes: 'Minutes', statutes: 'Statutes', regulations: 'Regulations', annual_report: 'Annual report', financial_statement: 'Financial statement', policy: 'Policy', other: 'Other' },
} satisfies Record<string, Record<GovernanceDocumentType, string>>
export default function GovernanceDocumentDetail() { const { slug = '' } = useParams(); const { locale } = useSiteLocale(); const labels = publicText(locale); const typeLabel = (type: GovernanceDocumentType) => typeLabels[locale][type] || type; const { data, isError } = useQuery({ queryKey: ['governance-document', slug, locale], queryFn: () => governanceApi.document(slug, locale), enabled: Boolean(slug), retry: false }); const document = data?.data.document; if (isError) return <PublicLayout><PageHero eyebrow={labels.governance} title={locale === 'sv' ? 'Dokumentet hittades inte' : 'Document not found'} description={locale === 'sv' ? 'Dokumentet finns inte eller är inte publicerat.' : 'The document does not exist or is not published.'} /><section className="ask-container py-12"><Link className="font-semibold text-ask-700" to="/styrning">{locale === 'sv' ? 'Till styrning' : 'To governance'}</Link></section></PublicLayout>; return <PublicLayout><PageHero eyebrow={labels.publicGovernance} title={document?.title || labels.documents} description={document?.description || ''} />{document && <section className="ask-container grid gap-8 py-12 lg:grid-cols-[1.2fr_.8fr]"><article className="rounded-2xl bg-white p-6 dark:bg-white/5"><h2 className="text-2xl font-black">{document.title}</h2><p className="mt-4 leading-7 text-black/65 dark:text-white/65">{document.description}</p><a href={document.externalUrl || document.fileUrl} className="mt-6 inline-flex rounded-xl bg-ask-600 px-5 py-3 font-semibold text-white">{locale === 'sv' ? 'Öppna dokument' : 'Open document'}</a></article><aside className="rounded-2xl bg-white p-6 dark:bg-white/5"><h2 className="font-black">Metadata</h2><dl className="mt-4 space-y-3 text-sm"><div><dt className="font-bold">{locale === 'sv' ? 'Typ' : 'Type'}</dt><dd>{typeLabel(document.documentType)}</dd></div><div><dt className="font-bold">{locale === 'sv' ? 'Datum' : 'Date'}</dt><dd>{document.documentDate ? formatDate(document.documentDate) : document.meetingDate ? formatDate(document.meetingDate) : '-'}</dd></div><div><dt className="font-bold">{labels.year}</dt><dd>{document.year || '-'}</dd></div><div><dt className="font-bold">{locale === 'sv' ? 'Språk' : 'Language'}</dt><dd>{document.language}</dd></div>{document.fileName && <div><dt className="font-bold">{locale === 'sv' ? 'Filnamn' : 'File name'}</dt><dd>{document.fileName}</dd></div>}</dl></aside></section>}</PublicLayout> }
