import { useQuery } from '@tanstack/react-query'
import { Link, useSearchParams } from 'react-router-dom'
import PublicLayout from '../components/PublicLayout'
import PageHero from '../components/PageHero'
import SectionHeading from '../components/SectionHeading'
import { governanceApi } from '../governance/api'
import { GovernanceDocumentType, PublicGovernanceDocument } from '../governance/types'
import { useSiteLocale } from '../hooks/useSiteLocale'
import { formatDate } from '../utils/dateTime'
const types: GovernanceDocumentType[] = ['meeting_notice', 'agenda', 'minutes', 'statutes', 'regulations', 'annual_report', 'financial_statement', 'policy', 'other']
const typeLabel = (type: GovernanceDocumentType) => ({ meeting_notice: 'Kallelse', agenda: 'Föredragningslista', minutes: 'Protokoll', statutes: 'Stadgar', regulations: 'Reglemente', annual_report: 'Verksamhetsberättelse', financial_statement: 'Bokslut', policy: 'Policy', other: 'Annat' }[type])
function DocumentCard({ document }: { document: PublicGovernanceDocument }) { return <Link to={`/styrning/dokument/${document.slug}`} className="rounded-2xl bg-white p-5 shadow-sm transition hover:-translate-y-0.5 hover:shadow-xl dark:bg-white/5"><p className="text-sm font-bold text-ask-600">{typeLabel(document.documentType)} {document.year ? `· ${document.year}` : ''}</p><h2 className="mt-2 text-xl font-black">{document.title}</h2><p className="mt-3 text-sm leading-6 text-black/60 dark:text-white/60">{document.description}</p><p className="mt-4 text-sm">{document.documentDate ? formatDate(document.documentDate) : document.meetingDate ? formatDate(document.meetingDate) : ''}</p></Link> }
export default function Governance() { const { locale } = useSiteLocale(); const [params, setParams] = useSearchParams(); const type = params.get('type') || ''; const year = params.get('year') || ''; const query = new URLSearchParams(); if (type) query.set('documentType', type); if (year) query.set('year', year); const overview = useQuery({ queryKey: ['governance-overview', locale], queryFn: () => governanceApi.overview(locale) }); const docs = useQuery({ queryKey: ['governance-documents', locale, type, year], queryFn: () => governanceApi.documents(locale, query.toString()) }); return <PublicLayout><PageHero eyebrow="Offentlig styrning / Public Governance" title="Styrning" description="Offentliga styrdokument, Fullmäktigehandlingar, stadgar, reglemente, verksamhetsberättelser, bokslut och policyer." /><section className="ask-container py-12"><SectionHeading eyebrow="ASK" title="Offentliga dokument" description={overview.data?.data.settings.intro || 'ASK publicerar offentliga styrdokument här.'} /><div className="mt-8 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{overview.data?.data.sections.map((section) => <Link key={section.key} to={section.href} className="rounded-2xl border border-black/10 bg-white p-6 transition hover:-translate-y-0.5 hover:shadow-xl dark:border-white/10 dark:bg-white/5"><h2 className="text-xl font-black">{section.label}</h2><p className="mt-3 text-sm leading-6 text-black/60 dark:text-white/60">{section.description}</p></Link>)}</div></section><section className="ask-container py-12"><SectionHeading eyebrow="Dokument" title="Dokumentlista" description={overview.data?.data.settings.documentPolicyText || 'Endast publicerade offentliga dokument visas.'} /><div className="mt-6 grid gap-3 rounded-2xl bg-white p-4 dark:bg-white/5 md:grid-cols-2"><select value={type} onChange={(event) => setParams((current) => { const next = new URLSearchParams(current); event.target.value ? next.set('type', event.target.value) : next.delete('type'); return next })} className="rounded border p-2"><option value="">Alla typer</option>{types.map((item) => <option key={item} value={item}>{typeLabel(item)}</option>)}</select><input placeholder="År" value={year} onChange={(event) => setParams((current) => { const next = new URLSearchParams(current); event.target.value ? next.set('year', event.target.value) : next.delete('year'); return next })} className="rounded border p-2" /></div><div className="mt-8 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{docs.data?.data.documents.length ? docs.data.data.documents.map((document) => <DocumentCard key={document.id} document={document} />) : <p className="rounded-2xl bg-white p-6 text-black/60 dark:bg-white/5 dark:text-white/60">Inga publicerade dokument matchar filtret.</p>}</div></section></PublicLayout> }
