import { useQuery } from '@tanstack/react-query'
import { Link, useParams } from 'react-router-dom'
import PublicLayout from '../components/PublicLayout'
import PageHero from '../components/PageHero'
import { governanceApi } from '../governance/api'
import { useSiteLocale } from '../hooks/useSiteLocale'
import { formatDate } from '../utils/dateTime'
const typeLabel = (type: string) => ({ meeting_notice: 'Kallelse / Meeting notice', agenda: 'Föredragningslista / Agenda', minutes: 'Protokoll / Minutes', statutes: 'Stadgar / Statutes', regulations: 'Reglemente / Regulations', annual_report: 'Verksamhetsberättelse / Annual report', financial_statement: 'Bokslut / Financial statement', policy: 'Policy', other: 'Annat / Other' }[type] || type)
export default function GovernanceDocumentDetail() { const { slug = '' } = useParams(); const { locale } = useSiteLocale(); const { data, isError } = useQuery({ queryKey: ['governance-document', slug, locale], queryFn: () => governanceApi.document(slug, locale), enabled: Boolean(slug), retry: false }); const document = data?.data.document; if (isError) return <PublicLayout><PageHero eyebrow="Styrning" title="Dokumentet hittades inte" description="Dokumentet finns inte eller är inte publicerat." /><section className="ask-container py-12"><Link className="font-semibold text-ask-700" to="/styrning">Till styrning</Link></section></PublicLayout>; return <PublicLayout><PageHero eyebrow="Offentlig styrning" title={document?.title || 'Dokument'} description={document?.description || ''} />{document && <section className="ask-container grid gap-8 py-12 lg:grid-cols-[1.2fr_.8fr]"><article className="rounded-2xl bg-white p-6 dark:bg-white/5"><h2 className="text-2xl font-black">{document.title}</h2><p className="mt-4 leading-7 text-black/65 dark:text-white/65">{document.description}</p><a href={document.externalUrl || document.fileUrl} className="mt-6 inline-flex rounded-xl bg-ask-600 px-5 py-3 font-semibold text-white">Öppna dokument / Open document</a></article><aside className="rounded-2xl bg-white p-6 dark:bg-white/5"><h2 className="font-black">Metadata</h2><dl className="mt-4 space-y-3 text-sm"><div><dt className="font-bold">Typ</dt><dd>{typeLabel(document.documentType)}</dd></div><div><dt className="font-bold">Datum</dt><dd>{document.documentDate ? formatDate(document.documentDate) : document.meetingDate ? formatDate(document.meetingDate) : '-'}</dd></div><div><dt className="font-bold">År</dt><dd>{document.year || '-'}</dd></div><div><dt className="font-bold">Språk</dt><dd>{document.language}</dd></div>{document.fileName && <div><dt className="font-bold">Filnamn</dt><dd>{document.fileName}</dd></div>}</dl></aside></section>}</PublicLayout> }
