import { useQuery } from '@tanstack/react-query'
import { Link } from 'react-router-dom'
import PublicLayout from '../components/PublicLayout'
import PageHero from '../components/PageHero'
import SectionHeading from '../components/SectionHeading'
import { publicText } from '../content/publicLabels'
import { useSiteLocale } from '../hooks/useSiteLocale'
import { representativesApi } from '../representatives/api'
import { PublicRepresentativeCall } from '../representatives/types'
import { formatDate } from '../utils/dateTime'

const statusLabel = (status: PublicRepresentativeCall['status'], labels: ReturnType<typeof publicText>) => status === 'open' ? labels.open : status === 'closed' ? labels.closed : labels.comingSoon
const appointingLabel = (value: string, labels: ReturnType<typeof publicText>) => value === 'fullmaktige' ? labels.council : value === 'board' ? labels.board : labels.other

export default function StudentRepresentatives() {
  const { locale } = useSiteLocale()
  const labels = publicText(locale)
  const bodies = useQuery({ queryKey: ['representative-bodies', locale], queryFn: () => representativesApi.bodies(locale) })
  const current = useQuery({ queryKey: ['representative-current', locale], queryFn: () => representativesApi.current(locale) })
  const calls = useQuery({ queryKey: ['representative-calls', locale], queryFn: () => representativesApi.calls(locale) })
  return <PublicLayout><PageHero eyebrow={labels.organization} title={labels.representatives} description={locale === 'sv' ? 'ASK väljer studeranderepresentanter till olika organ inom Arcada enligt stadgar och reglemente.' : 'ASK appoints student representatives to different Arcada bodies according to the statutes and regulations.'} />
    <section className="ask-container py-12"><SectionHeading eyebrow={locale === 'sv' ? 'Förtroendeuppdrag' : 'Representative roles'} title={labels.representatives} description={locale === 'sv' ? 'Studeranderepresentanter för fram studerandeperspektivet i Arcadas organ. Modulen visar information och utlysningar; val och utnämningar sker enligt ASK:s stadgar, valstadga och reglemente.' : 'Student representatives bring the student perspective into Arcada bodies. This module shows information and calls; elections and appointments follow ASK’s statutes, election rules, and regulations.'} /><div className="mt-8 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{bodies.data?.data.bodies.map((body) => <Link key={body.id} to={`/organisation/studeranderepresentanter/${body.slug}`} className="rounded-2xl border border-black/10 bg-white p-6 transition hover:-translate-y-0.5 hover:shadow-xl dark:border-white/10 dark:bg-white/5"><h2 className="text-xl font-black">{body.name}</h2><p className="mt-3 text-sm leading-6 text-black/60 dark:text-white/60">{body.description}</p><p className="mt-4 text-sm font-semibold">{body.defaultTermLengthMonths} {labels.months} · {appointingLabel(body.appointingBody, labels)}</p></Link>)}</div></section>
    <section className="ask-container py-12"><SectionHeading eyebrow={locale === 'sv' ? 'Aktuellt' : 'Current'} title={labels.calls} description={locale === 'sv' ? 'Öppna och kommande möjligheter att ansöka till förtroendeuppdrag.' : 'Open and upcoming opportunities to apply for representative roles.'} /><div className="mt-8 grid gap-4 md:grid-cols-2">{calls.data?.data.calls.length ? calls.data.data.calls.map((call) => <article key={call.id} className="rounded-2xl bg-white p-6 shadow-sm dark:bg-white/5"><p className="text-sm font-bold text-ask-600">{statusLabel(call.status, labels)}</p><h2 className="mt-2 text-xl font-black">{call.title}</h2><p className="mt-2 text-sm text-black/60 dark:text-white/60">{call.body?.name}</p><p className="mt-3 text-sm">{formatDate(call.openingDate)} - {formatDate(call.closingDate)} · {call.numberOfSeats} {labels.seats}</p><p className="mt-4 leading-7">{call.description}</p>{call.ctaUrl && call.status === 'open' && <a href={call.ctaUrl} className="mt-5 inline-flex rounded-xl bg-ask-600 px-5 py-3 font-semibold text-white">{call.ctaLabel || labels.apply}</a>}</article>) : <p className="rounded-2xl bg-white p-6 text-black/60 dark:bg-white/5 dark:text-white/60">{locale === 'sv' ? 'Inga publicerade utlysningar just nu.' : 'No published calls right now.'}</p>}</div></section>
    <section className="ask-container py-12"><SectionHeading eyebrow={labels.current} title={locale === 'sv' ? 'Representanter' : 'Representatives'} description={locale === 'sv' ? 'Publika representantprofiler visas när ASK har markerat dem som publika.' : 'Public representative profiles are shown when ASK has marked them as public.'} /><div className="mt-8 space-y-5">{current.data?.data.groups.length ? current.data.data.groups.map((group) => <article key={group.body.id} className="rounded-2xl bg-white p-6 dark:bg-white/5"><h2 className="text-xl font-black">{group.body.name}</h2><div className="mt-4 grid gap-3 md:grid-cols-2">{group.representatives.map((person) => <div key={person.id} className="rounded-xl border border-black/10 p-4 dark:border-white/10"><p className="font-bold">{person.fullName}</p><p className="text-sm text-black/60 dark:text-white/60">{person.role === 'deputy' ? labels.deputy : labels.representative} · {formatDate(person.termStart)} - {formatDate(person.termEnd)}</p>{person.description && <p className="mt-2 text-sm">{person.description}</p>}{person.email && <a className="mt-2 inline-block text-sm font-semibold text-ask-700" href={`mailto:${person.email}`}>{person.email}</a>}</div>)}</div></article>) : <p className="rounded-2xl bg-white p-6 text-black/60 dark:bg-white/5 dark:text-white/60">{locale === 'sv' ? 'Inga publika representantprofiler har publicerats ännu.' : 'No public representative profiles have been published yet.'}</p>}</div></section>
    <section className="ask-container pb-16"><div className="rounded-2xl bg-ask-600 p-6 text-white"><h2 className="text-2xl font-black">{labels.contact}</h2><p className="mt-2 max-w-2xl">{locale === 'sv' ? 'Frågor om studeranderepresentanter och utlysningar riktas till ASK.' : 'Questions about student representatives and calls should be directed to ASK.'}</p><a className="mt-4 inline-block font-semibold underline" href="mailto:info@asken.fi">info@asken.fi</a></div></section>
  </PublicLayout>
}
