export type CampaignStatus = 'coming_soon' | 'open' | 'closed'
export type CampaignType = 'tutor' | 'board' | 'student_council' | 'crew_member' | 'staff' | 'alumni' | 'other'
export interface PublicPerson { id: string; fullName: string; nickname?: string; slug: string; photoUrl?: string; photoAltText: string; positionTitle: string; description: string; responsibilities: string; email: string; phone?: string; languagesSpoken: string[]; roleBadges: Array<{ name: string; description: string; icon?: string; color?: string; link?: string }>; socialLinks: { instagram?: string; linkedIn?: string; website?: string }; officeHours?: string; type: string }
export interface PublicCommittee { id: string; name: string; slug: string; description: string; responsibilities: string; contactEmail?: string; contactPerson?: PublicPerson; members: PublicPerson[] }
export interface PublicStudentCouncil { title: string; description: string; speakerName?: string; speakerEmail?: string; viceSpeakerName?: string; viceSpeakerEmail?: string; contactEmail: string; members: Array<{ name: string; title?: string; displayOrder: number; active: boolean }>; documentLinks: Array<{ label: string; url: string; type: string }>; visible: boolean; updatedAt: string }
export interface PublicEldersCouncil { title: string; description: string; contactEmail: string; members: Array<{ name: string; title?: string; mandateStart?: string; mandateEnd?: string; chairperson: boolean; secretary: boolean; displayOrder: number; active: boolean }>; visible: boolean; updatedAt: string }
export interface PublicCampaign { id: string; title: string; description: string; type: CampaignType; openingDate: string; closingDate: string; ctaLabel: string; ctaUrl: string; contactPerson?: PublicPerson; contactEmail?: string; featured: boolean; status: CampaignStatus }
export interface PublicAlumni { title: string; intro: string; body: string; heroImageUrl?: string; heroImageAltText: string; benefits: string[]; ctaPrimaryLabel: string; ctaPrimaryUrl: string; ctaSecondaryLabel?: string; ctaSecondaryUrl?: string; contactEmail?: string; published: boolean; updatedAt: string }
export interface OrganizationOverview { sections: Array<{ key: string; label: string; href: string; description: string }>; featuredCampaigns: PublicCampaign[] }
