import { z } from 'zod';
export const objectIdSchema = z.string().regex(/^[a-f\d]{24}$/i, 'Expected MongoDB ObjectId');
const localizedTextSchema = z.object({ sv: z.string().trim().max(5000).default(''), en: z.string().trim().max(5000).default('') });
const optionalText = z.string().trim().max(5000).optional().or(z.literal(''));
const optionalDate = z.preprocess((value) => value === '' || value === null ? undefined : value, z.coerce.date().optional());
export const themeLocaleSchema = z.preprocess((value) => value || 'sv', z.enum(['sv', 'en']));
export const themeInputSchema = z.object({
  key: z.string().trim().min(1).max(120).regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/), name: localizedTextSchema, description: localizedTextSchema.optional(), type: z.enum(['seasonal', 'campaign', 'recruitment', 'event', 'custom']), status: z.enum(['draft', 'active', 'inactive', 'archived']), enabled: z.boolean().default(false), automaticActivation: z.boolean().default(false), manualOverride: z.boolean().default(false), priority: z.coerce.number().int().default(0), recurringYearly: z.boolean().default(false), startDate: optionalDate, endDate: optionalDate, startMonthDay: z.string().regex(/^\d{2}-\d{2}$/).optional().or(z.literal('')), endMonthDay: z.string().regex(/^\d{2}-\d{2}$/).optional().or(z.literal('')), timezone: z.string().trim().default('Europe/Helsinki'),
  decorationType: z.enum(['none', 'ducks', 'snow', 'confetti', 'pride', 'candles', 'flowers', 'pumpkins', 'sparkles', 'ribbons', 'custom']), accentColor: optionalText, secondaryAccentColor: optionalText, bannerImageUrl: optionalText, mascotImageUrl: optionalText, decorativeAssetUrl: optionalText, backgroundPatternUrl: optionalText, logoVariantUrl: optionalText, chatbotMascotAssetUrl: optionalText, animationEnabled: z.boolean().default(false), respectReducedMotion: z.boolean().default(true),
  announcementTitle: localizedTextSchema, announcementText: localizedTextSchema, heroTitle: localizedTextSchema, heroText: localizedTextSchema, ctaPrimaryLabel: localizedTextSchema.optional(), ctaPrimaryUrl: optionalText, ctaSecondaryLabel: localizedTextSchema.optional(), ctaSecondaryUrl: optionalText, homepageCardTitle: localizedTextSchema.optional(), homepageCardText: localizedTextSchema.optional(), homepageCardUrl: optionalText,
  showOnHomepage: z.boolean().default(false), showAnnouncementBar: z.boolean().default(false), showHeroDecoration: z.boolean().default(false), showNavigationBadge: z.boolean().default(false), highlightedNavItems: z.array(z.string().trim().max(80)).default([]), targetPages: z.array(z.enum(['home', 'membership', 'events', 'booking', 'organization', 'governance', 'recruitment', 'all'])).default(['home']), campaignType: z.enum(['gulis', 'tutor_recruitment', 'board_recruitment', 'student_council_election', 'crew_recruitment', 'staff_recruitment', 'custom']).optional().or(z.literal('')), externalCtaUrl: optionalText, relatedRecruitmentCampaignId: optionalText,
});
