export type LocalizedText = { sv: string; en: string }
export type PersonType = 'board' | 'staff' | 'council' | 'committee' | 'alumni' | 'other'
export type CampaignType = 'tutor' | 'board' | 'student_council' | 'crew_member' | 'staff' | 'alumni' | 'other'
export type CampaignStatus = 'coming_soon' | 'open' | 'closed'
export interface RoleBadge { id: string; name: LocalizedText; description: LocalizedText; icon?: string; color?: string; link?: string; active: boolean; displayOrder: number }
export interface Person { id: string; fullName: string; nickname?: string; slug: string; photoUrl?: string; photoAltText: LocalizedText; positionTitle: LocalizedText; description: LocalizedText; responsibilities: LocalizedText; email: string; phone?: string; languagesSpoken: string[]; roleBadgeIds: string[]; socialLinks: { instagram?: string; linkedIn?: string; website?: string }; officeHours?: Partial<LocalizedText>; type: PersonType; displayOrder: number; active: boolean; visible: boolean; startDate?: string; endDate?: string }
export interface Committee { id: string; name: LocalizedText; slug: string; description: LocalizedText; responsibilities: LocalizedText; contactEmail?: string; contactPersonId?: string; personIds: string[]; active: boolean; visible: boolean; displayOrder: number }
export interface StudentCouncil { title: LocalizedText; description: LocalizedText; speakerName?: string; speakerEmail?: string; viceSpeakerName?: string; viceSpeakerEmail?: string; contactEmail: string; members: Array<{ name: string; title?: string; displayOrder: number; active: boolean }>; documentLinks: Array<{ label: LocalizedText; url: string; type: 'agenda' | 'protocol' | 'bylaws' | 'other' }>; visible: boolean }
export interface Campaign { id: string; title: LocalizedText; description: LocalizedText; type: CampaignType; openingDate: string; closingDate: string; ctaLabel: LocalizedText; ctaUrl: string; contactPersonId?: string; contactEmail?: string; featured: boolean; published: boolean; status: CampaignStatus; displayOrder: number; active: boolean }
export interface AlumniContent { title: LocalizedText; intro: LocalizedText; body: LocalizedText; heroImageUrl?: string; heroImageAltText: LocalizedText; benefits: LocalizedText[]; ctaPrimaryLabel: LocalizedText; ctaPrimaryUrl: string; ctaSecondaryLabel?: LocalizedText; ctaSecondaryUrl?: string; contactEmail?: string; published: boolean }
