"use client";
import {useEffect,useState} from "react";
import {ArrowLeft,Mail,PlugZap,RefreshCw,Save} from "lucide-react";
import {Button} from "@/components/ui/button";
import {Input} from "@/components/ui/input";
import {Label} from "@/components/ui/label";
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from "@/components/ui/select";
import {Switch} from "@/components/ui/switch";
import {Textarea} from "@/components/ui/textarea";
type Integration={id:string;provider:string;category:string;status:string;purpose:string;personalData:string;dataRegion:string;dpaReviewedAt:string|null;enabled:boolean};type IntegrationForm=Omit<Integration,"id">&{id?:string};type Notification={id:string;template:string;recipient:string;locale:string;status:string;attempts:number;lastError:string;createdAt:string};
const defaults=[{provider:"Email provider",category:"email",purpose:"Transactional confirmations and case notifications"},{provider:"Kide.app",category:"membership",purpose:"Membership products, status and event tickets"},{provider:"Lime CRM",category:"crm",purpose:"Future member and stakeholder relationship management"},{provider:"Privacy-friendly analytics",category:"analytics",purpose:"Aggregate website usage statistics"},{provider:"Accounting system",category:"accounting",purpose:"Invoice basis and reconciliation"},{provider:"Payment provider",category:"payment",purpose:"Future online deposits and payments"}];
const blank:IntegrationForm={provider:"",category:"other",status:"planned",purpose:"",personalData:"",dataRegion:"",dpaReviewedAt:null,enabled:false};
export default function IntegrationDashboard(){const[items,setItems]=useState<Integration[]>([]),[notifications,setNotifications]=useState<Notification[]>([]),[form,setForm]=useState<IntegrationForm>(blank),[message,setMessage]=useState("");async function load(){const r=await fetch("/api/admin/platform"),d=await r.json();if(r.ok){setItems(d.integrations||[]);setNotifications(d.notifications||[])}}useEffect(()=>{load()},[]);async function save(value:IntegrationForm=form){const r=await fetch("/api/admin/platform",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({entity:"integration",data:value})}),d=await r.json();if(!r.ok)return setMessage(d.error||"Error");setMessage("Saved");setForm(blank);await load()}async function addDefaults(){for(const item of defaults)if(!items.some(x=>x.category===item.category))await save({...blank,...item});await load()}
 return <main className="integration-admin"><header><a href="/admin/platform"><ArrowLeft/>Platform</a><div><span>ASK Backoffice</span><h1>Integrations & processors</h1></div><Button variant="outline" onClick={load}><RefreshCw/></Button></header><p className="integration-warning">No external connection is enabled automatically. Add the supplier, purpose, personal data, region and DPA review before credentials are configured outside this page.</p><section className="integration-grid"><div className="integration-form"><h2><PlugZap/>Processor register</h2><div><Label>Provider</Label><Input value={form.provider} onChange={e=>setForm({...form,provider:e.target.value})}/></div><div><Label>Category</Label><Select value={form.category} onValueChange={v=>setForm({...form,category:v})}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{["email","membership","crm","analytics","calendar","accounting","payment","other"].map(x=><SelectItem value={x} key={x}>{x}</SelectItem>)}</SelectContent></Select></div><div><Label>Status</Label><Select value={form.status} onValueChange={v=>setForm({...form,status:v})}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{["planned","configured","active","paused"].map(x=><SelectItem value={x} key={x}>{x}</SelectItem>)}</SelectContent></Select></div><div><Label>Purpose</Label><Textarea value={form.purpose} onChange={e=>setForm({...form,purpose:e.target.value})}/></div><div><Label>Personal data</Label><Textarea value={form.personalData} onChange={e=>setForm({...form,personalData:e.target.value})}/></div><div><Label>Data region</Label><Input value={form.dataRegion} onChange={e=>setForm({...form,dataRegion:e.target.value})}/></div><div><Label>DPA reviewed</Label><Input type="date" value={form.dpaReviewedAt?.slice(0,10)||""} onChange={e=>setForm({...form,dpaReviewedAt:e.target.value||null})}/></div><label><Switch checked={form.enabled} onCheckedChange={v=>setForm({...form,enabled:v})}/> Enabled only after technical and legal approval</label>{message&&<p>{message}</p>}<div><Button onClick={()=>save()}><Save/>Save</Button><Button variant="outline" onClick={addDefaults}>Add planned providers</Button></div></div><div className="integration-list">{items.map(item=><button key={item.id} onClick={()=>setForm(item)}><b>{item.provider}</b><span>{item.category} · {item.status} · {item.enabled?"enabled":"disabled"}</span><small>{item.purpose}</small></button>)}</div></section><section className="notification-panel"><h2><Mail/>Notification outbox</h2><p>Messages remain pending until an approved email provider is connected.</p>{notifications.map(item=><article key={item.id}><span>{item.status}</span><div><b>{item.template}</b><small>{item.recipient} · {item.locale}</small></div><time>{new Date(item.createdAt).toLocaleString("fi-FI",{dateStyle:"short",timeStyle:"short",hour12:false})}</time></article>)}</section></main>}
