import { Schema, model, models } from 'mongoose';
const localizedTextSchema = new Schema({ sv: { type: String, default: '' }, en: { type: String, default: '' } }, { _id: false });
const websiteThemeSchema = new Schema({
  key: { type: String, required: true, unique: true, trim: true, lowercase: true }, name: { type: localizedTextSchema, required: true }, description: localizedTextSchema,
  type: { type: String, required: true, enum: ['seasonal', 'campaign', 'recruitment', 'event', 'custom'] }, status: { type: String, required: true, enum: ['draft', 'active', 'inactive', 'archived'], default: 'draft' }, enabled: { type: Boolean, default: false }, automaticActivation: { type: Boolean, default: false }, manualOverride: { type: Boolean, default: false }, priority: { type: Number, default: 0 }, recurringYearly: { type: Boolean, default: false }, startDate: Date, endDate: Date, startMonthDay: String, endMonthDay: String, timezone: { type: String, default: 'Europe/Helsinki' },
  decorationType: { type: String, enum: ['none', 'ducks', 'snow', 'confetti', 'pride', 'candles', 'flowers', 'pumpkins', 'sparkles', 'ribbons', 'custom'], default: 'none' }, accentColor: String, secondaryAccentColor: String, bannerImageUrl: String, mascotImageUrl: String, decorativeAssetUrl: String, backgroundPatternUrl: String, logoVariantUrl: String, chatbotMascotAssetUrl: String, animationEnabled: { type: Boolean, default: false }, respectReducedMotion: { type: Boolean, default: true },
  announcementTitle: { type: localizedTextSchema, default: () => ({}) }, announcementText: { type: localizedTextSchema, default: () => ({}) }, heroTitle: { type: localizedTextSchema, default: () => ({}) }, heroText: { type: localizedTextSchema, default: () => ({}) }, ctaPrimaryLabel: localizedTextSchema, ctaPrimaryUrl: String, ctaSecondaryLabel: localizedTextSchema, ctaSecondaryUrl: String, homepageCardTitle: localizedTextSchema, homepageCardText: localizedTextSchema, homepageCardUrl: String,
  showOnHomepage: { type: Boolean, default: false }, showAnnouncementBar: { type: Boolean, default: false }, showHeroDecoration: { type: Boolean, default: false }, showNavigationBadge: { type: Boolean, default: false }, highlightedNavItems: { type: [String], default: [] }, targetPages: { type: [String], default: ['home'] }, campaignType: String, externalCtaUrl: String, relatedRecruitmentCampaignId: String, createdBy: String, updatedBy: String,
}, { timestamps: true });
websiteThemeSchema.index({ status: 1, enabled: 1, priority: -1, updatedAt: -1 });
export const WebsiteThemeModel = models.WebsiteTheme || model('WebsiteTheme', websiteThemeSchema);
