import { PublicLanguage } from '../localization/languages';

export type GovernanceLocale = PublicLanguage;
export type GovernanceDocumentType = 'meeting_notice' | 'agenda' | 'minutes' | 'statutes' | 'regulations' | 'annual_report' | 'financial_statement' | 'policy' | 'other';
export type GovernanceBody = 'fullmaktige' | 'student_union' | 'other';
export type GovernanceDocumentLanguage = 'sv' | 'en' | 'bilingual';
export interface LocalizedText { sv: string; en: string; }
export interface GovernanceDocument { id: string; title: LocalizedText; slug: string; description: LocalizedText; documentType: GovernanceDocumentType; governanceBody: GovernanceBody; meetingDate?: Date; publishDate?: Date; documentDate?: Date; year?: number; language: GovernanceDocumentLanguage; fileUrl: string; fileName?: string; externalUrl?: string; fileSize?: number; isPublic: boolean; isPublished: boolean; publishedAt?: Date; displayOrder: number; tags: LocalizedText; createdBy?: string; updatedBy?: string; createdAt: Date; updatedAt: Date; }
export interface GovernanceSettings { id: string; intro: LocalizedText; documentPolicyText: LocalizedText; contactEmail?: string; visible: boolean; updatedAt?: Date; }
export interface PublicGovernanceDocument { id: string; title: string; slug: string; description: string; documentType: GovernanceDocumentType; governanceBody: GovernanceBody; meetingDate?: Date; publishDate?: Date; documentDate?: Date; year?: number; language: GovernanceDocumentLanguage; fileUrl: string; fileName?: string; externalUrl?: string; fileSize?: number; publishedAt?: Date; displayOrder: number; tags: string; }
export interface GovernanceDocumentFilters { documentType?: GovernanceDocumentType; year?: number; governanceBody?: GovernanceBody; language?: GovernanceDocumentLanguage; published?: boolean; publicOnly?: boolean; }
export interface PublicGovernanceOverview { settings: { intro: string; documentPolicyText: string; contactEmail?: string; visible: boolean }; latestDocuments: PublicGovernanceDocument[]; sections: Array<{ key: string; label: string; href: string; description: string }>; }
export interface FullmaktigeDocumentsOverview { meetingNotices: PublicGovernanceDocument[]; agendas: PublicGovernanceDocument[]; minutes: PublicGovernanceDocument[]; }
export interface GovernanceService { overview(locale: GovernanceLocale): Promise<PublicGovernanceOverview>; listPublicDocuments(filters: GovernanceDocumentFilters, locale: GovernanceLocale): Promise<PublicGovernanceDocument[]>; getPublicDocument(slug: string, locale: GovernanceLocale): Promise<PublicGovernanceDocument>; fullmaktige(locale: GovernanceLocale, year?: number): Promise<FullmaktigeDocumentsOverview>; listDocuments(filters?: GovernanceDocumentFilters): Promise<GovernanceDocument[]>; createDocument(input: Omit<GovernanceDocument, 'id' | 'createdAt' | 'updatedAt'>): Promise<GovernanceDocument>; updateDocument(id: string, input: Omit<GovernanceDocument, 'id' | 'createdAt' | 'updatedAt'>): Promise<GovernanceDocument>; publishDocument(id: string, actorId?: string): Promise<GovernanceDocument>; unpublishDocument(id: string, actorId?: string): Promise<GovernanceDocument>; archiveDocument(id: string, actorId?: string): Promise<void>; getSettings(): Promise<GovernanceSettings>; updateSettings(input: Omit<GovernanceSettings, 'id' | 'updatedAt'>): Promise<GovernanceSettings>; }
