export type BookingStatus='submitted'|'quote_requested'|'quote_sent'|'approved'|'contract_generated'|'waiting_for_signature'|'signed'|'completed'|'cancelled'|'rejected';
export type BookingType='internal_ask'|'arcada_association'|'ask_member'|'alumni'|'external';
export interface LocalizedText{en:string;sv:string;fi:string}export interface OpeningHours{weekday:number;start:string;end:string}export interface BlackoutPeriod{startAt:string;endAt:string;reason?:LocalizedText}
export interface BookingResource{id:string;slug:string;name:LocalizedText;floor:LocalizedText;description:LocalizedText;location:LocalizedText;rules:LocalizedText;capacity:number;accessibility:LocalizedText;imageUrl?:string;active:boolean;requiresApproval:boolean;minDurationMinutes:number;maxDurationMinutes:number;advanceBookingDays:number;openingHours:OpeningHours[];blackoutPeriods:BlackoutPeriod[];createdAt:string;updatedAt:string}
export interface BookingCategory{ id:string; key:BookingType; name:LocalizedText; description:LocalizedText; active:boolean; displayOrder:number; billingAddressRequired:boolean; contractRequired:boolean; quoteRequestAllowed:boolean; public:boolean; createdAt:string; updatedAt:string }
export interface BookingPricingRule{ id:string; version:string; resourceId?:string; resourceSlug:string; bookingType:BookingType; active:boolean; displayOrder:number; validFrom:string; validUntil?:string; minimumHours:number; weekdayHourly?:number; weekendHourly?:number; weekdayFixedPrice?:number; weekendFixedPrice?:number; fixedBookingPrice?:number; firstHours?:number; firstHoursHourly?:number; additionalHourly?:number; kitchenFee:number; saunaFee:number; kitchenIncluded:boolean; saunaIncluded:boolean; manualOverrideAllowed:boolean; createdAt:string; updatedAt:string }
export interface PriceBreakdown{currency:'EUR';rentalPrice:number;kitchenFee:number;saunaFee:number;discount:number;totalPrice:number;minimumHours:number;billableHours:number;benefitApplied?:string;pricingRuleVersion:string;manualOverride:boolean}
export interface BillingAddress{name:string;address:string;postalCode:string;city:string;country:string;vatOrBusinessId?:string;referenceNumber?:string}
export interface ChecklistItem{key:string;label:string;completed:boolean;completedAt?:string;completedBy?:string}
export interface BookingRecord{id:string;reference:string;resourceId:string;resourceSlug:string;resource:BookingResource;startAt:string;endAt:string;requesterName:string;requesterEmail:string;requesterPhone?:string;organization?:string;billingAddress?:BillingAddress;bookingType:BookingType;internalAskPurpose?:'official_activity'|'private_booking';mandateYear?:number;kitchenExtra:boolean;saunaExtra:boolean;purpose:string;attendees:number;accessibilityNeeds?:string;locale:'en'|'sv'|'fi';submissionType:'booking_request'|'quote_request';status:BookingStatus;price:PriceBreakdown;quoteNotes?:string;publicNotes?:string;internalNotes?:string;checklist:ChecklistItem[];decisionAt?:string;createdAt:string;updatedAt:string}
export interface BookingHistory{id:string;action:string;status:BookingStatus;reference?:string;actorId?:string;note?:string;occurredAt:string}
export interface ContractMetadata{id:string;bookingId:string;bookingReference:string;generatedBy:string;generatedAt:string;language:'en'|'sv'|'fi';templateVersion:string;termsVersion:string;status:'contract_generated'|'waiting_for_signature'|'signed'}
export interface DashboardSummary{pendingApprovals:number;waitingForSignature:number;quoteRequests:number;upcomingThisWeek:number;completedThisMonth:number}
export interface CorHouseBookingSettings{doorCodeConfigured:boolean;doorCode?:string;landlordAddress?:string;landlordEmail?:string}
export interface ResourcePayload{slug?:string;name:LocalizedText;floor:LocalizedText;description:LocalizedText;location:LocalizedText;rules:LocalizedText;capacity:number;accessibility:LocalizedText;imageUrl?:string;active:boolean;requiresApproval:boolean;minDurationMinutes:number;maxDurationMinutes:number;advanceBookingDays:number;openingHours:OpeningHours[];blackoutPeriods:BlackoutPeriod[]}
